### ISSUE TITLE
Changing hostname to FQDN in agent config file creates duplicate entry in OCS inventory

### ISSUE THREAD

**Issue by xalasys-luc** [OCSInventory-NG/UnixAgent#112]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Unix
Perl version : 5.12

### OCS Inventory informations
Unix agent version : 2.3

### Problem's description
Original contents of agent config file:
     server = http://ocshost/ocsinventory
Run ocsagent for the first time, client system is added to the OCS inventory on ocshost.

Change contents of agent config file (same ocshost, but now with FQDN):
     server = http://ocshost.mydomain.com/ocsinventory
Run ocsagent again, client system now appears twice in the OCS inventory on ocshost.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
Hi,
Does the server merge duplicates?
Regards
Frank

**Comment by xalasys-luc** [comment]
No, the server does not merge entries, it just creates a second (identical) entry.
Regards,Luc


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: fbomj <notifications@github.com> Date: 2/27/18  11:19  (GMT+01:00) To: OCSInventory-NG/UnixAgent <UnixAgent@noreply.github.com> Cc: xalasys-luc <luc@xalasys.com>, Author <author@noreply.github.com> Subject: Re: [OCSInventory-NG/UnixAgent] Changing hostname to FQDN in agent
  config file creates duplicate entry in OCS inventory (#112) 
Hi,

Does the server merge duplicates?

Regards

Frank

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/OCSInventory-NG/UnixAgent","title":"OCSInventory-NG/UnixAgent","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/OCSInventory-NG/UnixAgent"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fbomj in #112: Hi,\r\nDoes the server merge duplicates?\r\nRegards\r\nFrank"}],"action":{"name":"View Issue","url":"https://github.com/OCSInventory-NG/UnixAgent/issues/112#issuecomment-368820916"}}}
