### ISSUE TITLE
cannot compile the Agent

### ISSUE THREAD

**Issue by luca76** [OCSInventory-NG/UnixAgent#113]
Hi, I've installed all requirements in the readme, but there is one that is missing:
```
[Ocsinventory-Unix-Agent-2.3] $ perl Makefile.PL 
Can't locate lib/Ocsinventory/Agent/Config.pm in @INC (you may need to install the lib::Ocsinventory::Agent::Config module) (@INC contains: inc /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5) at Makefile.PL line 19.
```

Where's that library?

**Comment by fbomj** [comment]
Hi,

Edit Makefile.PL file and add a dot before the first slash in the line require 
before : require '/lib/Ocsinventory/Agent/Config.pm';
after    : require '**.**/lib/Ocsinventory/Agent/Config.pm';

This is corrected in the next version.

Regards
Frank
