### ISSUE TITLE
MacOSX 10.11.6 (El Capitan) Get few details of CPU

### ISSUE THREAD

**Issue by vitorinux** [OCSInventory-NG/UnixAgent#116]
## General informations
Operating system :  **MacOSX 10.11.6**
Perl version : This is perl 5, version 26, subversion 1 **(v5.26.1) built for darwin-thread-multi-2level**

## OCS Inventory informations
Unix agent version : Ocsinventory unified agent for UNIX, Linux and MacOSX 2.3.1

## Perl Modules Installed
+ **YAML**
+ **CPAN**
+ Digest::MD5 
+ XML::Simple 
+ Net::IP 
+ Mac::SysProfile 
+ Crypt::SSLeay 
+ Net::CUPS 
+ Net::SNMP 
+ Net::Netmask 
+ Nmap::Parser 
+ Data::UUID 
+ Parse::EDID 
+ Proc::Daemon 
+ Proc::PID::File 
+ Compress::Zlib 
+ Module::Install (Not required but installed)

## Problem's description
All works fine, but in comparison with WindowsAgent for example or Other Linux based OS like Ubuntu or Debian shows info that MacOSX don't show,

All information show below are sorted like appear on OCSEPORTS hardware table inside a machine imported. 

### WINDOWS, UBUNTU OR DEBIAN BASED (It was my goals)

+ Manufacturer
+ Type (All details like model and frequency included on this field _"Intel(R) Core(TM)2 Duo CPU E7500 @ 2.93GHz"_)
+ Serial Number
+ Frequency
+ Cores Number
+ L2 cache size (It depends of the CPU, something show L3 cache size)
+ Architecture (x86_64)
+ Data Width (64)
+ Current Address width (64)
+ Logical CPUS
+ Voltage (null)
+ Current Speed
+ Socket Type (CPU1)

### MacOSX 10.11.6 El Capitan 
+ Type (Only shows name of the model for example _"Intel Core 2 Duo"_)
+ Processor Speed (MHz)
+ Number

### Inventory log file ( optional )

I found this line in debug log, hope this help

[Mon Feb 12 14:00:48 2018][debug] Running Ocsinventory::Agent::Backend::OS::MacOS::CPU
[Mon Feb 12 14:00:49 2018][debug] PROCESSORN, PROCESSORS and PROCESSORT shouldn't be set directly anymore. Please use addCPU() method instead.

**Comment by fbomj** [comment]
Hi,
Fixed by PR https://github.com/OCSInventory-NG/UnixAgent/pull/158
Regards
Frank
