### ISSUE TITLE
Agent see only one monitor

### ISSUE THREAD

**Issue by ferdynand70** [OCSInventory-NG/UnixAgent#12]
Hi,

I have OCSInventory server 2.1.2 and i use OCS-NG_unified_unix_agent_v2.0.5. Agent see only one monitor Iiyama but i have one more monitor LG and agent can not see this.

I have installed get-edid 3.0.1 and parse-edid

Can i do something to see more?

**Comment by gillesdubois** [comment]
Hello,

You should try to install version 2.1. of the agent ... the 2.0.5 is quite old so, upgrading it may solve the problem.

Regards, Gilles Dubois.

**Comment by ferdynand70** [comment]
I tyr to install the last verssion of Linux Agent and nothing.. All computers have only one monitor in OCS console. Have anyone some idea?

**Comment by fbomj** [comment]
Hi,

Sorry for the delay. Could you please try with the latest version pushed 2 months ago?

Regards
Frank

**Comment by MyTheValentinus** [comment]
No update, i close this issue.
