### ISSUE TITLE
alias network devices not reported

### ISSUE THREAD

**Issue by tell1970** [OCSInventory-NG/UnixAgent#124]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  openSUSE 13.1
perl version: 5.18
### OCS Inventory informations
Unix agent version : 2.4.0 (but reports 2.3.1)

### Problem's description
After upgrade of agent to 2.4.0 alias devices like "ens32:service" are not part of the inventory anymore.

### Inventory log file ( optional )

[ocsinventory-agent.log](https://github.com/OCSInventory-NG/UnixAgent/files/1789309/ocsinventory-agent.log)

**Comment by tell1970** [comment]
I checked the code of Networks.pm and it looks like with the change to using "ip" instead of "ifconfig" we lose the information. The line containing the ip address should be checked for the keyword "secondary" after which the alias device name shows. If that keyword is present the device name should be changed.
I am not good enough with perl or regexes, else I would contribute the code.

**Comment by ivmaks** [comment]
I have a solution to this problem, next week I will send the pull-request

https://github.com/ivmaks/UnixAgent/commit/4c22dafc38aa4d7399415ce9c4ce2a3957865c73

**Comment by tell1970** [comment]
with v2.4.1 only 1 of 4 IP addresses is inventoried, all IPs related to alias devices are missing

**Comment by fbomj** [comment]
Currently working on the problem

**Comment by ivmaks** [comment]
plz check https://github.com/ivmaks/UnixAgent/blob/launchpad/lib/Ocsinventory/Agent/Backend/OS/Linux/Network/Networks.pm

**Comment by tell1970** [comment]
Thank you so much - I replaced Networks.pm with your version and all IPs are inventoried again. Great work!

**Comment by fbomj** [comment]
Thanks for the correction. This will be integrated in the next release.
Regards
