### ISSUE TITLE
The LSB.pm file is different for the Repo and Source version giving different OS name output.

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/UnixAgent#127]
I've noticed that the OS names are not consistantly displayed.

As can be seen in the screenshot below some of the Linux OS names differ. There are Centos,  CentOS 7.4.1708 and CentOS Linux release 7.4.1708 (Core) groups. (In the first 2 examples LSB_release is installed but in the 3rd it is not). Then the Windows devices are each grouped by the unique name + version rather than just OS name.

I'm trying to get the report view more constant so that I don't have to manually update my reports too much for OCSNG to quickly give me a list of Centos 6 or Centos 7 devices. Now there are some inside Centos and others inside Centos 7.4.1708. I'd prefer if they were all grouped as Windows, Centos, MacOS, FreeBSD and if I want to filter by version I can the add the column in the next view to sort them further.

The problem started by trying to simplify the installation of the agents. Some of the admins in my team felt uncomfortable installing from source. So they have installations using the Repo. My existing installations are version 2.3 from source.

That installations from Source give different OS results from Linux when using agent v 2.4 from the Repo vs 2.3 from source. I've also done Agent installation going back to older releases and found that there is 3 possible ways the OS can be reported which makes reporting a bit tricky. For constancy sake the 3rd version happens when no lsb_release is available and is therefore understandably different.

To resolve this going forward a single method should be used to report on the OS name. To start, best will be to look at all the different builds available and ensure they are using the same copy of LSB.pm for Linux devices.

Here is a list of assets to show the randomness in the report:
![os list](https://user-images.githubusercontent.com/13314239/38031491-9533e3d2-329b-11e8-833f-ce02a1861831.png)

### General informations
Operating system :  2 identical Centos 7.4 systems. One with Agent from source and the other with agent from Repo.
Perl version : 5.16

### OCS Inventory informations
Unix agent version : 2.4 from repo and 2.3 from source.

### Problem's description
Because the LSB.pm differ for the agents the OS value is captured differently depending on how the agent was installed. We'd prefer to use the Repo version to simplify our management of the agents.

The "wrong" version prints the OS name as **CentOS 7.4.1708** and the OS version is duplicated as **7.4.1708**.

The "correct" version prints the OS name as **CentOS** and the OS version as **7.4.1708** and work great in reports.

Here are the two LSB.pm files (this one is wrong):
```
package Ocsinventory::Agent::Backend::OS::Linux::Distro::LSB;

sub check {
    my $params = shift;
    my $common = $params->{common};
    $common->can_run("lsb_release")
}

sub run {
    my $params = shift;
    my $common = $params->{common};

    my $release;
    chomp($release =`lsb_release -is`);

    my $OSversion;
    chomp($OSversion =`lsb_release -rs`);

    $release .= " ";
    $release .= $OSversion;

    my $OSComment;
    chomp($OSComment =`uname -v`);

    $common->setHardware({
        OSNAME => $release,
        OSVERSION => $OSversion,
        OSCOMMENTS => "$OSComment"
    });
}

1;

```
Here is the other which is correct:
```
package Ocsinventory::Agent::Backend::OS::Linux::Distro::LSB;

sub check {
    my $params = shift;
    my $common = $params->{common};
    $common->can_run("lsb_release")
}

sub run {
    my $params = shift;
    my $common = $params->{common};

    my $release;
    foreach (`lsb_release -i`) {
        $release = $1 if /Distributor\sID:\s+(.+)/;
    }

    my $OSversion;
    foreach (`lsb_release -r`){
        $osversion = $1 if /Release:\s+(.+)/;
    }

    my $OSComment;
    chomp($OSComment =`uname -v`);

    $common->setHardware({
        OSNAME => $release,
        OSVERSION => $osversion,
        OSCOMMENTS => "$OSComment"
    });
}

1;
```

**Comment by fbomj** [comment]
Hi,

Corrected in 2.4.1 version.
Regards
Frank
