### ISSUE TITLE
Bad POD in lib/Ocsinventory/Agent/Common.pm

### ISSUE THREAD

**Issue by guimard** [OCSInventory-NG/UnixAgent#138]
lib/Ocsinventory/Agent/Common.pm contains POD but without minimal entries (=head1 NAME,...). So a bad manpage is build.

Severity: wishlist

### General informations
Operating system :  Any
Perl version : Any

### OCS Inventory informations
Unix agent version : 2.4.1

**Comment by fbomj** [comment]
Hi
Fixed.
Regards
