### ISSUE TITLE
RHEL / CentOS 7 : SElinux errors can be generated while trying to obtain EDID info

### ISSUE THREAD

**Issue by matt335672** [OCSInventory-NG/UnixAgent#151]
### General informations
Operating system :  RHEL / CentOS 7
Perl version : 5.16.3

### OCS Inventory informations
Unix agent version : 2.4.0-1 (from RPM)

### Problem's description
The RPM for the agent on RHEL 7 makes installation of the `/usr/sbin/monitor-get-edid-using-vbe` utility mandatory, as the agent pulls in the `monitor-edid` package.

When running the agent on a RHEL 7 server with SELinux enabled and no monitors connected, `/usr/sbin/monitor-get-edid-using-vbe` is run and generates harmless but annoying SELinux warnings in the audit log. Here is an example.

```
time->Mon Jun 11 07:22:01 2018
type=PROCTITLE msg=audit(1528698121.185:553): proctitle=2F7573722F7362696E2F6D6F6E69746F722D6765742D656469642D7573696E672D766265002D2D706F72740030
type=SYSCALL msg=audit(1528698121.185:553): arch=c000003e syscall=9 success=no exit=-13 a0=f000 a1=502 a2=7 a3=11 items=0 ppid=9515 pid=9516 auid=10321 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=pts0 ses=9 comm="monitor-get-edi" exe="/usr/sbin/monitor-get-edid-using-vbe" subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 key=(null)
type=AVC msg=audit(1528698121.185:553): avc:  denied  { mmap_zero } for  pid=9516 comm="monitor-get-edi" scontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 tclass=memprotect
```
This also happens in the (rarer) case of a monitor/KVM being connected which generates invalid EDID information (e.g. all-zeros). Sadly we have quite a few of these!

When a valid monitor is connected, no such warnings are generated for RHEL 7, as  the `Ocsinventory::Agent::Backend::OS::Generic::Screen` package is able to determine valid EDID information from the kernel. The `/usr/sbin/monitor-get-edid-using-vbe` is not run in this case.

The use of `/usr/sbin/monitor-get-edid-using-vbe` on RHEL-based systems is mentioned in [RHEL bugzilla 889581](https://bugzilla.redhat.com/show_bug.cgi?id=889581) from 2012). System managers may not want to install the utility on their systems and give it permissions to run.

I'm proposing making the following two small changes:-

1. Removing the "Requires: monitor-edid" line from the RHEL 7 ocsinventory-agent.spec file
2. Making a small change to `Ocsinventory::Agent::Backend::OS::Generic::Screen` to allow it to run if the monitor-edid package is not installed.

This would make the use of `monitor-get-edid-using-vbe` optional for RHEL 7 systems. If system managers want to go ahead and install it, they can still do so.
 
I have a small pull request for the second change above, which I'm happy to provide if you wish to proceed with this change. I cannot make a pull request for the first change as the RPM spec file is not held in the UnixAgent git repository, at least as far as I know.

**Comment by fbomj** [comment]
Hi,

Ok. You can propose your pull request.

Regards

**Comment by matt335672** [comment]
Pull request #152 created.

This patch or similar is recommended for the RHEL 7 `ocsinventory-agent.spec` file:-

```
--- ocsinventory-agent.spec.orig	2018-02-11 10:05:38.000000000 +0000
+++ ocsinventory-agent.spec	2018-06-12 08:22:50.228624840 +0100
@@ -98,7 +98,10 @@
 Requires:  net-tools
 Requires:  pciutils
 Requires:  nmap
+# RHEL 7 and later can get EDID info from sysfs
+%if 0%{?rhel} < 7
 Requires:  monitor-edid
+%endif
 Requires:  which
 Requires:  smartmontools
 Requires:  %{_sysconfdir}/logrotate.d
```

**Comment by kapouik** [comment]
Sorry for the delay : a new version of the agent was publish this morning with a separation in require dependancies.

You have now two version:
- ocsinventory-agent-core that come only with strictly needed dependancies
- ocsinventory-agent that come with full dependancies

As it, you can install core version and only other package you need for your servers.

new package are in testing on this URL : http://rpm.ocsinventory-ng.org/testing/
