### ISSUE TITLE
Empty BIOS serial number not handled correctly on Intel NUC

### ISSUE THREAD

**Issue by jmechnich** [OCSInventory-NG/UnixAgent#154]
### General informations
Operating system :  Debian (various versions)
Perl version : perl 5.24/5.26

### OCS Inventory informations
Unix agent version : 2.x

### Problem's description
On Intel NUC machines, the BIOS serial number is empty, or rather consists of whitespace characters. In earlier versions (i.e. 2:2.0.5-1.2 in Debian stretch) the UnixAgent automatically falls back on the CPU ID which at least in the case of the Intel NUCs from 2014 does not help as they all share the same CPU ID.

In the current version in Debian testing (2:2.4.1-2) even the fallback stopped working as it does not catch an all-whitespace BIOS serial number.

Therefore I propose the following fix which is ready to be submitted as a pull request:
https://github.com/OCSInventory-NG/UnixAgent/compare/master...jmechnich:fix-serial

**Comment by fbomj** [comment]
Hi
You can create the PR.
Regards

**Comment by jmechnich** [comment]
Done.

**Comment by fbomj** [comment]
Thanks. PR merged.
Regards
Frank
