### ISSUE TITLE
Missing files in my kit : ipdiscover

### ISSUE THREAD

**Issue by tusune** [OCSInventory-NG/UnixAgent#155]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Debian 8
Perl version : 5.20.2

### OCS Inventory informations
Unix agent version : 2.4.1

### Problem's description
My problem is simple :
I've done a wget or the unix agent files here : 
https://github.com/OCSInventory-NG/UnixAgent/releases/download/v2.4.1/Ocsinventory-unix-agent-2.4.1.tar.gz
Thats the download from the OCS inventory website.
Then a tar on it, ok, and when it come to do "perl Makefile.PL", it give me this error : 
Warning: the following files are missing in your kit:
	ipdiscover
So, there is no ipdiscover files at all, now i understand why it don't want to work, but how do i get those files ?

Thanks in advance,
Tusune

**Comment by fbomj** [comment]
Hi,

Have you installed gcc on your machine? gcc is needed for compiling ipdiscover tool.

Regards
Frank

**Comment by tusune** [comment]
Not at all, didn't know it was needed, i'll try it

**Comment by fbomj** [comment]
Ok. 
No matter.
