### ISSUE TITLE
AIX : wrong hardware memory value

### ISSUE THREAD

**Issue by nnn-dev** [OCSInventory-NG/UnixAgent#160]
### General informations
Operating system :  AIX 7.2
Perl version : 5.24.4

### OCS Inventory informations
Unix agent version : 2.4.1

### Problem's description
The report indicate a wrong value for Hardware/Memory.
Seems use the 4th field of `lsattr -EOlmem0` instead of 2nd field.

**Comment by fbomj** [comment]
Fix with https://github.com/OCSInventory-NG/UnixAgent/pull/161 PR
