### ISSUE TITLE
Error on AIX LVM

### ISSUE THREAD

**Issue by nnn-dev** [OCSInventory-NG/UnixAgent#162]
### General informations
Operating system :  AIX 7.1
Perl version : 5.24.4

### OCS Inventory informations
Unix agent version : 2.4.1

### Problem's description
Like in #77, when executing ocsinventory-agent we have these messages on error screen:

> 0516-306 : Unable to find  4 in the Device
>         Configuration Database.
> 0516-306 : Unable to find  4 in the Device
>         Configuration Database.
> 0516-306 lslv: Unable to find  4 in the Device
>         Configuration Database.
> 0516-306 lslv: Unable to find  4 in the Device
>         Configuration Database.
> 0516-306 : Unable to find volume group 1 in the Device
>         Configuration Database.
> 0516-306 : Unable to find volume group 1 in the Device
>         Configuration Database.

**Comment by nnn-dev** [comment]
The causes of theses messages are in AIX/LVM.pm

https://github.com/OCSInventory-NG/UnixAgent/blob/ae17ed8a3170a73d9751d003ce04997a4bf1f642/lib/Ocsinventory/Agent/Backend/OS/AIX/LVM.pm#L40
https://github.com/OCSInventory-NG/UnixAgent/blob/ae17ed8a3170a73d9751d003ce04997a4bf1f642/lib/Ocsinventory/Agent/Backend/OS/AIX/LVM.pm#L117

According https://perldoc.perl.org/functions/split.html, split returns the number of fields found if the variable is a scalar ($name). So instead to have the name of vg or lv, we have number (here 4 or 1).

**Comment by nnn-dev** [comment]
Another error on code.
https://github.com/OCSInventory-NG/UnixAgent/blob/ae17ed8a3170a73d9751d003ce04997a4bf1f642/lib/Ocsinventory/Agent/Backend/OS/AIX/LVM.pm#L72
https://github.com/OCSInventory-NG/UnixAgent/blob/ae17ed8a3170a73d9751d003ce04997a4bf1f642/lib/Ocsinventory/Agent/Backend/OS/AIX/LVM.pm#L103
https://github.com/OCSInventory-NG/UnixAgent/blob/ae17ed8a3170a73d9751d003ce04997a4bf1f642/lib/Ocsinventory/Agent/Backend/OS/AIX/LVM.pm#L135

Theses actions was made inner the loop when parsing the result of the command to have info on a specific lv, pv or vg.
This code must be outer the loop when all the command lines was collected.

**Comment by fbomj** [comment]
fixed #445
