### ISSUE TITLE
MacOS Drive detection type

### ISSUE THREAD

**Issue by AlroneRhyn** [OCSInventory-NG/UnixAgent#180]
Hi !

We got some issue regarding the differenties between macOS and Windows client and the way it categorise informations.

### General informations
Operating system :  macOS
Perl version : 5

### OCS Inventory informations
Unix agent version : 2.4.2

### Problem's description
Windows hard drives are correctly detected and classified whereas macOS client seems not to do so : There is no type associated.
Why do i care ? When i am importing ocs information to GLPI, the component synced is not the same : Hard drive for windows and drive (like DVD drive) for macos.

WIN:
![capture d ecran 2018-08-22 a 17 39 01](https://user-images.githubusercontent.com/8383459/44474167-4f12ae00-a632-11e8-83de-72d155f7e3ff.png)

macOS:
![capture d ecran 2018-08-22 a 17 38 45](https://user-images.githubusercontent.com/8383459/44474180-546ff880-a632-11e8-9759-44963af2ada2.png)

Thank you very much

**Comment by fbomj** [comment]
Fixed with PR #278
