### ISSUE TITLE
OCS-Inventory-NG fails to run (Perl 5.22.3)

### ISSUE THREAD

**Issue by alebersol** [OCSInventory-NG/UnixAgent#185]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  PCLinuxOS 
Perl version : 5.22.3

### OCS Inventory informations
Unix agent version : 2.1.1 and tried the latest 2.4.2

### Problem's description
After successfully converting it to  PCLinuxOS  RPM, when I try to invoke the ocs-inventory-agent, to test it, it displays an error message 

### Inventory log file ( optional )
*Use github cloud or trusted upload website*
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*
[ocs-inventory-agent-ng_error.txt](https://github.com/OCSInventory-NG/UnixAgent/files/2550461/ocs-inventory-agent-ng_error.txt)

**Comment by fbomj** [comment]
Hi
Install the missing module and relaunch an inventory after to test if it's good.

Regards

**Comment by alebersol** [comment]
> Hi
> Install the missing module and relaunch an inventory after to test if it's good.
> 
> Regards

And what module would it be ???
I'm a zero on Perl.
Ok ?

I can paste here the spec I built the package.
I already installed some dependencies.
But, which one is missing ?

Best regards,
