### ISSUE TITLE
Unix Agent 2.4.2 : Software Inventory Installation Date returns 0000-00-00 00:00:00 on web interface

### ISSUE THREAD

**Issue by YumeRAiN7324** [OCSInventory-NG/UnixAgent#187]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Debian GNU/Linux 9 (stretch), Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07) x86_64 GNU/Linux
Perl version : 5.24.1-3+deb9u4

### OCS Inventory informations
Unix agent version : 2.4.2

### Problem's description : 
Softwares installation date on web interface returns 0000-00-00 00:00:00. Local inventory through `ocsinventory-agent -l <folder>` command returns installation date written in the following format (see attachments 'Desktop-Ansible-2018-11-06-09-55-37.txt' for further informations) : 

YYYY/MMDD HH:MM:SS

When manually modified to : YYYY/MM/DD HH:MM:SS and imported to the database server, dates are correctly printed out on the web interface (see screenshot 'Desktop-Ansible-WebInterface.png' attachment and <SOFTWARES> sections of gcc-6 and gedit in 'Desktop-Ansible-2018-11-06-09-55-37.txt' attachment) 

Inventory log file also in attachment.

The bug is apparently well known and has been fixed since agent version 2.4.1 though. Any feedback will be very appreciated. 

Thanks a lot.
![desktop-ansible-webinterface](https://user-images.githubusercontent.com/19530538/48164121-e4dce180-e2e1-11e8-8d70-9fd9095c86d4.png)

[Desktop-Ansible-2018-11-06-09-55-37.txt](https://github.com/OCSInventory-NG/UnixAgent/files/2559391/Desktop-Ansible-2018-11-06-09-55-37.txt)
[ocsinventory-agent.log](https://github.com/OCSInventory-NG/UnixAgent/files/2559393/ocsinventory-agent.log)

**Comment by YumeRAiN7324** [comment]
Tested on unified agent 2.4.1 and observed the same symptoms (bad date format, causing mysql to fill the fields with 0s)

**Comment by fbomj** [comment]
Hi,
Fix with https://github.com/OCSInventory-NG/UnixAgent/pull/191
Regards
Frank

**Comment by YumeRAiN7324** [comment]
> Hi,
> Fix with #191
> Regards
> Frank

Thank you very much for the reply. Works fine nowq
