### ISSUE TITLE
MacOS :List more network interfaces 

### ISSUE THREAD

**Issue by solune** [OCSInventory-NG/UnixAgent#19]
Hi,
With the use of thunderbolt display or ethernet adapter, we really need to inventory network interface from en0 to en5.
Thanks.

In file : lib/Ocsinventory/Agent/Backend/OS/MacOS/Networks.pm

--         next unless(/^en(0|3)/); # darwin has a lot of interfaces, for this purpose we only want to deal with eth0 and eth1
++        next unless(/^en(0|5)/); # darwin has a lot of interfaces, but with thunderbolt we need en0 to en5

**Comment by StCyr** [comment]
+1

I thought it was fixed?

It's our most awaited feature for 2.2.

The problem is that those un-inventoried interfaces show up in the ipdiscover subnet sections of OCSReports, therefore making us believing OCS inventory is not correctly installed on the corresponding computer .

**Comment by solune** [comment]
Bonjour,
Quand pensez vous sortir une release qui intégrera cette modification ?
Cordialement

**Comment by gillesdubois** [comment]
Bonjour,

@solune : l'agent unix est en phase  de RC, dès qu'il sera valide pour mise en production une release sera lancer avec ces modifications.
Malheureusement, je ne peux pas donner de dates.

Cordialement, Gilles Dubois.

**Comment by fbomj** [comment]
Hi,
This is integrated. 

Regards
Frank

**Comment by solune** [comment]
Bonjour,
Est il possible d'avoir un pkg macos pour tester ?

**Comment by gillesdubois** [comment]
Bonjour,

L'agent sera compilé pour macosx a sa release.
Néanmoins, vous pouvez créer le pkg vous même en suivant cette doc : http://wiki.ocsinventory-ng.org/index.php/Developers:HOWTO_package_macosx_agent_release

Regards,
Gilles Dubois.
