### ISSUE TITLE
How to authorize agent

### ISSUE THREAD

**Issue by vsimhv** [OCSInventory-NG/UnixAgent#192]
Hi, I can't seem to find information about how to enable authentication and authorization of data being uploaded to /ocsinventory.
The trouble is that any machine can publish information about any other machine and I have not way of knowing if the data is correct or malicious.
One way, from my perspective, would be agent cetrificates and mutual ssl, making the server accept data about machine A only from machine A.
Is that possible? Or is there any other, better way? I checked the documentation/wiki and did not see anything there.

**Comment by fbomj** [comment]
this is possible with apache authentication and ssl certificate. Set ssl=1 in /etc/ocsinventory-agent.cfg file, then install the certificate in /var/lib/ocsinventory-agent/https:__<your_server>_ocsinventory directory, set user=<apache_user> and password=<password> in /etc/ocsinventory-agent.cfg file. Set file permission to 600 on ocsinventory-agent.cfg file.
