### ISSUE TITLE
Secondary ip on RedHat

### ISSUE THREAD

**Issue by dcec** [OCSInventory-NG/UnixAgent#194]
### General informations
Operating system :  RedHat 6.6
Perl version :

### OCS Inventory informations
Unix agent version :  2.4.2

### Problem's description
All secondary ip are missing,
example if i have a config with multiple ip only one is collected:

# cat ifcfg-eth5
DEVICE=eth5
HWADDR=E8:39:35:0E:DB:83
TYPE=Ethernet
UUID=15a7d815-3f21-4477-8bd4-76505bcc079f
ONBOOT=yes
NM_CONTROLLED=no
BOOTPROTO=static
IPADDR=172.16.1.1
NETMASK=255.255.255.0
IPADDR0=172.16.1.2
PREFIX0=24
IPADDR1=172.16.1.3
PREFIX1=24
IPADDR2=172.16.1.4
PREFIX2=24
ARPCHECK2=no

**Comment by fbomj** [comment]
Hi,

Post ip a result command, please.

**Comment by dcec** [comment]
I put a real case with all output:
[2.4.2.log](https://github.com/OCSInventory-NG/UnixAgent/files/2786383/2.4.2.log)
[output_command.txt](https://github.com/OCSInventory-NG/UnixAgent/files/2786384/output_command.txt)

Need some other output?

**Comment by dcec** [comment]
[otbcrap01-2014-08-19-10-43-40.ocs.txt](https://github.com/OCSInventory-NG/UnixAgent/files/2786660/otbcrap01-2014-08-19-10-43-40.ocs.txt)

**Comment by dcec** [comment]
I'm making a mistake on OS config or there's a bug?

**Comment by fbomj** [comment]
Fixed by #196

**Comment by dcec** [comment]
Hi,
i find a duplicated ip on your pull,
i fix with:

@@ -347,10 +347,12 @@
                     }
                 }
                 $description = $driver = $ipaddress = $ipgateway = $ipmask = $ipsubnet = $ipaddress6 = $ipgateway6 = $ipmask6 = $ipsubnet6 = $macaddr = $pcislot = $status = $type = $virtualdev = $speed = $duplex = $mtu = undef;
+                @secondary=();
             }
             $description = $1 if ($line =~ /^\d+:\s+([^:@]+)/); # Interface name
             if ($description && $description eq "lo" ) { next; } # loopback interface is not inventoried
-            if ($line =~ /inet ((?:\d{1,3}+\.){3}\d{1,3})\/(\d+)/i ){
+            if ($line =~ /inet ((?:\d{1,3}+\.){3}\d{1,3})\/(\d+)/i && $line !~ /secondary/i ){
                 $ipaddress=$1;
                 $ipmask=getIPNetmask($2);
                 $ipsubnet=getSubnetAddressIPv4($ipaddress,$ipmask);
