### ISSUE TITLE
Issues with macos Mojave

### ISSUE THREAD

**Issue by devilsoulblack** [OCSInventory-NG/UnixAgent#195]
### General informations
Operating system :   Mojave ( 10.14.3 )
Perl version : This is perl 5, version 18, subversion 2 (v5.18.2)

### OCS Inventory informations
Unix agent version :  Ocsinventory_Agent_MacOSX-2.4.2.pkg

### Problem's description
Hi we use ocs very long time ago but now i see i have issues with macos mojave 

this log show:

ega-aandaluz:~ aandaluz$ tail -F /var/log/ocsng.log
[Mon Feb 11 15:55:51 2019][debug] No modules will be used.
[Mon Feb 11 15:55:51 2019][debug] Compress::Zlib is not available! The data will be compressed with
             gzip instead but won't be accepted by server prior 1.02
[Mon Feb 11 15:55:51 2019][debug] sending XML
[Mon Feb 11 15:55:51 2019][debug] sending: <?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>mega-aandaluz-2019-02-11-15-55-41</DEVICEID>
  <QUERY>PROLOG</QUERY>
</REQUEST>
[Mon Feb 11 15:55:51 2019][error] Cannot establish communication : 400 Bad Request

### Inventory log file ( optional )
use from local server 172.17.200.202

**Comment by fbomj** [comment]
Hi 
first install the missing perl module, second what's the version of ocs server?

Regards

**Comment by devilsoulblack** [comment]
@fbomj thanks for answer

I have install zlib but i get the same msg:

[Tue Feb 12 09:23:45 2019][debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.4.2
[Tue Feb 12 09:23:45 2019][debug] Log system initialised (File)
[Tue Feb 12 09:23:45 2019][debug] --scan-homedirs missing. Don't scan user directories
[Tue Feb 12 09:23:45 2019][debug] Accountinfo file: /var/lib/ocsinventory-agent/http:__172.17.200.202_ocsinventory/ocsinv.adm
[Tue Feb 12 09:23:45 2019][debug] OCS Agent initialised
[Tue Feb 12 09:23:45 2019][debug] Failed to load `/etc/ocsinventory-agent/modules.conf': 0
[Tue Feb 12 09:23:45 2019][debug] No modules will be used.
[Tue Feb 12 09:23:45 2019][debug] Compress::Zlib is not available! The data will be compressed with
             gzip instead but won't be accepted by server prior 1.02
[Tue Feb 12 09:23:45 2019][debug] sending XML
[Tue Feb 12 09:23:45 2019][debug] sending: <?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>mega-aandaluz-2019-02-11-15-55-41</DEVICEID>
  <QUERY>PROLOG</QUERY>
</REQUEST>
[Tue Feb 12 09:23:45 2019][error] Cannot establish communication : 400 Bad Request


The ocs server is: 2.2.1 over debian 8.10

Regards

**Comment by fbomj** [comment]
OCS Server 2.2.1 is too old. You can't use agent 2.4.2 with this version of ocs server.  You have to update ocs server or to use a older version, in your case unix agent 2.2.1 version.
The rule is : 

ocs agent version <= ocs server version

Regards

**Comment by devilsoulblack** [comment]
@fbomj thanks, is working now 👍
