### ISSUE TITLE
AIX Hardware

### ISSUE THREAD

**Issue by lopova21** [OCSInventory-NG/UnixAgent#197]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : AIX 6.1
Perl version : 5.8.8

### OCS Inventory informations
Unix agent version : 2.4.2

### Problem's description
Some informations are not available on the OCS Inventory like Firmware Version, I think it's a wrong order entry in your module (Hardware.pm)
This commande don't work (lscfg -vpl sysplanr00).
I havent 
Please test your commands before publish your version.
I did not check everything but I hope there are no other issues.

**Comment by fbomj** [comment]
Fixed on master
