### ISSUE TITLE
The agent can't see the second monitor

### ISSUE THREAD

**Issue by reanimator2004** [OCSInventory-NG/UnixAgent#198]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  server Centos7; client Ubuntu 16.04
Perl version : client v5.22.1 ; server v5.16.3

### OCS Inventory informations
Unix agent version : 2.0.5 and 2.4.2

### Problem's description
Good day! The agent can't see the second monitor. tried on versions of the agent 2.0.5 and 2.4.2 (Linux) And on 2.4.0 Windows.
Help solve the problem

### Inventory log file ( optional )
https://owncloud.grancall.ru/index.php/s/K5D8spETcmeQZTy
log file attach

**Comment by reanimator2004** [comment]
The project is alive? Does anyone support him? Should we wait for a decision?

**Comment by fbomj** [comment]
open an issue on https://github.com/OCSInventory-NG/WindowsAgent/issues/new for windows agent.
Could you post ocsinventory-agent.log file content (ocsinventory unix agent), please?

**Comment by reanimator2004** [comment]
I use Linux, why do I need to open a query in the windows branch? Why was the request closed?

**Comment by reanimator2004** [comment]
cat ocsinventory-agent.log
[Wed May 29 16:14:47 2019][info] [download] Download is off.
[Wed May 29 16:14:49 2019][info] [download] Beginning work. I am 21205.
[Wed May 29 16:14:49 2019][info] [download] Option turned off. Exiting.

**Comment by fbomj** [comment]
for windows see what you have written => "Good day! The agent can't see the second monitor. tried on versions of the agent 2.0.5 and 2.4.2 (Linux) **And on 2.4.0 Windows**."

**Comment by reanimator2004** [comment]
https://owncloud.grancall.ru/index.php/s/K5D8spETcmeQZTy
lof file attach

**Comment by fbomj** [comment]
I saw in your log file that perl module Parse::EDID is not installed (see below). Install it and relaunch an inventory. 
Tested on my config all is good. 

[Thu May 30 12:01:17 2019][debug] Failed to load Ocsinventory::Agent::Backend::OS::MacOS::Video: Can't locate Parse/EDID.pm in @INC (you may need to install the Parse::EDID module) (@INC contains: /usr/lib/perl5/5.28/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.28/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.28/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/site_perl/Ocsinventory/Agent/Backend/OS/MacOS/Video.pm line 4.
BEGIN failed--compilation aborted at /usr/share/perl5/site_perl/Ocsinventory/Agent/Backend/OS/MacOS/Video.pm line 4.
Compilation failed in require at (eval 118) line 1.
BEGIN failed--compilation aborted at (eval 118) line 1.
[Thu May 30 12:01:17 2019][debug] Failed to load Ocsinventory::Agent::Backend::OS::Generic::Screen: Can't locate Parse/EDID.pm in @INC (you may need to install the Parse::EDID module) (@INC contains: /usr/lib/perl5/5.28/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.28/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.28/core_perl /usr/share/perl5/core_perl) at /usr/share/perl5/site_perl/Ocsinventory/Agent/Backend/OS/Generic/Screen.pm line 5.
BEGIN failed--compilation aborted at /usr/share/perl5/site_perl/Ocsinventory/Agent/Backend/OS/Generic/Screen.pm line 5.
Compilation failed in require at (eval 206) line 1.

**Comment by reanimator2004** [comment]
All OK,
Thanks! Problem resolv
