### ISSUE TITLE
resources/ipdiscover/ipdiscover.c:100: poor error checking ?

### ISSUE THREAD

**Issue by dcb314** [OCSInventory-NG/UnixAgent#2]
[resources/ipdiscover/ipdiscover.c:100]: (style) A pointer can not be negative so it is either pointless or an error to check if it is.

Source code is

    *sd = socket( PF_PACKET, SOCK_RAW, htons( ETH_P_ARP ) );
    // ...
    if( sd < 0 ){
        perror("Socket creation problem");
        exit(1);
    }

Suggest new code

    *sd = socket( PF_PACKET, SOCK_RAW, htons( ETH_P_ARP ) );
    // ...
    if (*sd < 0 ){
        perror("Socket creation problem");
        exit(1);
    }

**Comment by fbomj** [comment]
Thanks for reporting.
Regards
