### ISSUE TITLE
Is this repo's source code is same for OCS Inventory NG agent for MacOS X ?

### ISSUE THREAD

**Issue by djbdjb00djb** [OCSInventory-NG/UnixAgent#20]
Is this repo's source code is same for OCS Inventory NG agent for MacOS X ?

and how to build a  pkg installer for MacOS X?

**Comment by gillesdubois** [comment]
Hi,

The unix unified agent is used for UNIX and OSX system.
However there is a OSX packager available which provide a friendly graphics interface for mac users.
Here is the link : https://github.com/OCSInventory-NG/Macosx-Packager
You can download it here : https://github.com/OCSInventory-NG/Macosx-Packager/releases/tag/0.8

If you want to build a .pkg  from the unix agent here is the documentation : http://wiki.ocsinventory-ng.org/index.php/Developers:Unified_OSX

Regards,
Gilles Dubois.
