### ISSUE TITLE
The agent can't see the second monitor#198

### ISSUE THREAD

**Issue by reanimator2004** [OCSInventory-NG/UnixAgent#208]
It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.

General informations
Operating system : server Centos7; client Ubuntu 16.04
Perl version : client v5.22.1 ; server v5.16.3

OCS Inventory informations
Unix agent version : 2.0.5 and 2.4.2

Problem's description
Good day! The agent can't see the second monitor. tried on versions of the agent 2.0.5 and 2.4.2 (Linux) 
Help solve the problem

Inventory log file ( optional )
cat ocsinventory-agent.log
[Wed May 29 16:14:47 2019][info] [download] Download is off.
[Wed May 29 16:14:49 2019][info] [download] Beginning work. I am 21205.
[Wed May 29 16:14:49 2019][info] [download] Option turned off. Exiting.

**Comment by fbomj** [comment]
the log must be longer

**Comment by fbomj** [comment]
i close this because I reopen the other
