### ISSUE TITLE
Why  depend Crypt::SSLeay perl module 

### ISSUE THREAD

**Issue by djbdjb00djb** [OCSInventory-NG/UnixAgent#21]
Why  depend Crypt::SSLeay perl module, this module is not default installed in  Mac OS X 10.10 and above. Manual install it so hard to normal user.

**Comment by gillesdubois** [comment]
Hi,

As you can see the unified unix agent is not used only for mac osx platform. Even if that harder to install on Mac OSX we can't just change this dependency at the moment.
I got some trouble too with my Mac OSX devices installing this librairie.

=

However if you get some trouble installing the Crypt:SSLeay here is a little 2 commands trick that can help you (sudo needed) :

Requirements : 
- gcc
- make 
- cpan
- openssl

And then launch this command : 
`sudo OPENSSL_INCLUDE=/usr/local/opt/openssl/incude OPENSSL_LIB=/usr/local/opt/openssl/lib PERL_MM_USE_DEFAULT=1 perl -MCPAN -e "install Crypt::SSLeay"`

NB  : You may need to change these path depending in your install.

Regards,
Gilles Dubois.

**Comment by djbdjb00djb** [comment]
Thanks, but is there have a way to build Crypt::SSLeay  perl module  in  the pkg installer for Mac OS ？

**Comment by MyTheValentinus** [comment]
Hello @djbdjb00djb ,
Sorry but to my knowledge you need to use this method https://github.com/OCSInventory-NG/UnixAgent/issues/21#issuecomment-197786804
Thank
