### ISSUE TITLE
Use of uninitialized value $password in concatenation (.) or string at /usr/share/perl5/vendor_perl/Ocsinventory/Agent/Network.pm line 52.

### ISSUE THREAD

**Issue by nerijus** [OCSInventory-NG/UnixAgent#211]
Version 2.6.0, when running ocsinventory-agent --nolocal --server=example.com, I get:
```
Use of uninitialized value $password in concatenation (.) or string at /usr/share/perl5/vendor_perl/Ocsinventory/Agent/Network.pm line 52.
```

**Comment by nerijus** [comment]
CentOS 7.x

**Comment by mariaczi** [comment]
Duplicate https://github.com/OCSInventory-NG/UnixAgent/issues/205

**Comment by nerijus** [comment]
Yes, but #205 is closed. If the problem is not resolved, issue should not be closed, otherwise you will get more reports like this.

**Comment by mariaczi** [comment]
I have added more details in #205. If you can, please look on that or reopen #205.

**Comment by mariaczi** [comment]
Small info, how to fix I had described here: https://github.com/OCSInventory-NG/UnixAgent/issues/205#issuecomment-508681080

**Comment by o71** [comment]
Same problem with Debian 10 Buster.

**Comment by o71** [comment]
I solved the problem like this :   

` ...
    $self->{ua}->agent($version);
    my $password = $self->{config}->{password};
    $self->{ua}->credentials(
       ...`

Diff with orignal file :  
`# diff -u Network.pm.origine Network.pm
--- Network.pm.origine  2019-07-12 23:14:12.351943537 +0200
+++ Network.pm  2019-07-12 23:20:05.164533783 +0200
@@ -49,8 +49,7 @@
     my $version = 'OCS-NG_unified_unix_agent_v';
     $version .= exists ($self->{config}->{VERSION})?$self->{config}->{VERSION}:'';
     $self->{ua}->agent($version);
-    $self->{config}->{user}.",".
-    my $password = $self->{config}->{password}."";
+    my $password = $self->{config}->{password};
     $self->{ua}->credentials(
         $uaserver, # server:port, port is needed
         $self->{config}->{realm},
`
I hope it can help

**Comment by nerijus** [comment]
Diff is incorrect. Correct diff:
```
--- Network.pm.orig     2019-05-20 12:37:00.000000000 +0300
+++ Network.pm  2019-07-14 16:27:29.123718023 +0300
@@ -49,13 +49,11 @@
     my $version = 'OCS-NG_unified_unix_agent_v';
     $version .= exists ($self->{config}->{VERSION})?$self->{config}->{VERSION}:'';
     $self->{ua}->agent($version);
-    $self->{config}->{user}.",".
-    my $password = $self->{config}->{password}."";
     $self->{ua}->credentials(
         $uaserver, # server:port, port is needed
         $self->{config}->{realm},
         $self->{config}->{user},
-        $password,
+        $self->{config}->{password},
     );

     #Setting SSL configuration depending on LWP version
```
With this diff I no longer get `Useless use of concatenation (.) or string in void context at /usr/share/perl5/vendor_perl/Ocsinventory/Agent/Network.pm line 53.`
