### ISSUE TITLE
The installation failed

### ISSUE THREAD

**Issue by dtxl** [OCSInventory-NG/UnixAgent#212]
### General informations
Operating system :  Mojave ( 10.14.5 )
Perl version : perl 5, version 18, subversion 4 (v5.18.4)

### OCS Inventory informations
Unix agent version :  Ocsinventory_Agent_MacOSX-2.4.2.pkg

### Problem's description
The installation of this package ends with the summary "The installation failed". The installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

**Comment by fbomj** [comment]
Hi,

Sorry for delay. Try with new version => https://github.com/OCSInventory-NG/UnixAgent/releases/download/v2.6.0-MAC/Ocsinventory_Agent_MacOS-2.6.0.mpkg.zip
