### ISSUE TITLE
[Feature] possibility a switch manually ON/OFF lsbrelease usage

### ISSUE THREAD

**Issue by gillesdubois** [OCSInventory-NG/UnixAgent#216]
Hi,

I would like to have the possibility to switch the LSBRelease usage at will.
Let's say you have 150 redhat server inventoried, some of them have lsbrelease installed and some not.  

You will have some differences in the OS name because all the servers are not using the same tool / utility to get their informations. It can be frustrating when doing search or deployments.

I think a specific config to disable the usage of LSB even if installed would be a nice idea.

Regards,
Gilles Dubois.

**Comment by fbomj** [comment]
Hi
Use /etc/os-release file content to retrieve OS informations (name, version, service pack). All majors distributions use it.
