### ISSUE TITLE
2.6.0 Unix agent on Fedora 30 not populating the BIOS section anymore

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/UnixAgent#219]
### General informations
Operating system :  Fedora 30 - Selinux enabled
Perl version : perl5 (revision 5 version 28 subversion 2

### OCS Inventory informations
Unix agent version : 2.6.0

### Problem's description
I no longer see the Fedora 30 BIOS details. I do see if for Centos 7.6 though. Both agents are 2.6.0.

![image](https://user-images.githubusercontent.com/13314239/62189329-f6ce4b00-b36e-11e9-8109-bdf082b6e17f.png)

[fedora_30.csv.zip](https://github.com/OCSInventory-NG/UnixAgent/files/3450192/fedora_30.csv.zip)

![image](https://user-images.githubusercontent.com/13314239/62189301-e8802f00-b36e-11e9-8064-0f64cf8dff86.png)

[Centos_7_6.csv.zip](https://github.com/OCSInventory-NG/UnixAgent/files/3450194/Centos_7_6.csv.zip)

**Comment by fbomj** [comment]
Hi,
dmidecode command has not been removed?

**Comment by daniejstriata** [comment]
Thanks for your guidance. I found my issue. Was related to ModSecurity.

I was getting 
`[error] Cannot establish communication : 413 Request Entity Too Large`
so previously the BIOS record could've been broken but now I see my BIOS details.
