### ISSUE TITLE
kernel version reported in OSVERSION

### ISSUE THREAD

**Issue by pandrieux** [OCSInventory-NG/UnixAgent#227]
### General informations
Operating system :  CentOS Linux release 7.7.1908 (Core)
Perl version : (v5.16.3)

### OCS Inventory informations
Unix agent version : 2.4.0

### Problem's description
The kernel version is reported in <OSVERSION>.
This is happening on various CentOS 7.x
On some machines, the reported value is correct on some other the kernel version is reported. I can't figure it out why.
perl packages are the same.
kernel is the same.
ocs agent is the same

### Inventory log file ( optional )
OSVERSION report a correct value
```
    <HARDWARE>

      <DATELASTLOGGEDUSER>Mon Sep 30 14:45</DATELASTLOGGEDUSER>

      <NAME>proxy01</NAME>
      <OSCOMMENTS>#1 SMP Fri Sep 13 22:55:44 UTC 2019</OSCOMMENTS>
      <OSNAME>CentOS 7.7.1908</OSNAME>
      <OSVERSION>7.7.1908</OSVERSION>

    </HARDWARE>
```

OSVERSION report kernel version : 
```
    <HARDWARE>

      <DATELASTLOGGEDUSER>Mon Sep 30 15:37</DATELASTLOGGEDUSER>

      <NAME>gitlab</NAME>
      <OSCOMMENTS>#1 SMP Fri Sep 13 22:55:44 UTC 2019</OSCOMMENTS>
      <OSNAME>CentOS Linux release 7.7.1908 (Core)</OSNAME>
      <OSVERSION>3.10.0-1062.1.1.el7.x86_64</OSVERSION>

    </HARDWARE>
```

**Comment by fbomj** [comment]
Hi,
Could you post both ocsinventory-agent.log file content, plz?
Regards

**Comment by pandrieux** [comment]
Hi, 
please find attached both reports (gitlab and proxy01 hosts)
best regards, 

[proxy01-2019-09-27-04-02-07.ocs.txt](https://github.com/OCSInventory-NG/UnixAgent/files/3675719/proxy01-2019-09-27-04-02-07.ocs.txt)
[gitlab-2019-02-09-03-16-07.ocs.txt](https://github.com/OCSInventory-NG/UnixAgent/files/3675720/gitlab-2019-02-09-03-16-07.ocs.txt)

**Comment by fbomj** [comment]
Hi
I've asked for ocsinventory-agent.log file which is stored in /var/log/.
Regards

**Comment by pandrieux** [comment]
Hi, 
I'am sorry for that, my bad.

The log file say actually my agent is : 
```
[Wed Oct  2 12:09:28 2019][debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.3.1
```

I notice a diff between log file, especially this line on my incorrect server 
```
[Wed Oct  2 12:05:58 2019][debug] Ocsinventory::Agent::Backend::OS::Linux::Distro::LSB ignored
```

My correct server say
```
[Wed Oct  2 12:09:28 2019][debug]  - lsb_release found
```

Could you help me find out why this module is ignored ?

Regards

**Comment by pandrieux** [comment]
Hi guys, 
I found it ! thank you @fbomj for pointing me out to post the debug file (which is obvious saying it...).

Anyway, I simply installed the package "redhat-lsb-core" on my CentOS. 
And now I have the correct OS version.
