### ISSUE TITLE
[new feature] exclude network interfaces based on regex in description

### ISSUE THREAD

**Issue by mariaczi** [OCSInventory-NG/UnixAgent#228]
### General informations
Operating system :  all
Perl version :

### OCS Inventory informations
Unix agent version : all

### Problem's description
Be able to setup the regexp for network interfaces which should be not inventoried.
Why?
When we use docker on server each virtual interface from new container is inventoried, so when we create new one container for the same functionality and delete the old one we have a new one network interface on the network interfaces list for the bare-metal server.

**Comment by fbomj** [comment]
Hi,
Could you explain with details?
Regards

**Comment by mariaczi** [comment]
Hi.
On clean install linux OS we starting docker daemon. It creates the docker0 interface and it it OK.
When we start docker container new "veth*" interface is created for them. The interface is not deleted when we stop the container.
When we have a lot of docker containers running on a server we will have a lot of veth* interfaces inventoried, but it will be good option to have a possibility to exclude this interfaces - starting with veth name from inventory.
Regards.
