### ISSUE TITLE
virtual machines hosted on a ovirt-engine (libvirt) are not listed

### ISSUE THREAD

**Issue by pandrieux** [OCSInventory-NG/UnixAgent#229]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  centos
Perl version : v5.16.3

### OCS Inventory informations
Unix agent version : 2.3.1

### Problem's description
virtual machines hosted on a ovirt-engine (libvirt) are not listed in Miscellaneous.

Please find hereunder the code to be updated in perl module Libvirt.pm
+ add option --readonly in both virsh list and dumpxml
+ note that the 'if... ' statement is already on your master branch
+ fixbug : machine is a hash not a variable
+ fixbug : Pass hash by reference, using the backslash operator

```
$ diff /usr/share/perl5/vendor_perl/Ocsinventory/Agent/Backend/Virtualization/Libvirt.pm_OLD /usr/share/perl5/vendor_perl/Ocsinventory/Agent/Backend/Virtualization/Libvirt.pm
17,18c17,18
<     foreach (`virsh list --all`) {
<         if (/^(\d+|\s+\-)\s+(\S+)\s+(\S.+)/){
---
>     foreach (`virsh --readonly list --all`) {
>       if (/^\s*(\d+|\s+\-)\s+(\S+)\s+(\S.+)/){
25c25
<             my $xml = `virsh dumpxml $name`;
---
>             my $xml = `virsh --readonly dumpxml $name`;
40c40
<             my $machine = {
---
>             my %machine = (
48c48
<             };
---
>             );
50c50
<             $common->addVirtualMachine($machine);
---
>             $common->addVirtualMachine(\%machine);
```

my branch is ready to push, but i can't (permission)

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
Hi,
Create a pr for that.
Regards

**Comment by pandrieux** [comment]
https://github.com/OCSInventory-NG/UnixAgent/pull/230
