### ISSUE TITLE
List secondary IPs on Linux

### ISSUE THREAD

**Issue by nagyd-ema** [OCSInventory-NG/UnixAgent#23]
Hi,

Linux agent doesn't discover secondary ip addresses, added using 'ip addr add ...' command, for example
ip a a 100.100.100.100 dev lo
ip -o a s dev lo
1: lo    inet 127.0.0.1/8 scope host lo\       valid_lft forever preferred_lft forever
1: lo    inet 100.100.100.100/32 scope global lo\       valid_lft forever preferred_lft forever
1: lo    inet6 ::1/128 scope host \       valid_lft forever preferred_lft forever

I'd be nice if the agent would collect and display all secondary IPs on all interfaces.

Keep up the good work!

Daniel

**Comment by fbomj** [comment]
Hi,
Tested with the latest version of the agent on my laptop : 
 <NETWORKS>
      <DESCRIPTION>lo</DESCRIPTION>
      <DUPLEX>Half</DUPLEX>
      <IPADDRESS>100.100.100.100</IPADDRESS>
      <IPMASK>255.255.255.255</IPMASK>
      <IPSUBNET>100.100.100.100</IPSUBNET>
      <MACADDR>00:00:00:00:00:00</MACADDR>
      <MTU>65536</MTU>
      <STATUS>UP</STATUS>
      <TYPE>Loopback</TYPE>
      <VIRTUALDEV>1</VIRTUALDEV>
    </NETWORKS>
Agent retrieves the address.
Regards
Frank
