### ISSUE TITLE
bad version number

### ISSUE THREAD

**Issue by cirvent** [OCSInventory-NG/UnixAgent#231]
Hi,

wrong version number after build 2.4.3 instead of 2.6.0

### General informations
Operating system :  any
Perl version : any

### OCS Inventory informations
Unix agent version : 2.6.0

### Problem's description
you forgot to change the version number from 2.4.3 to 2.6.0 in the source code

**Comment by fbomj** [comment]
Hi

Version number is correct in the source. I've verified. Master branch is correct and tarball also. How did you obtain your files?
Regards
