### ISSUE TITLE
IP is not updated after change

### ISSUE THREAD

**Issue by mariaczi** [OCSInventory-NG/UnixAgent#235]
### General informations
Operating system :  Linux
Perl version : 5.22

### OCS Inventory informations
Unix agent version : 2.6

### Problem's description
After change IP address on server the IP is not updated on OCS server. The new IP we have only on "Administrative data" but not in "Network" (screen-shots bellow).

![Selection_106](https://user-images.githubusercontent.com/25037132/68470882-426d7c00-021d-11ea-875f-cd7175f39fdb.png)
![Selection_107](https://user-images.githubusercontent.com/25037132/68470896-48fbf380-021d-11ea-95c3-9e1a57103d69.png)

If this bug should be reported in other OCS component, please let me known.

**Comment by fbomj** [comment]
Hi,
Could you post the content of the xml file after running ocsinventory-agent --local /tmp /debug command?
Regards
Frank

**Comment by mariaczi** [comment]
Log file, which you requested.
[darkstar-2019-10-31-13-40-02.ocs.txt](https://github.com/OCSInventory-NG/UnixAgent/files/3886518/darkstar-2019-10-31-13-40-02.ocs.txt)

**Comment by fbomj** [comment]
after refreshing the page is there a change? As I can see in the .ocs file network address is correct. I think this is a cache problem. Remove cache from your browser and re-test. 

Regards
Frank

**Comment by mariaczi** [comment]
No, it is not a problem with cache in web browser. I tried full refresh in web browser (Ctrl+Shift+R on FF), I tried open web browser window in private mode and on two other web browser. On each this issue was visible. I think that this problem can be connected with DEVICEID issue described by me here [#234].
