### ISSUE TITLE
can't find ocsinventory-agent in $PATH - postinstall bug in CentOS 8

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/UnixAgent#242]
### General informations
Operating system :  CentOS 8.0.1905
Perl version : v5.26.3

### OCS Inventory informations
Unix agent version : 2.4.2

### Problem's description
I compiled the ocs unix agent successfully under CentOS but make install fails at the end of the post-install script with this error message:

```
Setting OCS Inventory NG server address...
Looking for OCS Invetory NG Unix Unified agent installation...
sorry, can't find ocsinventory-agent in $PATH
make: *** [Makefile:1338: install] Error 1
```

Because it's a new install, I chose:

```
Should I remove the old unix_agent
Please enter 'y' or 'n'?> [n]
```

Anyway, I executed ./ocsinventory-agent -s ocs.mydomain and it sent the inventory, but the post-install configuration is not done.

**Comment by fbomj** [comment]
Hi
Does it appear with the latest version ?
Regards
Frank

**Comment by pchamo** [comment]
Yes, you are right. Agent version 2.4.2 and centos 8 1905.

**Comment by fbomj** [comment]
I've tested the installation on a centos 8 with the same version as yours and I haven't had the problem. 2.4.2 is not the last. 2.6.0 is. Have you installed all modules needed?

**Comment by pchamo** [comment]
It seems 2.6.0 is not affected. Thanks.

**Comment by fbomj** [comment]
I don't have these messages after installation of ocs 2.6.0 on CentOS 8.

Regards

**Comment by goandy84** [comment]
Hi, is all day i try to install ocs on redhat 8, when i run perl Make.PL i get this output

Please install Crypt::SSLeay if you want to use SSL.
Net::IP is strongly recommended since it's required to retrieve network information
Net::Netmask is strongly recommended since it's required to retrieve snmp information
Please install Proc::Daemon and Proc::PID::File if you want to use the daemon mode.
Nvidia::ml is recommended if you want to retrieve memory, speed, bios information for Nvidia cards.
Warning: prerequisite Data::UUID 0 not found.
Warning: prerequisite Net::IP 0 not found.
Generating a Unix-style Makefile
Writing Makefile for Ocsinventory::Unix::Agent
Writing MYMETA.yml and MYMETA.json

if i go next, the installation proceed but at the end it exit with failure
sorry, can't find ocsinventory-agent in $PATH
make: *** [Makefile:1778: install] Error 1

please can you let me know how did you do?

**Comment by fbomj** [comment]
Hi,
Which version of agent are you trying to install ?
Regards

**Comment by goandy84** [comment]
Hi, 2.6 and perl 5, version 26, subversion 3 (v5.26.3) built for x86_64-linux-thread-multi

**Comment by goandy84** [comment]
is available a document that descrive how to install OCS 2.6 on Redhat 8?

**Comment by kapouik** [comment]
https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-UNIX-agent-on-client-computers/#installing-unix-agent-with-rpm

**Comment by goandy84** [comment]
this wiki is not complete. It not show how install all prereq for centos 8 or RedHat 8. 

All wiki is full of not correct information.

wget installation:
when i run last command 
`sudo dnf --enablerepo=PowerTools --enablerepo=epel-playground install ocsinventory-agent
`
Error: Unknown repo: 'PowerTools'

when i run local installation many required module has needed
```
perl Makefile.PL
Please install Crypt::SSLeay if you want to use SSL.
Please install Proc::Daemon and Proc::PID::File if you want to use the daemon mode.
Nvidia::ml is recommended if you want to retrieve memory, speed, bios information for Nvidia cards.
Checking if your kit is complete...
Looks good
Warning: prerequisite Data::UUID 0 not found.
Generating a Unix-style Makefile
Writing Makefile for Ocsinventory::Unix::Agent
Writing MYMETA.yml and MYMETA.json
```

**Comment by kapouik** [comment]
The repository PowerTools come with the package centos-repos that is install by default on Centos 8. If you don't have this repo on your system, it's not normal.

The documentation explain how to install the agent by RPM. So for that : it is complete and show only correct information.

**Comment by goandy84** [comment]
Under section: On **Redhat**/Centos 8 you can install the unix agent with RPM 
I have Redhat 8

```
[root@ELT-ARTiFACTORY01 Ocsinventory-Unix-Agent-2.6.0]# sudo dnf --enablerepo=PowerTools --enablerepo=epel-playground install ocsinventory-agent
Updating Subscription Management repositories.
Error: Unknown repo: 'PowerTools'
```

**Comment by kapouik** [comment]
After some search, on RHEL, PowerTools don't exist. The repo is call codeready. You can activate it with this command : 
subscription-manager repos --enable codeready-builder-for-rhel-8-x86_64-rpms
Say me if it work and I will update the documentation for RHEL.
