### ISSUE TITLE
Agent 2.6 is broken after update from Epel repo

### ISSUE THREAD

**Issue by pchamo** [OCSInventory-NG/UnixAgent#243]
### General informations
Operating system :  CentOS Linux release 7.6.1810 & CentOS 7.7.1908
Perl version : v5.16.3

### OCS Inventory informations
Unix agent version : 2.6.0.3

### Problem's description
After update from ocsinventory-agent-2.6.0-2.1 to version ocsinventory-agent-2.6.0-3 from Epel repo the agent stopped working.

```
[root@host ~]# ocsinventory-agent
Failed to load Ocsinventory::Agent, Global symbol "$self" requires explicit package name at /usr/share/perl5/vendor_perl/Ocsinventory/Agent.pm line 166.
Compilation failed in require at (eval 1) line 1.
BEGIN failed--compilation aborted at (eval 1) line 1.

you can run the agent directly for its source directory with --devlib
```

**Comment by pchamo** [comment]
I have no credentials to file that bug in https://apps.fedoraproject.org/packages/ocsinventory-agent/bugs/all :(

**Comment by kapouik** [comment]
This agent don't come from me. I will do an update to correct this on the official repo.

**Comment by thomasmarteau** [comment]
Thanks for the fix. I'll test it as soon as it is available.

**Comment by pchamo** [comment]
Thank you :) I have a question for you, why the name of the operating system shown in some versions of the agent is just "CentOS" and not "centos release 7.8" (for example). What needs to be done in order to get the the full OS name? Thank you.

**Comment by kapouik** [comment]
I just release a new version of the agent on the repo. I add some patch from the current devel version.

**Comment by thomasmarteau** [comment]
Cool, thanks a lot. I'll test as soon as I can download it.
Enjoy tonight party!

**Comment by thomasmarteau** [comment]
Hi @kapouik I still see a package in epel repository from 18 december here for example https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/o/ Any place I can download the correct version?

**Comment by kapouik** [comment]
http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server-with-rpm/

The repo for the agent is the same than for the server. You just need epel repo as additionnal repository if you only want to install the agent : Remi repo is only needed for ocsreports.

**Comment by thomasmarteau** [comment]
I'm afraid the repo is not updated. Look at the screenshot. The binary 2.6 is there since 18 december
![repo](https://user-images.githubusercontent.com/13727189/71896251-89132000-3153-11ea-9ff9-ab1c38d2d443.JPG)
md5sum ocsinventory-agent-2.6.0-3.el7.x86_64.rpm perl-Ocsinventory-Agent-2.6.0-3.el7.noarch.rpm
2603fd9b91c1d8e92ae8b023ca14ec13  ocsinventory-agent-2.6.0-3.el7.x86_64.rpm
f6f3f80921d2e58063b2896365e10216  perl-Ocsinventory-Agent-2.6.0-3.el7.noarch.rpm
Those have still the bug.
Can you point to the new location that I missed?

**Comment by fbomj** [comment]
Hi
rpms can be downloaded from here => http://rpm.ocsinventory-ng.org/enterprise/

**Comment by thomasmarteau** [comment]
Thanks a lot.
With 2.6.0-5, it is working fine!
