### ISSUE TITLE
ssl certificate verify failed after upgrading debian packages from stretch to buster

### ISSUE THREAD

**Issue by dudleyperkins** [OCSInventory-NG/UnixAgent#245]
### General informations
Operating system : Debian 10.2
Perl version : debian package 5.28.1-6

### OCS Inventory informations
Unix agent version : debian package 2.4.2-3

### Problem's description

After upgrading some of our server from stretch to buster, and with this ocsinventory from 2.0.5-1.2 to 2.4.2-3, we noticed they don't report to the ocs-server anymore.

If you execute ocsinventory-agent in a shell it says:
`[error] Cannot establish communication : 500 SSL_ca_file /var/lib/ocsinventory-agent/https:__my.server_ocsinventory/cacert.pem can't be used: No such file or directory`

In "/etc/ocsinventory/ocsinventory-agent.cfg" we have set the server url with https-protocol:
`server=https://my.server/ocsinventory`

Okay new version may mean new requirements, so i tried to put the server-certificate in the desired path:
`openssl s_client -showcerts -connect my.server:443 </dev/null 2>/dev/null|openssl x509 -outform PEM > cacert.pem`

Well the error changed, but still no report to the server:
`[error] Cannot establish communication : 500 Can't connect to my.server:443 (certificate verify failed)`

My first option now is setting "ssl=0", from what i understand that only disables ssl-verification but connection is still made via ssl, right?

But in the end it would be good if i can turn it back to default with "ssl=1".

**Comment by kapouik** [comment]
ssl=0 mean that there is no validation of the certificat. So any Man in the middle attack can take the root of your server. 
Please use it only on test computer.
It look you have a problem on your certificat : 
- Check that CN of your certificat is exactly the same as the DNS you use to call your server.
- Check expiration date and local time on your client.

**Comment by dudleyperkins** [comment]
Yes i have checked that, it's all correct. Common Name is the fqdn of the ocs-server and time is synchronised an all server. A check with curl looks like this:

`curl -v --cacert /var/lib/ocsinventory-agent/https\:__my.server_ocsinventory/cacert.pem https://my.server:443
*   Trying 10.xx.xx.xx...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x55b3501e5f50)
* Connected to my.server (10.xx.xx.xx) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /var/lib/ocsinventory-agent/https:__my.server_ocsinventory/cacert.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=DE; ..***.. ; CN=my.server
*  start date: Jan 29 10:49:45 2019 GMT
*  expire date: Jan 29 10:49:45 2020 GMT
*  subjectAltName: host "my.server" matched cert's "my.server"
*  issuer: C=DE; ...***...
*  SSL certificate verify ok.
`

The thing i wonder is, why is it still working with the old server? The cacert-file was never needed on them, and is still not present.

Can i debug this somehow more detailed? Calling ocsinventory-agent with debug also only gives me that one [error]-line.

**Comment by fbomj** [comment]
Hi,
Edit the file ocsinventory-agent.cfg. Comment the line beginning with ca= or suppress it. Save. Launch an inventory.

Regards

**Comment by dudleyperkins** [comment]
I didn't have a "ca" line in the agent config. But while trying around i found the problem, somehow openssl only got the server certificate, but i needed the whole certificate chain including intermediate and root ca. Once i got all this into the pem-file it worked.

**Comment by nikinname** [comment]
I have the same problem but putting the whole chain in cacert.pem did not resolve the provlem.
I put cacert.pem in ocsinventory-agent/https\:__myFQDNservernameocsinventory_ (created by ocsinventory-agent)
but I still have the error

[debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.0
[debug] Log system initialised (Stderr)
[debug] --scan-homedirs missing. Don't scan user directories
[debug] Accountinfo file: /var/lib/ocsinventory-agent/https:__myFQDNservernameocsinventory_/ocsinv.adm
[debug] OCS Agent initialised
[debug] Turns hooks on for /etc/ocsinventory/modules.conf
[debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.0
[debug] Log system initialised (Stderr)
[debug] Calling handlers : 'start_handler'
[debug] [download] Calling download_start_handler
[debug]  - Net::SSLeay qw(die_now die_if_ssl_error) loaded
[debug] Compress::Zlib is available.
[debug] Calling handlers : `prolog_writer'
[debug] sending XML
[debug] sending: \<?xml version="1.0" encoding="UTF-8"?>
\<REQUEST>
  \<DEVICEID>xxxxxxxxxx\</DEVICEID>
  \<QUERY>PROLOG\</QUERY>
\</REQUEST>
**[error] Cannot establish communication : 500 Can't connect to ocsinventory.sit.local:443 (certificate verify failed)**
