### ISSUE TITLE
Linux: options to skip loop device

### ISSUE THREAD

**Issue by masutomo** [OCSInventory-NG/UnixAgent#248]
Operating system :  Ubuntu 18.04
Perl version :5.28.1

### OCS Inventory informations
Unix agent version : 2.4.2-3

### Problem's description
As more and more snap packages using loop devices, can we add an option to skip the loop device to be added to the inventory? As it is mostly meaningless to know about them in our environment.

Thanks.

**Comment by fbomj** [comment]
Hi,
version 2.6.0 skip the inventory of the loopback interface.
Regards
