### ISSUE TITLE
Incomplete list of packages installed on linux

### ISSUE THREAD

**Issue by brisingertrece** [OCSInventory-NG/UnixAgent#249]
Hello, I am testing the application, I have installed an OCS server, and two clients, one Windows, and one on Linux, in Linux I have a problem with the list of inventoried packages. The problem is that all packages ending with ":amd64" do not appear in the OCS inventory.

 ex: zlib1g-dev:amd64

Any idea how to fix it?

Thanks.

### General informations
Operating system :  Linux is a Debian 10u2 (2019-08-08)
Perl version : Perl/v5.16.3
Unix agent version : Unix-Agent-2.6.0

**Comment by fbomj** [comment]
Fixed. See PR #251
