### ISSUE TITLE
No Memory informations on EC2 instance

### ISSUE THREAD

**Issue by jmguilloux** [OCSInventory-NG/UnixAgent#250]
### General informations
Operating system :  Linux centos 7.7 & debian 9.11
Perl version : 5.16.3 & 5.28.1

### OCS Inventory informations
Unix agent version : 2.4.2

### Problem's description
There's no Memory informations on ec2 instances.

_dmidecode -t6_ or _dmidcode -t 17_ doesn't return any informations.  For e.g : 

> [user@host:]# dmidecode -t 6
dmidecode 3.0
Getting SMBIOS data from sysfs.
SMBIOS 2.7 
>

On OCS server web interface Memory part is empty.

![ocsservermemoriesinfo2](https://user-images.githubusercontent.com/60658302/73759659-8dd7ed80-476c-11ea-95e2-779375e0b58e.PNG)

The informations are missing when bios manufacturer is "Amazon EC2"

### Inventory log file ( optional )
Module is uploaded
`[Tue Feb  4 10:42:30 2020][debug] Running Ocsinventory::Agent::Backend::OS::Generic::Dmidecode::Memory`
No <MEMORIES></MEMORIES> xml tag into the log.

**Comment by fbomj** [comment]
Hi,
Could you send me the global result of the command dmidecode, plz?
Thanks

**Comment by jmguilloux** [comment]
hello,

Yes of course, find below : 

`$ dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.7 present.
6 structures occupying 349 bytes.
Table at 0x000F8FE0.

Handle 0x0000, DMI type 0, 24 bytes
BIOS Information
	Vendor: Amazon EC2
	Version: 1.0
	Release Date: 10/16/2017
	Address: 0xF0000
	Runtime Size: 64 kB
	ROM Size: 64 kB
	Characteristics:
		PCI is supported
		EDD is supported
		ACPI is supported
		System is a virtual machine
	BIOS Revision: 1.0

Handle 0x0001, DMI type 1, 27 bytes
System Information
	Manufacturer: Amazon EC2
	Product Name: c5.large
	Version: Not Specified
	Serial Number: ec20799f-8061-ba74-18ea-c36b0524527e
	UUID: ec20799f-8061-ba74-18ea-c36b0524527e
	Wake-up Type: Power Switch
	SKU Number: Not Specified
	Family: Not Specified

Handle 0x0002, DMI type 2, 15 bytes
Base Board Information
	Manufacturer: Amazon EC2
	Product Name: Not Specified
	Version: Not Specified
	Serial Number: Not Specified
	Asset Tag: i-080939687a37a60e5
	Features: None
	Location In Chassis: Not Specified
	Chassis Handle: 0x0003
	Type: Other
	Contained Object Handles: 0

Handle 0x0003, DMI type 3, 21 bytes
Chassis Information
	Manufacturer: Amazon EC2
	Type: Other
	Lock: Not Present
	Version: Not Specified
	Serial Number: Not Specified
	Asset Tag: Amazon EC2
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Safe
	Security Status: None
	OEM Information: 0x00000000
	Height: Unspecified
	Number Of Power Cords: 1
	Contained Elements: 0

Handle 0x0004, DMI type 4, 42 bytes
Processor Information
	Socket Designation: CPU 0
	Type: Central Processor
	Family: Xeon
	Manufacturer: Intel(R) Corporation
	ID: 53 06 05 00 FF FB EB BF
	Signature: Type 0, Family 6, Model 85, Stepping 3
	Flags:
		FPU (Floating-point unit on-chip)
		VME (Virtual mode extension)
		DE (Debugging extension)
		PSE (Page size extension)
		TSC (Time stamp counter)
		MSR (Model specific registers)
		PAE (Physical address extension)
		MCE (Machine check exception)
		CX8 (CMPXCHG8 instruction supported)
		APIC (On-chip APIC hardware supported)
		SEP (Fast system call)
		MTRR (Memory type range registers)
		PGE (Page global enable)
		MCA (Machine check architecture)
		CMOV (Conditional move instruction supported)
		PAT (Page attribute table)
		PSE-36 (36-bit page size extension)
		CLFSH (CLFLUSH instruction supported)
		DS (Debug store)
		ACPI (ACPI supported)
		MMX (MMX technology supported)
		FXSR (FXSAVE and FXSTOR instructions supported)
		SSE (Streaming SIMD extensions)
		SSE2 (Streaming SIMD extensions 2)
		SS (Self-snoop)
		HTT (Multi-threading)
		TM (Thermal monitor supported)
		PBE (Pending break enabled)
	Version: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
	Voltage: 1.6 V
	External Clock: 100 MHz
	Max Speed: 3500 MHz
	Current Speed: 3000 MHz
	Status: Populated, Enabled
	Upgrade: Other
	L1 Cache Handle: Not Provided
	L2 Cache Handle: Not Provided
	L3 Cache Handle: Not Provided
	Serial Number: Not Specified
	Asset Tag: Not Specified
	Part Number: Not Specified
	Core Count: 1
	Core Enabled: 1
	Thread Count: 2
	Characteristics:
		64-bit capable
		Multi-Core
		Hardware Thread
		Execute Protection

Handle 0x0005, DMI type 127, 4 bytes
End Of Table`


Regards

**Comment by fbomj** [comment]
OK. dmidecode command does not return all necessary informations. The problem is not link with ocs agent.

Regards

**Comment by jmguilloux** [comment]
Hello,
Thanks for the feedback. Do you plan something to work around or correct the problem ?

Regards
