### ISSUE TITLE
Uninstall Linux agent

### ISSUE THREAD

**Issue by bebozps** [OCSInventory-NG/UnixAgent#277]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  RHEL7 family
Perl version : 5

### OCS Inventory informations
Unix agent version : 2.3 (source code)

### Problem's description
keep the binary 2.3 version also if install from rpm 

### Inventory log file ( optional )
[debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.3

**Comment by bebozps** [comment]
which is the better way to unistall ocs-Agent from make procedure to avoid missconfigiuration with 2.6.1 from officila repo? thanks for your support

**Comment by fbomj** [comment]
Make a backup of ocsinventory-agent.cfg file. On CentOS /Rhel run the following commands.
rm -rf /etc/ocsinventory or rm -rf /etc/ocsinventory-agent or rm -rf /usr/local/etc/ocsinventory
rm -rf /var/lib/ocsinventory
rm -rf /var/log/ocsinventory-agent.log
rm -rf /usr/local/share/perl5/[vendor_perl]/Ocsinventory if vendor_perl directory is present
rm -f /usr/local/share/man/man1/ocsinventory-agent.1
