### ISSUE TITLE
Unix OCS agent to collect IP details with ip command

### ISSUE THREAD

**Issue by jitendra-gondaliya** [OCSInventory-NG/UnixAgent#28]
Hi Team,

Current Unix OCS agent need "ifconfig" command to be present/installed in system for ocs agent to get IP details but with RedHat7 ifconfig is not a part of network management commands and we can get the IP details with "ip" command. we need to install RPM "net-tools" to have ifconfig command so that OCS agent can collect IP details. Is there a new release or patch to existing agent which use "ip" command instead of ifconfig so that we dont have to install additional RPM. Also ifconfig will not be supported by RedHat.

Thanks,
Jitendra

**Comment by fbomj** [comment]
Hi,

Latest git version of the unix agent use ip command at first. ifconfig command is not use if not installed. 
Try this version.
Regards
Frank

**Comment by jitendra-gondaliya** [comment]
Hi Frank,

Thanks for this, will try and let you know.

Regards,
Jitendra

**Comment by jitendra-gondaliya** [comment]
Hi,

I did installation of new agent which I downloaded from https://github.com/OCSInventory-NG/UnixAgent, but still I am not able to get the IP address details. I have saved report locally on system with "ocsinventory-agent --local /root" but there also I don't see IP details.

version I have is "Ocsinventory unified agent for UNIX, Linux and MacOSX (2.2)"

Regards,
Jitendra

**Comment by kapouik** [comment]
https://github.com/OCSInventory-NG/UnixAgent/archive/master.zip
Try this version : this is the current devel version.

**Comment by fbomj** [comment]
Hi Jitendra

Could you please send me the file saved locally?

Regards

**Comment by fbomj** [comment]
No reply so I close the issue.
Regards

**Comment by jitendra2050** [comment]
Hi Frank,

Please find the attached locally saved file. IP address is there in local file but when I send data to server its not reflecting IP detail. I have attached log file for your reference. It seems agent is having issue connecting to server.



[l0r-server-38374230-3842-4436-2D45-3337442D3345.txt](https://github.com/OCSInventory-NG/UnixAgent/files/575290/l0r-server-38374230-3842-4436-2D45-3337442D3345.txt)

[ocsinventory.txt](https://github.com/OCSInventory-NG/UnixAgent/files/575291/ocsinventory.txt)
