### ISSUE TITLE
Raspberry have no serials

### ISSUE THREAD

**Issue by Eon9D** [OCSInventory-NG/UnixAgent#287]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Raspbian 10.3

### OCS Inventory informations
Unix agent version : Latest

### Problem's description
Using multiple diffrent raspberrys - none of them are reporting a serial.
Digging deeper this is caused as dmidecode (BIOS.pm) doesnt returning anything.
dmidecode -s baseboard-serial-number
dmidecode -s system-serial-number
Both are empty.
However when running ocsinventory-agent it reports a serial:
BogoMIPS        : 76.80
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a02082
Serial          : 00000000aXXXXba8
Model           : Raspberry Pi 3 Model B Rev 1.2

These information are received by: cat /proc/cpuinfo

**Comment by yvroum** [comment]
I have also the problem.
Informations are to be retrieve on another way on raspi.
I works on it.
I will propose something in the week or if someone has yet resolved ?

**Comment by gillesdubois** [comment]
Hi @yvroum 

I've planned to work on it but I don't have much time.
I'll be glad if you could help us fix this problem :)

Regards,
Gilles.

**Comment by fbomj** [comment]
zip downloaded. Updating agent with your contrib.

**Comment by Eon9D** [comment]
@yvroum I think "fboomj" is needing your permission to use this code. Do you grant?

**Comment by yvroum** [comment]
@Eon9D @fbomj 
Yes I agree, you can use it.
If that can help.

**Comment by fbomj** [comment]
Fixed with #330
