### ISSUE TITLE
Ocsinventory unified agent for UNIX, Linux and MacOSX (2.6.1) not finish good

### ISSUE THREAD

**Issue by sasousuke** [OCSInventory-NG/UnixAgent#289]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubuntu 1804
Perl version : This is perl 5, version 26, subversion 1 (v5.26.1) built for x86_64-linux-gnu-thread-multi

### OCS Inventory informations
Unix agent version : (2.6.1)

### Problem's description
root@perinatologia:~# ocsinventory-agent
Can't open display
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.26.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.

### Inventory log file ( optional )
[ocsinventory.log](https://github.com/OCSInventory-NG/UnixAgent/files/5077856/ocsinventory.log)

**Comment by gillesdubois** [comment]
Hi @sasousuke 

The master branch doesn't have this problem anymore.
The next version will include this fix.

Please note, that it doesn't impact OCS's behavior.

Regards,
Gilles Dubois.
