### ISSUE TITLE
Networks.pm error in the variable $leasepath

### ISSUE THREAD

**Issue by Artem-Mamzikov** [OCSInventory-NG/UnixAgent#291]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Debian 9 x64
Perl version : v5.24.1

### OCS Inventory informations
Unix agent version : 2.6.1

### Problem's description
Use of uninitialized value $leasepath in pattern match (m//) at /usr/local/share/perl/5.24.1/Ocsinventory/Agent/Backend/OS/Linux/Network/Networks.pm line 61.
Use of uninitialized value $leasepath in open at /usr/local/share/perl/5.24.1/Ocsinventory/Agent/Backend/OS/Linux/Network/Networks.pm line 73.
Use of uninitialized value $leasepath in concatenation (.) or string at /usr/local/share/perl/5.24.1/Ocsinventory/Agent/Backend/OS/Linux/Network/Networks.pm line 91.

The IP is set to static
### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi,

Fixed with #295 

Regards,
Gilles Dubois.
