### ISSUE TITLE
I can't get any snmp data

### ISSUE THREAD

**Issue by Artem-Mamzikov** [OCSInventory-NG/UnixAgent#292]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Debian 9 x64 ; AltLinux 8 x64
Perl version : 5.24

### OCS Inventory informations
Unix agent version :  2.6.1

### Problem's description
Is it possible to work with snmp without ssl http?
Everything is configured according to the documentation, groups are created, mib is loaded, and snmp is enabled.
IPDISCOVER works.

[Tue Aug 18 10:29:51 2020][debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.6.1
[Tue Aug 18 10:29:51 2020][debug] Log system initialised (File)
[Tue Aug 18 10:29:51 2020][debug] --scan-homedirs missing. Don't scan user directories
[Tue Aug 18 10:29:51 2020][debug] Accountinfo file: /var/lib/ocsinventory-agent/http:__192.168.60.4_ocsinventory/ocsinv.adm
[Tue Aug 18 10:29:51 2020][debug] OCS Agent initialised
[Tue Aug 18 10:29:51 2020][debug] Turns hooks on for /etc/ocsinventory-agent/modules.conf
[Tue Aug 18 10:29:51 2020][debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.6.1
[Tue Aug 18 10:29:51 2020][debug] Log system initialised (File)
[Tue Aug 18 10:29:51 2020][debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.6.1
[Tue Aug 18 10:29:51 2020][debug] Log system initialised (File)
[Tue Aug 18 10:29:51 2020][debug] Calling handlers : `start_handler'
[Tue Aug 18 10:29:51 2020][debug] [download] Calling download_start_handler
[Tue Aug 18 10:29:51 2020][debug]  - LWP loaded
[Tue Aug 18 10:29:51 2020][debug]  - LWP::Protocol::https loaded
[Tue Aug 18 10:29:51 2020][debug] [snmp] Calling snmp_start_handler
[Tue Aug 18 10:29:51 2020][debug]  - Net::SNMP loaded
[Tue Aug 18 10:29:51 2020][debug] Compress::Zlib is available.
[Tue Aug 18 10:29:51 2020][debug] Calling handlers : `prolog_writer'
[Tue Aug 18 10:29:51 2020][debug] sending XML
[Tue Aug 18 10:29:51 2020][debug] sending: <?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>ZABBIXSERVER-2020-08-18-09-51-03</DEVICEID>
  <QUERY>PROLOG</QUERY>
</REQUEST>
[Tue Aug 18 10:29:51 2020][debug] =BEGIN=SERVER RET======
[Tue Aug 18 10:29:51 2020][debug] $VAR1 = '<?xml version=\'1.0\' encoding=\'UTF-8\'?>
<REPLY>
  <PROLOG_FREQ>4</PROLOG_FREQ>
  <RESPONSE>SEND</RESPONSE>
  <OPTION>
    <NAME>IPDISCOVER</NAME>
    <PARAM IPDISC_LAT="100">192.168.60.0</PARAM>
  </OPTION>
  <OPTION>
    <NAME>DOWNLOAD</NAME>
    <PARAM TIMEOUT="90" TYPE="CONF" FRAG_LATENCY="30" PERIOD_LENGTH="90" EXECUTION_TIMEOUT="120" PERIOD_LATENCY="10" ON="1" CYCLE_LATENCY="90" />
  </OPTION>
  <INVENTORY_ON_STARTUP>1</INVENTORY_ON_STARTUP>
</REPLY>
';
[Tue Aug 18 10:29:51 2020][debug] =END=SERVER RET======
[Tue Aug 18 10:29:51 2020][debug] PROLOG_FREQ has not changed since last process
[Tue Aug 18 10:29:51 2020][debug] Calling handlers : `prolog_reader'
[Tue Aug 18 10:29:51 2020][debug] [download] Calling download_prolog_reader
[Tue Aug 18 10:29:51 2020][debug] [download] <?xml version='1.0' encoding='UTF-8'?>
<REPLY>
  <PROLOG_FREQ>4</PROLOG_FREQ>
  <RESPONSE>SEND</RESPONSE>
  <OPTION>
    <NAME>IPDISCOVER</NAME>
    <PARAM IPDISC_LAT="100">192.168.60.0</PARAM>
  </OPTION>
  <OPTION>
    <NAME>DOWNLOAD</NAME>
    <PARAM TIMEOUT="90" TYPE="CONF" FRAG_LATENCY="30" PERIOD_LENGTH="90" EXECUTION_TIMEOUT="120" PERIOD_LATENCY="10" ON="1" CYCLE_LATENCY="90" />
  </OPTION>
  <INVENTORY_ON_STARTUP>1</INVENTORY_ON_STARTUP>
</REPLY>
[Tue Aug 18 10:29:51 2020][debug] [download] Writing config file.
[Tue Aug 18 10:29:51 2020][debug] [snmp] Calling snmp_prolog_reader
[Tue Aug 18 10:29:51 2020][debug] Failed to load Ocsinventory::Agent::Backend::OS::MacOS::Video: 
*************************************************
[Tue Aug 18 10:38:27 2020][debug] =BEGIN=SERVER RET======
[Tue Aug 18 10:38:27 2020][debug] $VAR1 = '<?xml version=\'1.0\' encoding=\'UTF-8\'?>
<REPLY>
  <RESPONSE>NO_ACCOUNT_UPDATE</RESPONSE>
</REPLY>
';
[Tue Aug 18 10:38:27 2020][debug] =END=SERVER RET======
[Tue Aug 18 10:38:27 2020][debug] Calling handlers : `end_handler'
[Tue Aug 18 10:38:27 2020][debug] [download] Calling download_end_handler
[Tue Aug 18 10:38:27 2020][debug] [snmp] Calling snmp_end_handler
[Tue Aug 18 10:38:27 2020][info] [download] Beginning work. I am 16016.
[Tue Aug 18 10:38:27 2020][info] [download] No more package to download.
[Tue Aug 18 10:38:27 2020][debug] [download] End of work...

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi @Artem-Mamzikov ,

New SNMP implementation require the latest agent from the github branch.
We will publish an official release alongside the 2.8 server release which will most likely goes live during september.

Regards,
Gilles Dubois.

**Comment by Artem-Mamzikov** [comment]
Thanks for the answer! 
Can I do without updating the Server part? (leave version 2.6). 
Agent of the new version 2.6.1 unix with github can you somehow configure the collection of snmp information?

![OCS](https://user-images.githubusercontent.com/60091084/91295468-cfc98f00-e7a3-11ea-86d0-560ff45a2f89.jpg)

**Comment by gillesdubois** [comment]
Hi @Artem-Mamzikov 

The server still need to be updated.
You can wait mid septemer for our 2.8 version or upgrade now using our nightly build : http://download.ocsinventory-ng.org/nightly/

Regards,
Gilles Dubois.

**Comment by Artem-Mamzikov** [comment]
Thanks!
