### ISSUE TITLE
CPU info for i386/x86_64 processors is frequently wrong

### ISSUE THREAD

**Issue by MikkelPaulson** [OCSInventory-NG/UnixAgent#3]
The code that parses `/proc/cpuinfo` and `dmidecode` is flawed, iterating line by line through file/command output rather than reading CPU by CPU. Mostly this won't be noticeable on a system with only one CPU, or where all CPUs are identical, but some stats for CPU 1 will be taken from CPU 0 (and CPU 0 will be empty) because the record submits prematurely. As well, the core count for `dmidecode` improperly falls back on `/proc/cpuinfo`, and reports my dual 12-core Intel Xeon E5-2680 system as having 24 cores on each processor.

I'll fork and attempt a fix myself. It's likely that this problem affects other architectures as well, but I'll leave that code as-is since I have no way of testing it.

**Comment by fbomj** [comment]
Hi,
Which version of the agent do you use?
Regards

**Comment by MikkelPaulson** [comment]
2.1.1. The problem is in [CPU.pm](https://github.com/OCSInventory-NG/UnixAgent/blob/master/lib/Ocsinventory/Agent/Backend/OS/Linux/Archs/i386/CPU.pm) in the master branch; for instance, lines 68-72 set `$current->{CORES}` to the correct value on the `Core Count:` line of `dmidecode` output, but then overwrite it with the (incorrect) value of `$cpucores` on the very next line that's parsed. Lines 101-104 save the data as a new CPU when the `Status:` line is encountered even though (in my `dmidecode` output at least) `Status:` appears above `Upgrade:` (socket) and `Core Count:`.

**Comment by fbomj** [comment]
Hi,

This has been corrected. Try the latest version of the code.

Regards
