### ISSUE TITLE
POD errors

### ISSUE THREAD

**Issue by guimard** [OCSInventory-NG/UnixAgent#300]
Hi,

[Ocsinventory::Agent::Backend::OS::BSD::Networks](lib/Ocsinventory/Agent/Backend/OS/BSD/Networks.pm) and [Ocsinventory::Agent::Backend::OS::Linux::Network::Networks](lib/Ocsinventory/Agent/Backend/OS/Linux/Network/Networks.pm) contain some `=back` that does not match any `=over`

**Comment by fbomj** [comment]
see #302
