### ISSUE TITLE
LSB.pm file is possibly different from 2.6.1 and 2.8

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/UnixAgent#303]
### OCS Inventory informations
Unix agent version : 2.8

### Problem's description
I just upgraded my server to 2.8 and installed a 2.8 agent on uBuntu, Mint and Centos. The way the OS name is printed seems to have reverted back to and old issue (https://github.com/OCSInventory-NG/UnixAgent/issues/127) that was resolved in 2018 when we noticed that the RPM installed agent printed the OS name differently than agents installed from source.

I found Issues on Mint, Ubuntu and Centos. As can be seen in my Centos example I have another version of Centos from one of our old servers as well.

I've found this issue now where the OS name also includes the version. These issues creates havoc on the automation we wrote to handle the OS value
![image](https://user-images.githubusercontent.com/13314239/93599961-403c8800-f9bf-11ea-9fe4-3a7b724b1de9.png)
![image](https://user-images.githubusercontent.com/13314239/93600685-5139c900-f9c0-11ea-9c93-f19862572e58.png)
![image](https://user-images.githubusercontent.com/13314239/93600930-b392c980-f9c0-11ea-87b8-ad9f1e0816fa.png)

This issue was looked at here
https://github.com/OCSInventory-NG/UnixAgent/issues/127

Is it possible to make the OS name uniform and standard across releases? What will be decided in the issue? If this is the new way the OS name is being handled I'll have to know so I can update my automation and asset allocation scripts. Ideally I don't want to cater for different combinations of the OS name.

Please let me know if I can help my providing logs or any other information you need.

**Comment by gillesdubois** [comment]
Hi,

We reverted this changes to uniform release name with Windows agent.
See : https://github.com/OCSInventory-NG/UnixAgent/commit/1fca6a12a4a77ae56f14604a7f7e1c9d852838d4

You can also take a look at this issue : https://github.com/OCSInventory-NG/UnixAgent/issues/290
It is not the only one mentionning this.

Regards,
Gilles.
