### ISSUE TITLE
failliur to detect the correct version of app-portage/gentoolkit on gentoo

### ISSUE THREAD

**Issue by kenshin33** [OCSInventory-NG/UnixAgent#309]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Gentoo
Perl version : 5.30.3

### OCS Inventory informations
Unix agent version : 2.8

### Problem's description
https://github.com/OCSInventory-NG/UnixAgent/blob/master/lib/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Gentoo.pm#L22
will match only equery 0.3 (actually it will match 0 followed by any character followed by 3)... as of now app-portage/gentoolkit is at version 0.5

an easy immediate fix would be to try and  0\.[3-9] (it wont match 0.15 for example). 

this :  /^0\.([3-9]\.?|[0-9]{2,})/, at first glance seems better (i'm no expert in Regular expression) as in will match  0.3 and above  (with any number of digits ans dots). May be there's a better  way to match, the above solved my problem!

**Comment by fbomj** [comment]
Fix with #331 pr
