### ISSUE TITLE
Redundant Argument in sprintf

### ISSUE THREAD

**Issue by forbi** [OCSInventory-NG/UnixAgent#31]
I'm getting this:
`
Redundant Argument in sprintf at /usr/share/perl5/site_perl/Ocs.../Agen../Bakc.../OS/Linux/Network/Networks.pm line 29.
`
Perl version: 5.24.0
Arch Linux.

**Comment by fbomj** [comment]
Hi,

Could you please post the content of ocsinventory-agent.log file?

Regards

**Comment by hschletz** [comment]
It's a warning caused by having one of the tested locations (/var/lib/dhcp/dhclient.leases) not having a placeholder, but still being used as a format string for 1 argument. The code still works as intended. 

Use a string replacement operation instead of sprintf() to get rid of the warning.

**Comment by fbomj** [comment]
Hi,

For info where is stored the lease file ? A correction has been made in the latest version. Try this new version.

Regards
Frank
