### ISSUE TITLE
Argument "" isn't numeric in multiplication - 2.8.0 packages

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/UnixAgent#311]
### General informations
Operating system :  Debian 10 Buster
Perl version : v5.28.1

### OCS Inventory informations
Unix agent version : 2.8.0

### Problem's description
When the agent runs, 1058 lines of this error is generated.

`Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.`

Was previously fixed but it seems the fix did not reach the final version. https://github.com/OCSInventory-NG/UnixAgent/pull/295

This seem to happen because the repo version is still 2.6.1 compiled into the 2.8.0 package.

### Inventory log file ( optional )
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.
Argument "" isn't numeric in multiplication (*) at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Backend/OS/Generic/Packaging/Deb.pm line 62.

**Comment by fbomj** [comment]
Verified in sources and packages => fixed.
