### ISSUE TITLE
2.8.0 version from repo packages wrong. Claims to be 2.6.1

### ISSUE THREAD

**Issue by daniejstriata** [OCSInventory-NG/UnixAgent#312]
### General information
Operating system :  Centos 7 and Debian 10

### OCS Inventory informations
Unix agent version :  2.8.0

### Problem's description

The version for 2.8.0 agents are not updated. They present themselves as 2.6.1. My automation script looks at the installed version to update it and therefore keeps reinstalling the same package every time it runs.

```
/usr/bin/ocsinventory-agent -V
Ocsinventory unified agent for UNIX, Linux and MacOSX (2.6.1)

```
Buster
```
# pkg -l | grep ocs
ii  ocsinventory-agent                   2:2.8                        all          Hardware and software inventory tool (client)
```
Centos 7.8
```
# rpm -qa | grep ocs
ocsinventory-agent-core-2.8.0-1.el7.ocs.x86_64
perl-Ocsinventory-Agent-2.8.0-1.el7.ocs.noarch
ocsinventory-agent-2.8.0-1.el7.ocs.x86_64
```

**Comment by daniejstriata** [comment]
Seems the latest packages for Ubuntu and Centos are still incorrectly compiled.

**Comment by kapouik** [comment]
It look like very strange. 

# ocsinventory-agent -v
Ocsinventory unified agent for UNIX, Linux and MacOSX (2.8.0)
# rpm -qa |grep ocs
ocsinventory-release-7-4.el7.ocs.noarch
ocsinventory-agent-core-2.8.0-1.el7.ocs.x86_64
ocsinventory-agent-2.8.0-1.el7.ocs.x86_64
perl-Ocsinventory-Agent-2.8.0-1.el7.ocs.noarch

Do you have install the agent whit the tar.gz before ?

**Comment by daniejstriata** [comment]
I used the source package before I started using the current repo versions. I don't see any other version of the binary on my server.

```
# locate ocsinventory-agent | grep bin
/usr/sbin/ocsinventory-agent
```
```
# /usr/sbin/ocsinventory-agent -V
Ocsinventory unified agent for UNIX, Linux and MacOSX (2.6.1)
```
```
# rpm -qa |grep ocs
ocsinventory-release-7-4.el7.ocs.noarch
ocsinventory-agent-2.8.0-1.el7.ocs.x86_64
perl-Ocsinventory-Agent-2.8.0-1.el7.ocs.noarch
ocsinventory-agent-core-2.8.0-1.el7.ocs.x86_64
```

**Comment by fbomj** [comment]
Did you remove agent (source installed) before installing its with repo ?

**Comment by daniejstriata** [comment]
I'd like to believe the RPM would cater for an upgrade like this as for a long time there was no other option but to use the source install for the latest version.

How I migrated from source to repo:

1. Check if the latest binary is on disk
2. check if the source install exist in /etc/ocsinventory-agent and delete it after coping the configs to /etc/ocsinventory/
3. Delete the source binary at /usr/local/bin/ocsinventory-agent
4. Delete man pages for source version.

```
	if [[ "$_currentOCSVersion" != "$_installedOcsVersion" ]]; then
		ocs_repo_installer
	fi

	if [[ -e /etc/ocsinventory-agent/ ]]; then
		$_cp /etc/ocsinventory-agent/* /etc/ocsinventory/
		rm -Rf /etc/ocsinventory-agent
	fi
	if [[ -e /usr/local/bin/ocsinventory-agent ]]; then
		rm -Rf /usr/local/bin/ocsinventory-agent
		rm -Rf /usr/local/share/man/man1/ocsinventory-agent.1
	fi
```

**Comment by fbomj** [comment]
I've just made the test. I've older version of the agent on my server (2.6.1) installed with source. Remove it and install the agent with dnf install command. 
ocsinventory-agent --version reports me 2.8.0.

**Comment by daniejstriata** [comment]
@fbomj Can you please elaborate how you remove the source version differently than I do?

**Comment by fbomj** [comment]
rm -rf /etc/ocsinventory 
rm -rf /var/lib/ocsinventory
rm -rf /var/log/ocsinventory-agent.log
rm -rf /usr/local/share/perl5/[vendor_perl]/Ocsinventory if vendor_perl directory is present
rm -f /usr/local/share/man/man1/ocsinventory-agent.1

**Comment by daniejstriata** [comment]
Thanks for your input. It seems I had do delete as well. When installing the Package this does not get recreated but if it is there it seem to confuse the agent.

```
# ocsinventory-agent -V
Ocsinventory unified agent for UNIX, Linux and MacOSX (2.6.1)
```
`rm -Rf /usr/local/share/perl5/Ocsinventory `
```
# ocsinventory-agent -V
Ocsinventory unified agent for UNIX, Linux and MacOSX (2.8.0)
```
