### ISSUE TITLE
Agent on macOS uses SSLv3

### ISSUE THREAD

**Issue by multiflexi** [OCSInventory-NG/UnixAgent#314]
### General informations
Operating system :  macOS Mojave 10.14.6
Perl version : v5.18.4

### OCS Inventory informations
Unix agent version : 2.6.0

### Problem's description
Agent cannot connect to the server because (according to log) tries to use SSLv3. Server supports only TLS 1.2 and 1.3. Agent on Mac with Catalina works without issues. 
```
cat /var/log/ocsng.log
[Sun Oct 11 19:11:43 2020][error] Cannot establish communication : 500 Can't connect to ocsi.vse.cz:443 (LWP::Protocol::https::Socket: SSL connect attempt failed because of handshake problems error:14004410:SSL routines:CONNECT_CR_SRVR_HELLO:sslv3 alert handshake failure)

```

**Comment by daniejstriata** [comment]
I've seen this in the past. Following.

**Comment by gillesdubois** [comment]
Hi,

2.8 of the mac agent is coming soon. We will address the problem during this release.

Regards,
Gilles.

**Comment by multiflexi** [comment]
Hi, I just installed agent version  2.8.0 and the behaviour is exactly the same.

**Comment by multiflexi** [comment]
Am I the only one with this issue or is it well known?

**Comment by fbomj** [comment]
which version of openssl and Net::SSLeay ?

**Comment by multiflexi** [comment]
LibreSSL 2.6.5 and Net::SSLeay 1.72.

**Comment by fbomj** [comment]
Upgrade to latest version of LibreSSL and Net::SSLeay (1.88)

**Comment by daniejstriata** [comment]
Do you mean to update those libraries for the OS or to compile OCS using these?

**Comment by fbomj** [comment]
Update librairies for OS.

**Comment by fbomj** [comment]
Issue closed with no comments
