### ISSUE TITLE
XML file of the result of SNMP queries containing values ​​encoded in octetstring (raw snmp response) and a response code "500" from the server

### ISSUE THREAD

**Issue by FredCL1** [OCSInventory-NG/UnixAgent#319]
### General informations
Operating system :  Centos 7.8 2003
Perl version : v5.16.3

### OCS Inventory informations
Unix agent version : V2.8

### Problem's description

During an SNMP inventory of an HP printer, I observed problems encoding the SNMP responses in the XML file sent to the server (formatting the responses in octetstring format in the XML tags) and returning a 500 code from the OCS server

label + following OID:

Imprimante HP | Description | 1.3.6.1.2.1.1.1.0   
Imprimante HP | uptime | 1.3.6.1.2.1.1.3.0   
Imprimante HP | Model Name | 1.3.6.1.4.1.11.2.3.9.4.2.1.1.3.1.0   
Imprimante HP | Serial Number | 1.3.6.1.4.1.11.2.3.9.4.2.1.1.3.3.0 | Yes

The traces below come from the logs of an agent ocs inventory V2.8 on a Centos 7.8 2003, version of perl v5.16.3

The HP MiB (HP-LASERJET-COMMON-MIB.mib) is indeed the directory "/ usr / share / snmp / mibs", the access rights are OK (similar to the other mibs)

We can see that the XML Model Name and Serial Number tags are in the OctetString format and therefore probably in the expected format

We can observe at the end of the logs that the OCS server returns a code "500 Internal Server Error"

The logs:

```Fri Nov 13 22:45:38 2020][debug] sending: <?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <CONTENT>
    <snmp_imprimante_hp>
      <Description>HP ETHERNET MULTI-ENVIRONMENT,SN:VNC3S88888,FN:8G44X2Z,SVCID:30157,PID:HP LaserJet MFP M28w</Description>
      <Model Name>01:15:57:32:47:35:35:41</Model Name>
      <Serial Number>01:15:56:4E:43:33:53:38:38:38:38:38</Serial Number>
      <uptime>8 days, 03:58:42.74</uptime>
    </snmp_imprimante_hp>
  </CONTENT>
  <DEVICEID>agentocs-2020-11-13-18-50-24</DEVICEID>
  <QUERY>SNMP</QUERY>
</REQUEST>

[Fri Nov 13 22:45:38 2020][error] Cannot establish communication : 500 Internal Server Error
[Fri Nov 13 22:45:38 2020][debug] [snmpscan] End snmp_end_handler :)
```

Proposal to modify the module code

I tested a perl code modification of the configuration of the "-translate" parameter of the Net :: SNMP object with the following configuration in the SnmpScan.pm and Snmp.pm modules
```
-translate   => [-nosuchinstance => 0, -nosuchobject => 0, -octetstring => 0]
```
origine code  :

```
-translate   => [-nosuchinstance => 0, -nosuchobject => 0, ]
```
full exemple :
```
                # We have an older version v2c ou v1
                ($session, $error) = Net::SNMP->session(
                    -retries     => 1 ,
                    -timeout     => 3,
                    -version     => 'snmpv'.$comm->{VERSION},
                    -hostname    => $device->{IPADDR},
                    -community   => $comm->{NAME},
                    -translate   => [-nosuchinstance => 0, -nosuchobject => 0, -octetstring => 0],
```

I made the modifications 2 times (snmp V1 / V2 and snmp V3 function) in the SnmpScan.pm and Snmp.pm modules

After the modification, the results are as follows in the log file:

the formatting of the SNMP responses in the XML tags is correct ... However, the response from the server is always "Cannot establish communication: 500 Internal Server"

```
<REQUEST>

  <CONTENT>
    <snmp_imprimante_hp>
      <Description>HP ETHERNET MULTI-ENVIRONMENT,SN:VNC3S88888,FN:8G44X2Z,SVCID:30157,PID:HP LaserJet MFP M28w</Description>
      <Model Name>W2G55A</Model Name>
      <Serial Number>VNC3S88888</Serial Number>
      <uptime>8 days, 06:06:36.83</uptime>
    </snmp_imprimante_hp>
  </CONTENT>
  <DEVICEID>agentocs-2020-11-13-18-50-24</DEVICEID>
  <QUERY>SNMP</QUERY>
</REQUEST>

[Sat Nov 14 00:53:33 2020][error] Cannot establish communication : 500 Internal Server Error
[Sat Nov 14 00:53:33 2020][debug] [snmpscan] End snmp_end_handler :
```

Server OCS Logs :

```
[Sat Nov 14 00:53:33.029221 2020] [perl:error] [pid 1837] [client 192.168.0.26:44192] \nnot well-formed (invalid token) at line 6, column 17, byte 228 at /usr/lib64/perl5/vendor_perl/XML/Parser.pm line 187.\n
```

Can you look at the problem with encoding SNMP responses in the OCS client XML file and the server error 500, and maybe also my suggested code change! :-)

Cordially !

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi @FredCL1 

A lot of fixes has been made on the 2.8.1 unix agent and the 2.8.1 server.
SNMP should work way better if you upgrade :) 

Thanks for your report and contribution.

Regards,
Gilles.
