### ISSUE TITLE
Uninitialized value $leasepath

### ISSUE THREAD

**Issue by laupera** [OCSInventory-NG/UnixAgent#32]
Bonjour,

   je rencontre un problème lors du premier lancement de l'agent UNIX à la fin de l'installation et j'obtiens, ces messages d'erreur

Launching OCS Inventory NG Unix Unified agent...
Use of uninitialized value $leasepath in open at /usr/local/share/perl/5.22.1/Ocsinventory/Agent/Backend/OS/Linux/Network/Networks.pm line 55.
Use of uninitialized value $leasepath in concatenation (.) or string at /usr/local/share/perl/5.22.1/Ocsinventory/Agent/Backend/OS/Linux/Network/Networks.pm line 73.
Can't open 
   -> Failed!

Es ce normal?

 Merci

**Comment by fbomj** [comment]
Bonjour,

Désolé pour le retard de la réponse.

Quel sont l'OS et la distribution Unix utilisés? 
Quel est le chemin de stockage et le nom du fichier pour le bail DHCP? 

Cordialement

**Comment by pilch-cit** [comment]
Hello,

the issue is fixed in our fork but I still have a few fixes I want to do before I do a pull request.

Best regards

**Comment by MyTheValentinus** [comment]
Hello @pilch-cit,
Thank for you fixes, i'm stay connected to test your pull request

**Comment by MyTheValentinus** [comment]
Hello this issue was fixed here https://github.com/OCSInventory-NG/UnixAgent/pull/33
