### ISSUE TITLE
BigSur Compatible?

### ISSUE THREAD

**Issue by sokatra** [OCSInventory-NG/UnixAgent#320]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  BigSur
Perl version :

### OCS Inventory informations
Unix agent version : 2.8

### Problem's description
I .. is Agent 2.8 compatible with BigSur? because Agent was released on November 6. and BigSur some days after that date 

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi @sokatra 

MacOS package backward compatibility with the latest SDK, in your case it should be OK since are based on a recent SDK.

Regards,
Gilles.
