### ISSUE TITLE
Certificate verify failed with Ubuntu package

### ISSUE THREAD

**Issue by adaigre** [OCSInventory-NG/UnixAgent#324]
Hello,

I'm trying to configure Linux agents to use HTTPS. We are using the rather dated ocsinventory-agent package provided in Ubuntu 18.04 repository.

### General informations
Operating system :  Ubuntu 18.04.4 LTS
Perl version : 5.26.1
OCS server version : 2.1.2

### OCS Inventory informations
Unix agent version : 2.0.5-1.2

### Problem's description
ocsinventory-agent returns "[error] Cannot establish communication : 500 Can't connect to OCSSERVER:443 (certificate verify failed)"

But the same configuration (and cafile) under Windows is working without problems. We are using the same version for Windows computers although the implementation looks different.
Using "--debug" flag does not show useful information about certificate verification.

I'de like to stay on the repository provided package if possible.

Thanks for your help !

**Comment by gillesdubois** [comment]
Hi,

Please update your OCS Inventory server and agents ...
2.1.2 Server is now 6-7 years old.
Your agent version is even older.

Don't use the official repositories we do have our own (and up to date) repository for debian / ubuntu / redhat / centos.

On ubuntu you will need to install the server manually (using setup.sh)
If you switch on CentOS / Redhat, our repository have an ocsinventory-server package with the latest version.

You will find some links below : 
* http://wiki.ocsinventory-ng.org/
* http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-UNIX-agent-using-repository-on-client-computers/
* http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server/
* http://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-a-OCS-Inventory-Server-with-rpm/

Regards,
Gilles.

**Comment by adaigre** [comment]
Hi Gilles,

I didn't notice that you offered your own repositories! However with the 2.8 agent provided in that repo I've the following issue : #310 .
Is it possible to build a new release ? That would allow me to deploy from the official repo.

Thanks for your work, your support and reactivity!

**Comment by gillesdubois** [comment]
Yes, we are aware of the issue. A new release will be published soon and address this problem.
Please note that this problem doesn't prevent inventory from being done.

You can also check the patch applied here :
https://github.com/OCSInventory-NG/UnixAgent/issues/310

Thanks for your kind words,
Have a nice day.
