### ISSUE TITLE
Question of Compatibility - MacOS 11.1

### ISSUE THREAD

**Issue by souwill** [OCSInventory-NG/UnixAgent#328]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  MacOS 11.1 - Big Sur
Perl version :

### OCS Inventory informations
Unix agent version : 2.8

### Problem's description
Dears
have any prediction of compatibility with the system MacOS 11.1 Big Sur?
Best Regards!

**Comment by souwill** [comment]
Dears?

Any response?

Thanks!

**Comment by gillesdubois** [comment]
Hi, 

We will take a look at your issues during the next week.

Regards,
Gilles.

**Comment by sgargel** [comment]
Just installed today v2.8.0:
```
OS Name :macOS
OS Version :11.1 (20C69)
Service pack :Darwin Kernel Version 20.2.0: Wed Dec 2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101
Description :x86_64/00-00-00 00:26:23
User agent :OCS-NG_unified_unix_agent_v2.8.0
```
It's working quite well.

**Comment by souwill** [comment]
> Just installed today v2.8.0:
> 
> ```
> OS Name :macOS
> OS Version :11.1 (20C69)
> Service pack :Darwin Kernel Version 20.2.0: Wed Dec 2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101
> Description :x86_64/00-00-00 00:26:23
> User agent :OCS-NG_unified_unix_agent_v2.8.0
> ```
> 
> It's working quite well.

This system is MacOS Big Sur ?

**Comment by sgargel** [comment]
Yes. Latest versions: https://en.m.wikipedia.org/wiki/MacOS_Big_Sur

**Comment by gillesdubois** [comment]
Hi,

We updated our dev environement to Big Sur (most of them being Mac Mini) and it seems to be working fine so far :) 

Regards,
Gilles.

**Comment by souwill** [comment]
thanks for your response!

I will make a test and will response for you!

Best regards!

**Comment by souwill** [comment]
Hi @gillesdubois !!!!

I did a test and it worked correctly in the version Big Sur. Thank you very much for the support, we closed this successfully! 

Best Regards! =)
