### ISSUE TITLE
RHEL: systemd timer or cron?

### ISSUE THREAD

**Issue by mimmus** [OCSInventory-NG/UnixAgent#332]
I noticed that ocsinventory-agent 2.6.x on RHEL 7 uses systemd timer to schedule agent runs (but it is not enabled by default) while older releases used cron (enabled by default).
Instead, 2.8.x on RHEL8 uses cron again!

This breaks our deployment systems. Any explanation?

**Comment by mimmus** [comment]
Probably, only package using systemd timer is the EPEL7 package

**Comment by fbomj** [comment]
Our package uses cron not systemd timer. So use it.
