### ISSUE TITLE
Backend Timeout because of 'last' command

### ISSUE THREAD

**Issue by wiltonsr** [OCSInventory-NG/UnixAgent#333]
### General informations
Operating system :  Unix
Perl version : All

### OCS Inventory informations
Unix agent version : All

### Problem's description
On some systems, especially those that run `proftpd` with the [wtmplog option enabled](http://www.proftpd.org/docs/directives/linked/config_ref_WtmpLog.html), that is the default behavior, there is a great tendency for the file `/var/log/wtmp` to grow out of control.

The problem can be solved by disabling the option, however if it is enabled the user will face problems during the agent's execution, as this file is used by the `last` command to display the latest logins. The problem is that when this file is very large, 12GB on some systems I know, the `last` command takes a long time to display all the output. 

Consequently, [Linux.pm](https://github.com/OCSInventory-NG/UnixAgent/blob/b37a044c200a9b5c76a6a7aecaec3b29a4018c8a/lib/Ocsinventory/Agent/Backend/OS/Linux.pm#L17) and [Users.pm](https://github.com/OCSInventory-NG/UnixAgent/blob/b37a044c200a9b5c76a6a7aecaec3b29a4018c8a/lib/Ocsinventory/Agent/Backend/OS/Generic/Users.pm#L12) modules that use this command end up receiving timeout. The inventory takes place correctly, however it takes up to 20 minutes to complete.

### Inventory log file ( optional )

```bash
time /usr/bin/ocsinventory-agent -f
real    20m4.633s
user    0m2.264s
sys     0m1.040s

...
[Fri Jan 15 11:38:08 2021][debug] Ocsinventory::Agent::Backend::OS::Generic::Users killed by a timeout.
...
[Fri Jan 15 11:48:09 2021][debug] Ocsinventory::Agent::Backend::OS::Linux killed by a timeout.
...
```

An alternative solution to solve this problem can be to use the [-n from last](https://man7.org/linux/man-pages/man1/last.1.html) option and specify a fixed value for the `last` outputs. Taking into account that the objective is to inventory the last logged in user and the occurrences of `reboot` and `shutdown`, a `last -R -n 50` should be enough to solve the problem on `Users.pm` and `last -n 1` on `Users.pm`'s command verify and `last -R -n 1` to `Linux.pm`, since `foreach` will only get `first` value.

**Comment by fbomj** [comment]
PR #334 merged
