### ISSUE TITLE
ssl=0 not respected

### ISSUE THREAD

**Issue by fourstepper** [OCSInventory-NG/UnixAgent#336]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  CentOS7
Perl version : 5.16.3

### OCS Inventory informations
Unix agent version : 2.6.0

### Problem's description
Even though I have set in my config that I don't want to verify the ssl certificate of the server (with ssl=0) and didn't specify the ca=, I am still getting:

`[Tue Feb 23 15:04:00 2021][error] Cannot establish communication : 500 SSL_ca_file /var/lib/ocsinventory-agent/https:__example.com_ocsinventory_/cacert.pem does not exist`

My config looks like this:
```
server=https://example.com/ocsinventory/
basevardir=/var/lib/ocsinventory-agent
debug=1
configdir=/etc/ocsinventory
logfile=/var/log/ocsinventory-agent/ocsinventory-agent.log
ssl=0
nosoftware=1
```

**Comment by fbomj** [comment]
Hi,

If you don't want to use ssl set server to http://example.com/ocsinventory otherwise set ssl=1 specify ca=/var/lib/ocsinventory/https__:example.com_ocsinventory/cacert.pem and server=https://example.com/ocsinventory

Regards

**Comment by fourstepper** [comment]
So this is a breaking change.

@fbomj Could you explain the reasoning behind removing that choice that is available in the previous versions?

I would like to send the content of the report over SSL, but in certain scenarios it is either not possible or needed to verify the SSL certificate, which is what the `ssl=0` flag did before
