### ISSUE TITLE
Net::SNMP module error Red HAT 7.9

### ISSUE THREAD

**Issue by AllendeJavier** [OCSInventory-NG/UnixAgent#349]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Red Hat 7.9
Perl version :  perl 5, version 16, subversion 3 (v5.16.3) built for x86_64-linux-thread-multi

### OCS Inventory informations
Unix agent version :  2.8.01

### Problem's description
in the process of start appears the following error 

[Sat May  8 08:08:26 2021][error] [snmpscan] Net::SNMP perl module is missing !!
[Sat May  8 08:08:26 2021][error] [snmpscan] Humm my prerequisites are not OK...disabling module :( :(

yum list installed | grep snmp
net-snmp.x86_64                     1:5.7.2-49.el7_9.1       @rhel-7-server-rpms
net-snmp-agent-libs.x86_64          1:5.7.2-49.el7_9.1       @rhel-7-server-rpms
net-snmp-devel.x86_64               1:5.7.2-49.el7_9.1       @rhel-7-server-rpms
net-snmp-libs.x86_64                1:5.7.2-49.el7_9.1       @rhel-7-server-rpms
net-snmp-perl.x86_64                1:5.7.2-49.el7_9.1       @rhel-7-server-optional-rpms
net-snmp-utils.x86_64               1:5.7.2-49.el7_9.1       @rhel-7-server-rpms

yum update
Loaded plugins: product-id, search-disabled-repos, subscription-manager
No packages marked for update

yum install net-snmp-perl
Loaded plugins: product-id, search-disabled-repos, subscription-manager
Package 1:net-snmp-perl-5.7.2-49.el7_9.1.x86_64 already installed and latest version
Nothing to do

any ideas??

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
install perl-Net-SNMP package

**Comment by AllendeJavier** [comment]
I've search for this packeget 

# yum list all |grep perl | grep SNMP
perl-SNMP_Session.noarch         1.13-5.el7          rhel-7-server-rpms
# yum list all |grep perl | grep snmp
net-snmp-perl.x86_64             1:5.7.2-49.el7_9.1  @rhel-7-server-optional-rpms


The package that i've installed 
[root@as-mad-pre secjallende]# yum list installed |grep perl | grep snmp
net-snmp-perl.x86_64                1:5.7.2-49.el7_9.1       @rhel-7-server-optional-rpms

Where can i find this package??
regards

**Comment by fbomj** [comment]
on epel http://mirror.in2p3.fr/pub/epel/7/x86_64/Packages/p/perl-Net-SNMP-6.0.1-7.el7.noarch.rpm
