### ISSUE TITLE
Interface IP  OS X not detected

### ISSUE THREAD

**Issue by dwtz** [OCSInventory-NG/UnixAgent#35]
Thunderbolt to Gigabit Ethernet Adapter detected but Interface missing in NETWORKS
[debug.txt](https://github.com/OCSInventory-NG/UnixAgent/files/502352/debug.txt)

**Comment by fbomj** [comment]
Hi,

I need ocsinventory-agent.log content. Please post it.

Regards

Frank

**Comment by dwtz** [comment]
Hi,

OCS Inventory Agent: 
/Applications/OCSNG.app/Contents/Resources/ocsinventory-agent --version
Ocsinventory unified agent for UNIX, Linux and MacOSX (2.1.1)
OSX Version: 10.9.5

Regards
Dirk

[ocsng.txt.zip](https://github.com/OCSInventory-NG/UnixAgent/files/502689/ocsng.txt.zip)

**Comment by fbomj** [comment]
Hi,

Latest version of the agent can retrieve networks from en0 to en5. Try it.

Regards

Frank
