### ISSUE TITLE
$network/24 hardcoded!?!

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/UnixAgent#350]
What about other network masks?!?

https://github.com/OCSInventory-NG/UnixAgent/blob/2456a417fc2f78046de06a73b46882ffc74b98f8/lib/Ocsinventory/Agent/Backend/IpDiscover/Nmap.pm#L54

**Comment by charleneauger** [comment]
Hi @StCyr,

Indeed, this data is hardcoded.

We don’t think we’ll make any immediate changes. Today, NMAP is mainly used for dev/test purposes rather than for production.

In the majority of cases, users force-disable NMAP.

Best regards,
Charlene
