### ISSUE TITLE
how to not Updating Subscription Management in linux

### ISSUE THREAD

**Issue by NandoDark** [OCSInventory-NG/UnixAgent#351]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  rhel6/7/8
Perl version : 5.26.3

### OCS Inventory informations
Unix agent version : 2.8.0

### Problem's description
It is possible to configure the agent so as not to update the repository. My servers that do not access the internet take a long time to complete the inventory. 

### Inventory log file ( optional )
![OCS Time](https://user-images.githubusercontent.com/12589889/119396147-df322600-bcaa-11eb-8476-626f9bed408a.PNG)

**Comment by fbomj** [comment]
Disable ocsinventory repository. Set enable=0 in ocsinventory-agent.repo file.

**Comment by NandoDark** [comment]
It's not the OCS repository I'm referring to.
The ocsinventory-agent performs a "yum repolist" or a "yum makecache" on the server and because it doesn't have internet access the process is stopped for a long time.

**Comment by NandoDark** [comment]
![Erro OCS](https://user-images.githubusercontent.com/12589889/125475519-61b11b6f-7dc3-4821-8fb5-b89402104b82.PNG)

**Comment by fbomj** [comment]
yes ocsinventory-agent runs 'yum -v repolist' command to retrieve detailed informations on repositories.  With no Internet or Intranet access the result of the command is immediate.
