### ISSUE TITLE
[BUG]OCS Mac agent sends inventory without username, password and realm.

### ISSUE THREAD

**Issue by rajeevso** [OCSInventory-NG/UnixAgent#352]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubuntu 20.04.1 LTS
Perl version : 5.30

### OCS Inventory informations
Unix agent version :  Unix Agent 2.6.0 (Mac Version)

### Problem's description
The ocsinventory server is configured to accept inventory from the agent which are having following details 
1 - Username
2 - Password
3 - Realm
4 - Certificate.
And this setup works with Windows and Linux. But when we deploy OCS mac agent on the mac machines it ask for certificate and sends the inventory to the OCS inventory server.

We want, if mac agent doesn't have that details then the inventory server shouldn't accept the data.

**Comment by gillesdubois** [comment]
Hi @rajeevso 

If you set a server side basic auth and your agent can still connect without user / password, it means your Apache configuration is wrong.

Its not related to the agent because whats manage the authentication is the server.
You might need to review your apache configuration and make sure that the authentication is requested in every case.

Regards,
Gilles.

**Comment by rajeevso** [comment]
Thanks, @gillesdubois 
We checked the configuration as mentioned above by you and yes the authorization type is basic.
If we want to make it work what authorization type should we keep?
If we change the authorization type, will there be any impact on the computers with windows and Linux OS.

**Comment by charleneauger** [comment]
Hi @rajeevso,

Can you update your agent to version 2.10 ? 
This release officially includes agent authentication functionality. 
Older versions used limited support which could cause some problems when authenticating the agent.

Best regards,
Charlene

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
