### ISSUE TITLE
SNMP Scan no result

### ISSUE THREAD

**Issue by inferno66** [OCSInventory-NG/UnixAgent#357]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Centos7
Perl version : 5.2.6

### OCS Inventory informations
Unix agent version : 2.8.1

### Problem's description
Hello,
I'm trying to scan my network for Linux and Windows Server and get some informations with SNMP (like I used to do when my OCS Server was in 2.5 version).

SNMP is enable on OCS Server.
I've a Linux Agent which is enable to do SNMP scan with selected network to scan (i've tried on remote and local subnet)

I've done multiple test, but my actual SNMP configuration is (for testing)  : 
Type Name : Windows63
Type OID : 1.3.6.1.2.1.1.1
Type OID string value : Hardware: Intel64 Family 6 Model 15 Stepping 1 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 9600 Multiprocessor Free)

(I've did a SNMPWALK on a device from my OCS Agent Server an this is the aswner I got with this OID)

Label : Name
OID : 1.3.6.1.2.1.1.5.0

Example of SNMPWalk result (from my ocsagent machine) : 
 snmpwalk -v2c -c asasaasa 10.210.110.17 1.3.6.1.2.1.1.1
SNMPv2-MIB::sysDescr.0 = STRING: Hardware: Intel64 Family 6 Model 15 Stepping 1 AT/AT COMPATIBLE - Software: Windows Version 6.3 (Build 9600 Multiprocessor Free)

Agent log : 

[Tue Jul  6 17:53:37 2021][debug] =BEGIN=SERVER RET======
[Tue Jul  6 17:53:37 2021][debug] $VAR1 = '<?xml version=\'1.0\' encoding=\'UTF-8\'?>
<REPLY>
  <RESPONSE>NO_ACCOUNT_UPDATE</RESPONSE>
</REPLY>
';
[Tue Jul  6 17:53:37 2021][debug] =END=SERVER RET======
[Tue Jul  6 17:53:37 2021][debug] Calling handlers : `end_handler'
[Tue Jul  6 17:53:37 2021][debug] [snmpscan] Calling snmp_end_handler
[Tue Jul  6 17:53:37 2021][debug] [snmpscan] Snmp: Scanning network
[Tue Jul  6 17:53:37 2021][debug]  - Net::Netmask loaded
[Tue Jul  6 17:53:37 2021][debug]  - Net::Ping loaded
[Tue Jul  6 17:53:37 2021][debug] [snmpscan] Scanning 10.210.110.0/24 with ping
[Tue Jul  6 17:53:40 2021][debug] [snmpscan] Found 10.210.110.4
[Tue Jul  6 17:53:43 2021][debug] [snmpscan] Found 10.210.110.8
[Tue Jul  6 17:53:47 2021][debug] [snmpscan] Found 10.210.110.13
[Tue Jul  6 17:53:50 2021][debug] [snmpscan] Found 10.210.110.17
[Tue Jul  6 17:54:06 2021][debug] [snmpscan] Found 10.210.110.34
[Tue Jul  6 17:54:06 2021][debug] [snmpscan] Found 10.210.110.35
[Tue Jul  6 17:54:07 2021][debug] [snmpscan] Found 10.210.110.37
[Tue Jul  6 17:54:16 2021][debug] [snmpscan] Found 10.210.110.46
[Tue Jul  6 17:54:19 2021][debug] [snmpscan] Found 10.210.110.50
[Tue Jul  6 17:54:26 2021][debug] [snmpscan] Found 10.210.110.58
[Tue Jul  6 17:54:55 2021][debug] [snmpscan] Found 10.210.110.88
[Tue Jul  6 17:54:55 2021][debug] [snmpscan] Found 10.210.110.89
[Tue Jul  6 17:57:39 2021][debug] [snmpscan] Found 10.210.110.254
[Tue Jul  6 17:57:39 2021][debug] [snmpscan] Snmp: Ending Scanning network
[Tue Jul  6 17:57:39 2021][debug] [snmpscan] Scanning 10.210.110.4 device
[Tue Jul  6 17:57:57 2021][debug] [snmpscan] Scanning 10.210.110.8 device
[Tue Jul  6 17:58:15 2021][debug] [snmpscan] Scanning 10.210.110.13 device
[Tue Jul  6 17:58:51 2021][debug] [snmpscan] Scanning 10.210.110.17 device
[Tue Jul  6 17:59:09 2021][debug] [snmpscan] Scanning 10.210.110.34 device
[Tue Jul  6 17:59:27 2021][debug] [snmpscan] Scanning 10.210.110.35 device
[Tue Jul  6 17:59:45 2021][debug] [snmpscan] Scanning 10.210.110.37 device
[Tue Jul  6 18:00:03 2021][debug] [snmpscan] Scanning 10.210.110.46 device
[Tue Jul  6 18:00:39 2021][debug] [snmpscan] Scanning 10.210.110.50 device
[Tue Jul  6 18:00:57 2021][debug] [snmpscan] Scanning 10.210.110.58 device
[Tue Jul  6 18:01:15 2021][debug] [snmpscan] Scanning 10.210.110.88 device
[Tue Jul  6 18:01:33 2021][debug] [snmpscan] Scanning 10.210.110.89 device
[Tue Jul  6 18:02:09 2021][debug] [snmpscan] Scanning 10.210.110.254 device
[Tue Jul  6 18:02:27 2021][info] [snmpscan] No more SNMP device to scan
[Tue Jul  6 18:02:27 2021][debug] sending XML
[Tue Jul  6 18:02:27 2021][debug] sending: <?xml version="1.0" encoding="UTF-8"?>
<REQUEST>
  <DEVICEID>lx8496-2021-07-01-15-26-23</DEVICEID>
  <QUERY>SNMP</QUERY>
</REQUEST>

[Tue Jul  6 18:02:27 2021][debug] [snmpscan] End snmp_end_handler :)

Maybe it's just an SNMP configuration issue, but the documentation is not very clear about this part.
Help will be very appreciated.
What's is the best configuration if I just want to SNMP scan for Servers with OCS? 
Thanks a lot 

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by namery** [comment]
i have the same issue

**Comment by felixrodrigo19** [comment]
I have the same issue too

**Comment by akhiltrip** [comment]
Hii,
Devices which you are scanning are Ipdiscovered or not ?Devices should be ipdiscovered for Snmp scan

**Comment by alias59** [comment]
Hi,
I have the same problem.
For me, they devices which we are scanning are IpDiscovered
Thank you

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
