### ISSUE TITLE
Deuxième carte réseau non inventoriée

### ISSUE THREAD

**Issue by xnae** [OCSInventory-NG/UnixAgent#37]
Bonjour,
L'inventaire ne reporte pas la deuxième carte réseau : la carte réseau wifi "wlp4s0" est bien listée dans ocsreports mais la carte réseau filaire "enp5s0f2" ne l'est pas.

Matériel :

> sans-fil : wlp4s0 : Intel Corporation Wireless 7260 [8086:08b1](rev 73)
> filaire : enp5s0f2 : Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller [10ec:8168](rev 0a)

UnixAgent :

> OCS-NG_unified_unix_agent_v2.2 (version de l'agent (master) du 17/10/2016 20:01 UTC+2)

Environnement :

> Distribution : LinuxMint 18
> Kernel : Linux 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Log (debug=2) :

> [ocsinventory-agent.log.txt](https://github.com/OCSInventory-NG/UnixAgent/files/548717/ocsinventory-agent.log.txt)

Est-il possible de corriger ce problème ?

Cordialement.

**Comment by fbomj** [comment]
Bonjour

La 2ème carte est bien up et configurée? Merci de fournir le résultat de la commande ip addr show.

Merci
Cordialement

**Comment by xnae** [comment]
Bonjour,
Non, la carte est down et n'est pas configurée : il s'agit d'un poste client simple => la carte récupère une adresse ip via dhcp lorsqu'un câble est branché.

Voici le résultat demandé :
> [ip_addr_sow.txt](https://github.com/OCSInventory-NG/UnixAgent/files/551421/ip_addr_sow.txt)

Cordialement.

**Comment by fbomj** [comment]
Bonjour

La deuxième carte sera inventoriée lorsqu'elle sera configurée (adresse IP). 

Cordialement

**Comment by xnae** [comment]
Bonjour,

Pourriez-vous poursuivre le développement de l'agent Unix pour que la carte soit inventoriée même DOWN comme pour Windows (voir snapshot ci-dessous) svp ?

> ![snapshot](https://cloud.githubusercontent.com/assets/22777682/19832703/9666e020-9e2b-11e6-81c7-88edc42d1cd7.jpg)

Cordialement.

**Comment by fbomj** [comment]
Bonjour,

Quelle version de l'agent Windows permet d'inventorier toutes les cartes réseau même DOWN?
Cordialement

**Comment by xnae** [comment]
Bonjour,

La version de l'agent Windows utilisée pour l'inventaire de l'exemple ci-dessus est la 2.1.1.3.

 Cordialement.

**Comment by diodo** [comment]
Il y a quand même un problème de carte réseau sous linux lorsque la commande ip est utilisé (ce qui devrait être le cas maintenant tout le temps)

Dans le cas d'un bond, seul le bond remonte, et non les cartes réseaux associées.

ip -o link remonte bien les cartes physiques et le bond en state UP, sauf que la boucle pour récupérer les cartes réseaux se fait sur ip -o addr, et là, les cartes physiques ne remontent pas.

En revanche, le code avec ifconfig (qui n'est plus fonctionnel sur debian par exemple) remonte bien les infos des cartes, même sans les ip.

**Comment by fbomj** [comment]
C'est corrigé et ce sera bientôt publié.

Cordialement
Frank

**Comment by xnae** [comment]
Merci pour votre investissement.

Cordialement.
