### ISSUE TITLE
Network speed show wrong value -1, instead of 10G

### ISSUE THREAD

**Issue by KpuCko** [OCSInventory-NG/UnixAgent#370]
### General informations
Operating system :  Debian GNU/Linux 10 (buster)
Perl version : This is perl 5, version 32, subversion 1 (v5.32.1) built for x86_64-linux-gnu-thread-multi

### OCS Inventory informations
Unix agent version : Ocsinventory unified agent for UNIX, Linux and MacOSX (2.8.1)

### Problem's description
As mentioned in the topic, I got wrong value for this network interface, but it seems that the problem is outside of OCSInventory.
Long story short - I use Proxmox as hypervisor, I know that "VirtIO" will do best performance compared with the rest of the controllers/interfaces, there is a support from OS perspective for that as well. So I use "VirtIO" whenever possible - disk controller, video card controller, network controller and so on.

Before opening the ticket I started to get some information about the link connection and notices that, ethtool can't get the right values:

```
root@muttley.home.lan:/tmp# ethtool eth0
Settings for eth0:
        Supported ports: [ ]
        Supported link modes:   Not reported
        Supported pause frame use: No
        Supports auto-negotiation: No
        Supported FEC modes: Not reported
        Advertised link modes:  Not reported
        Advertised pause frame use: No
        Advertised auto-negotiation: No
        Advertised FEC modes: Not reported
        Speed: Unknown!
        Duplex: Unknown! (255)
        Port: Other
        PHYAD: 0
        Transceiver: internal
        Auto-negotiation: off
        Link detected: yes
root@muttley.home.lan:/tmp#
```

I'm not sure if that matters. Let me show you some additional things:

```
root@muttley.home.lan:/tmp# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.0.7  netmask 255.255.255.0  broadcast 192.168.0.255
        ether 12:34:56:0d:41:36  txqueuelen 1000  (Ethernet)
        RX packets 4444204  bytes 626953871 (597.9 MiB)
        RX errors 0  dropped 1  overruns 0  frame 0
        TX packets 2953847  bytes 2617976153 (2.4 GiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
root@muttley.home.lan:/tmp# lspci
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
00:01.0 ISA bridge: Intel Corporation 82371SB PIIX3 ISA [Natoma/Triton II]
00:01.1 IDE interface: Intel Corporation 82371SB PIIX3 IDE [Natoma/Triton II]
00:01.2 USB controller: Intel Corporation 82371SB PIIX3 USB [Natoma/Triton II] (rev 01)
00:01.3 Bridge: Intel Corporation 82371AB/EB/MB PIIX4 ACPI (rev 03)
00:02.0 VGA compatible controller: Device 1234:1111 (rev 02)
00:03.0 Unclassified device [00ff]: Red Hat, Inc Virtio memory balloon
00:08.0 Communication controller: Red Hat, Inc Virtio console
00:0a.0 SCSI storage controller: Red Hat, Inc Virtio block device
00:12.0 Ethernet controller: Red Hat, Inc Virtio network device
00:1e.0 PCI bridge: Red Hat, Inc. QEMU PCI-PCI bridge
00:1f.0 PCI bridge: Red Hat, Inc. QEMU PCI-PCI bridge
root@muttley.home.lan:/tmp#
```

I know you can't do anything about this issue, but I at least hope that you will advice me how to workaround it by supplying a value instead of -1. Let's rephrase it - is there a way to overwrite a value gathered by unix agent collector?
Thanks

**Comment by fbomj** [comment]
agent does not use ethtool command.
