### ISSUE TITLE
Missing version of OCS agent in official repository

### ISSUE THREAD

**Issue by thfiliol1** [OCSInventory-NG/UnixAgent#373]
Hello OCS Team,
I didn't found the last OCS agent (version: 2.8.1) in this repo: https://rpm.ocsinventory-ng.org/enterprise/7/x86_64/

Could you please add it ? 

Thanks in advance :)

**Comment by thfiliol1** [comment]
Do you have any information about it ?

**Comment by gillesdubois** [comment]
Hi,

The 2.9.0 is available on our repository.
Sorry we skipped the 2.8.1 on the  RPM repo.

Regards,
Gilles.

**Comment by thfiliol1** [comment]
Thank you very much @gillesdubois :)
