### ISSUE TITLE
installation ocsinventory-agent on RHEL8 - missing Perl module

### ISSUE THREAD

**Issue by christianwohlgemuth** [OCSInventory-NG/UnixAgent#374]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  RHEL 8.4
Perl version : 5.26.3

### OCS Inventory informations
Unix agent version : 2.8.0 1.el8.ocs x86_64

### Problem's description
cannot install the package ocsinventory-agent (https://rpm.ocsinventory-ng.org/enterprise/8/x86_64/ocsinventory-agent-2.8.0-1.el8.ocs.x86_64.rpm) because missing dependency perl(Data::UUID)

the package perl-Data-UUID is no longer present in the EPEL8 repository.

**Comment by christianwohlgemuth** [comment]
# yum install ocsinventory-agent
Updating Subscription Management repositories.
Unable to read consumer identity

This system is not registered with an entitlement server. You can use subscription-manager to register.

Last metadata expiration check: 1:20:05 ago on Wed 10 Nov 2021 08:20:52 AM CET.
Error:
 Problem: package ocsinventory-agent-2.8.0-1.el8.ocs.x86_64 requires perl-Ocsinventory-Agent = 2.8.0-1.el8.ocs, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides perl(Data::UUID) needed by perl-Ocsinventory-Agent-2.8.0-1.el8.ocs.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by cdabin** [comment]
Hello

package perl-Data-UUID is in the codeready-builder-for-rhel-8-x86_64-rpms repository

https://access.redhat.com/downloads/content/perl-Data-UUID/1.221-10.el8/x86_64/fd431d51/package

**Comment by christianwohlgemuth** [comment]
thanks
