### ISSUE TITLE
Ubuntu 21.10 being reported as Ubuntu 11.0

### ISSUE THREAD

**Issue by brizao** [OCSInventory-NG/UnixAgent#375]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubuntu 21.10
Perl version : perl  5.32.1-3ubuntu3

### OCS Inventory informations
Unix agent version : ocsinventory-agent 2:2.8-2

### Problem's description
I've recently installed Ubuntu 21.10 and also installed Ocs Agent from its repositories (apt-get install ocsinventory-agent). But the OS name is being sent as:

OS Name: Ubuntu 11.0
OS Version 11.0
Service pack:Ubuntu 21.10

If I execute the command: "ocsinventory-agent --debug -i --stdout|grep -i osname", it returns the following:
<OSNAME>Ubuntu 11.0</OSNAME>

Something has been changed in the newest Ubuntu.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
Fixed with #376
