### ISSUE TITLE
Unix Agent 2.8.0 | --Proxy gives error

### ISSUE THREAD

**Issue by GuilhermeKG** [OCSInventory-NG/UnixAgent#377]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubuntu 21.04
Perl version : Perl 5, version 32

### OCS Inventory informations
Unix agent version : 2.8.0

### Problem's description
Hello OCS Team,

I'm having trouble connecting to my internal OCS Server when using proxy mode. It gives me the error:
501 Protocol scheme 'connect' is not supported
Log attached.

We've always used OCS without problems, but since some recent update the issue began.
Confirmed that using the version 2.6.1 the agent runs fine.

Thank you!

Agent version 2.8.0
[ocs log.txt](https://github.com/OCSInventory-NG/UnixAgent/files/7557469/ocs.log.txt)

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
install perl LWP-Protocol-Connect

**Comment by fbomj** [comment]
As there is no answer I close the issue
