### ISSUE TITLE
Missing Debian 11 Bullseye packages from official repo

### ISSUE THREAD

**Issue by sblaisot** [OCSInventory-NG/UnixAgent#378]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations

Operating system :  Debian 11 Bullseye
Perl version : v5.32.1

### OCS Inventory informations

Unix agent version : 2.8.1

### Problem's description

[Official debian package repository](http://deb.ocsinventory-ng.org/debian/dists/) are missing packages for debian 11 bullseye. This version of debian has been published as stable on 2021/08/14

Could you please provide a debian 11 package?

Also in this repo, stable should now be debian 11 bullseye, oldstable should be debian 10 buster and debian 9 stretch should be oldoldstable.

Thanks in advance.

**Comment by gillesdubois** [comment]
Hi,

Sorry i didn't noticed your issue.
Its done.

Regards,
Gilles.
