### ISSUE TITLE
How to build UnixAgent 2.9.0 for MacOs

### ISSUE THREAD

**Issue by hans0801** [OCSInventory-NG/UnixAgent#380]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  MacOs
Perl version : 5.30

### OCS Inventory informations
Unix agent version : 2.9.0 

### Problem's description
*Describe your problem here*
Hi Team,
Anyone can help me for give me a guidance for build unixagent 2.9.0 for MacOs?
Because i saw on release page, there is no version 2.9.0 for MacOs.

Thanks
### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by charleneauger** [comment]
Hi @hans0801 ,

Unix Agent 2.9 for MacOS is being released soon.

Best regards,
Charlene Auger
