### ISSUE TITLE
SNMP XML parse error

### ISSUE THREAD

**Issue by bgoales** [OCSInventory-NG/UnixAgent#381]
### General informations
Operating system :  debain 10
Perl version : 5.28.1

### OCS Inventory informations
Unix agent version : 2.9.0
Server version : 2.9.2

### Problem's description

Hi,

I'm having a issue with the SNMP scan option since i've installed 2.9.1 server version. I've upgarded to 2.9.2 Yesterday thinking the issue was corrected but still having the same results. No SNMP Device recovered from my network scan is added to my OCS server.

-- Server and agent are one the same PC

Below the apache, agent log files and a screen of my SNMP parameters.

Thank's for Your help.

### apache log file

[Wed Dec 22 00:38:00.780622 2021] [perl:error] [pid 10153] [client 10.247.192.5:48504] \nnot well-formed (invalid token) at line 6, column 14, byte 131 at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/XML/Parser.pm line 187.\nXML::Simple called at /usr/local/share/perl/5.28.1/Apache/Ocsinventory.pm line 218.\n

### Agent Log file error
[Wed Dec 22 16:14:28 2021][info] [snmpscan] No more SNMP device to scan
[Wed Dec 22 16:14:28 2021][debug] checking XML
[Wed Dec 22 16:14:28 2021][error] Invalid XML: not well-formed (invalid token) at line 150, column 14, byte 7338 at /usr/local/lib/x86_64-linux-gnu/perl/5.28.1/XML/Parser.pm line 187.
XML::Simple called at /usr/local/share/perl/5.28.1/Ocsinventory/Agent/Network.pm line 106.
[Wed Dec 22 16:14:28 2021][error] Cannot submit XML! Abort...
[Wed Dec 22 16:14:28 2021][debug] [snmpscan] End snmp_end_handler :)

![SNMPparam](https://user-images.githubusercontent.com/96566428/147206247-85aa4da4-40dd-4faa-a244-e8f4bd547f16.png)

**Comment by wiltonsr** [comment]
This is related to #275 

Please note that, how log says, some info being inventoried is not parsable by XML. 

Since `v2.9.0` when this is detected, the agent don't send XML to server since the same error would occur there.

You could run `ocsinventory-agent --stdout > /tmp/ocs.xml 2>&1` and inspect `line 150, column 14` to know what information is causing you problems.
