### ISSUE TITLE
Agent 2.9.0 not reporting OS minor release on Debian

### ISSUE THREAD

**Issue by G-N-ius** [OCSInventory-NG/UnixAgent#382]
### General informations
Operating system :  Debian 11.2
Perl version : 5.32.1

### OCS Inventory informations
Unix agent version : OCS-NG_unified_unix_agent_v2.9.0

### Problem's description
after upgrading agent to v2.9.0 the Debian version is only reported as "11"
The 2.8.0 agent reported this as "11.2"

**Comment by fbomj** [comment]
Fix with #383

**Comment by itiser** [comment]
I've the same problem with agent v2.10.0, but only on proxmox servers (pve/pbs).

Any clue?
