### ISSUE TITLE
Virtual Box Script Returns VMs for the Root User

### ISSUE THREAD

**Issue by hamzashariq7** [OCSInventory-NG/UnixAgent#384]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubuntu (But this applies to all Operating Systems)
Perl version : 5.30.1

### OCS Inventory informations
Unix agent version : All

### Problem's description
Virtualbox stores a list of VMs separately for each user. Since the unix agent is run as root, OCS returns the list of VMs for the root user (which is often empty).

This is undesirable since the VMs the user is looking for are more likely to be installed for the current user, not root.

The code for this can be found in  Ocsinventory > Agent > Backend > Virtualisation > VirtualBox.pm

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by charleneauger** [comment]
Hi,

This bug has been fixed by #386 .

Regards,
Charlene
