### ISSUE TITLE
[MacOs X - Agent 2.9.0] Invalid XML

### ISSUE THREAD

**Issue by aramilialon** [OCSInventory-NG/UnixAgent#395]
Hi!

### General informations
Operating system :  MacOS X 12.1
Perl version : This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level

### OCS Inventory informations
Unix agent version : 2.9.0

### Problem's description
I'm trying to sync a macos device to my OCS server, but in the /var/log/ocsng.log file I find those errors:
```
[Mon Jan 24 18:49:02 2022][error] Invalid XML: not well-formed (invalid token) at line 1666, column 22, byte 46453 at /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/XML/Parser.pm line 187.
XML::Simple called at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Network.pm line 106.
[Mon Jan 24 18:49:02 2022][error] Cannot submit XML! Abort...
```
Already tried also to install some perl packages (actually all the ones listed in the README.md file) but it's still not working

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by gillesdubois** [comment]
Hi,

Could you generate a local xml of the inventory using --local=/path/to/xmlfile so we can see what is the wrong character in the xml.

Regards,
Gilles.

**Comment by holm-informatik** [comment]
The problem is in the MEMORIES - DESCTIPTION element. Cut & paste example from this section:

`    <MEMORIES>
      <CAPACITY>16384</CAPACITY>
      <CAPTION>Status: ok</CAPTION>
      <DESCRIPTION><A8> <C6>ø}<F4></DESCRIPTION>
      <NUMSLOTS>BANK 0/ChannelA-DIMM0</NUMSLOTS>
      <SERIALNUMBER>93B3E7D6</SERIALNUMBER>
      <SPEED>2667 MHz</SPEED>
      <TYPE>DDR4</TYPE>
    </MEMORIES>
    <MEMORIES>
      <CAPACITY>empty</CAPACITY>
      <CAPTION>Status: empty</CAPTION>
      <DESCRIPTION>empty</DESCRIPTION>
      <NUMSLOTS>BANK 1/ChannelA-DIMM1</NUMSLOTS>
      <SERIALNUMBER>empty</SERIALNUMBER>
      <SPEED>empty</SPEED>
      <TYPE>empty</TYPE>
    </MEMORIES>
    <MEMORIES>
      <CAPACITY>16384</CAPACITY>
      <CAPTION>Status: ok</CAPTION>
      <DESCRIPTION><A8> <C6>ø}<F4></DESCRIPTION>
      <NUMSLOTS>BANK 2/ChannelB-DIMM0</NUMSLOTS>
      <SERIALNUMBER>93B3E99D</SERIALNUMBER>
      <SPEED>2667 MHz</SPEED>
      <TYPE>DDR4</TYPE>
    </MEMORIES>
    <MEMORIES>
      <CAPACITY>empty</CAPACITY>
      <CAPTION>Status: empty</CAPTION>
      <DESCRIPTION>empty</DESCRIPTION>
      <NUMSLOTS>BANK 3/ChannelB-DIMM1</NUMSLOTS>
      <SERIALNUMBER>empty</SERIALNUMBER>
      <SPEED>empty</SPEED>
      <TYPE>empty</TYPE>
    </MEMORIES>
`

**Comment by aramilialon** [comment]
Seems like that in 2.9.1 everything works, so... let's close!
