### ISSUE TITLE
VMware dmidecode memory duplication

### ISSUE THREAD

**Issue by pilch-cit** [OCSInventory-NG/UnixAgent#40]
Hello,

the memory configuration in VMware virtual machines is listed as both DMI type 6 and type 17.
As the current version of the agent checks for both types, we have a memory duplication in the inventory for all VMware virtual machines.

I don't know if there is a bare metal with both types available and if it is OK to just use one of both (first come first serve) or if it is more save to check if we are in a vm.

Attached is a example output of a vm with 1 GB of memory.
[dmidecode_output.txt](https://github.com/OCSInventory-NG/UnixAgent/files/634226/dmidecode_output.txt)

Best regards

**Comment by pilch-cit** [comment]
We found a physical machine with the same issue. Therefore we cannot just test if we are in a vm.

**Comment by fbomj** [comment]
Hi,

Your PR has been merged. 

Regards
Frank
