### ISSUE TITLE
Solaris 11  Ocsinventory-Unix-Agent-2.9.1

### ISSUE THREAD

**Issue by argj** [OCSInventory-NG/UnixAgent#402]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Solaris 11
Perl version :  This is perl 5, version 26, subversion 3 (v5.26.3) built for sun4-solaris-thread-multi-64

### OCS Inventory informations
Unix agent version : Ocsinventory-Unix-Agent-2.9.1

### Problem's description
When i execute the agent i get this error on the log file:  Cannot establish communication : 500 Internal Server Error
this only happen on Solaris 11, i found a procedure install on internet and the install works fine but i get this error

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
What is the error on server ? Look at your apache error log file

**Comment by argj** [comment]
Hi, thanks for time and help on Unix Mchine i get this:

`/usr/bin/ocsinventory-agent
Bareword found where operator expected at /opt/csw/share/perl/site_perl/Ocsinventory/Agent/Modules/SnmpScan.pm line 424, near "s/\*//gr"
Unquoted string "r" may clash with future reserved word at /opt/csw/share/perl/site_perl/Ocsinventory/Agent/Modules/SnmpScan.pm line 424.
Bareword found where operator expected at /opt/csw/share/perl/site_perl/Ocsinventory/Agent/Modules/SnmpScan.pm line 427, near "s/\*//gr"
Unquoted string "r" may clash with future reserved word at /opt/csw/share/perl/site_perl/Ocsinventory/Agent/Modules/SnmpScan.pm line 427.
Bareword found where operator expected at /opt/csw/share/perl/site_perl/Ocsinventory/Agent/Modules/SnmpScan.pm line 431, near "s/\*//gr"
Unquoted string "r" may clash with future reserved word at /opt/csw/share/perl/site_perl/Ocsinventory/Agent/Modules/SnmpScan.pm line 431.
Could not open bmc device: Resource temporarily unavailable
Unable to connect on interface bmc
cfgadm: Configuration administration not supported
Failed to connect to logical domain manager: Connection refused`

On Server LOG:
10.0.0.1 - - [28/Mar/2022:08:56:05 -0400] "POST /ocsinventory HTTP/1.1" 200 235 "-" "OCS-NG_unified_unix_agent_v2.9.1"
10.0.0.1 - - [28/Mar/2022:08:56:19 -0400] "POST /ocsinventory HTTP/1.1" 500 527 "-" "OCS-NG_unified_unix_agent_v2.9.1"

**Comment by fbomj** [comment]
perl version on the solaris ?

**Comment by argj** [comment]
This is perl 5, version 26, subversion 3 (v5.26.3) built for sun4-solaris-thread-multi-64

**Comment by fbomj** [comment]
Could you try latest version please ?

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
