### ISSUE TITLE
Malformed XML On Mac OS X 12.3.1

### ISSUE THREAD

**Issue by oraki23** [OCSInventory-NG/UnixAgent#407]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : MacOS X 12.3.1 (MacBook Pro Early 2015)
Perl version : This is perl 5, version 30, subversion 3 (v5.30.3) built for darwin-thread-multi-2level

### OCS Inventory informations
Unix agent version : 2.9.2

### Problem's description
Cannot submit XML error when running the agent.

Error:
```
[Sun May  1 14:06:35 2022][error] Invalid XML: not well-formed (invalid token) at line 1657, column 35, byte 46202 at /System/Library/Perl/Extras/5.30/darwin-thread-multi-2level/XML/Parser.pm line 187.
XML::Simple called at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Network.pm line 107.
```

Same error as these issues, however, version 2.9.2 or 2.9.1 does not seems to fix the problem for me. I'm still getting the error for the malformed XML.
https://github.com/OCSInventory-NG/UnixAgent/issues/401
https://github.com/OCSInventory-NG/UnixAgent/issues/395

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

[MacBookProAntoAvril2020-2022-04-29-14-36-10.txt](https://github.com/OCSInventory-NG/UnixAgent/files/8599458/MacBookProAntoAvril2020-2022-04-29-14-36-10.txt)

**Comment by fbomj** [comment]
Fix with #408
