### ISSUE TITLE
Public Key expired

### ISSUE THREAD

**Issue by timcanty** [OCSInventory-NG/UnixAgent#415]
### General informations
Operating system :  Ubuntu 20.04 LTS
Perl version :

### OCS Inventory informations
Unix agent version : 2.9

### Problem's description
When trying to run apt update, we are getting expired key for http://deb.ocsinventory-ng.org/ubuntu 

![image](https://user-images.githubusercontent.com/32928117/182323072-0bf19443-4a4a-4085-be5b-f58ac7154384.png)

**Comment by candyman2903** [comment]
Have the same Error:

```
W: GPG-Fehler: http://deb.ocsinventory-ng.org/ubuntu stable InRelease: Die folgenden Signaturen waren ungültig: EXPKEYSIG 8D1DA07AF0AF3862 Gilles DUBOIS <gilles.dubois@factorfx.com>
E: Das Depot »http://deb.ocsinventory-ng.org/ubuntu stable InRelease« ist nicht signiert.
N: Eine Aktualisierung von solch einem Depot kann nicht auf eine sichere Art durchgeführt werden, daher ist es standardmäßig deaktiviert.
N: Weitere Details zur Erzeugung von Paketdepots sowie zu deren Benutzerkonfiguration finden Sie in der Handbuchseite apt-secure(8).
```

**Comment by candyman2903** [comment]
Thanks for Update:

![image](https://user-images.githubusercontent.com/18519607/182839952-e8632def-978b-4b60-bf62-81e993767bbf.png)

**Comment by Lea9250** [comment]
Hi @timcanty, hi @candyman2903,

The key has been updated. You'll have to follow the process of reimporting it : https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-UNIX-agent-using-repository-on-client-computers/

Regards,
Léa

**Comment by timcanty** [comment]
thank you
