### ISSUE TITLE
lsusb.pm "unable to initialize libusb: -99"

### ISSUE THREAD

**Issue by lhchin** [OCSInventory-NG/UnixAgent#42]
a) The following module have no exception handling if VM does not setup usb on starting ocs service.
thus getting "unable to initialize libusb: -99" (lsusb.pm, usb.pm)

b) "USBDEVICES" and fields are not found to be setup in latest Server's Map.pm and Table.
common.pm (sub addUsb)

**Comment by fbomj** [comment]
Hi,

Which version of the agent are you using? 

Regards
Frank

**Comment by lhchin** [comment]
Hi, that would be v2.1.1 unix

**Comment by StCyr** [comment]
funny enough, on all our clients I can find only one reporting USBDEVICES sections and this makes our server (v2.3) error 500 :-)

**Comment by fbomj** [comment]
Hi
to lhchin : "unable to initialize libusb: -99" is a system message. The problem does not come from the agent.
usbdevices : this problem has been corrected in ocs server because the table was missing. 
So I close the issue.
Regards
Frank

**Comment by lhchin** [comment]
Hi @fbomj, there are remote agent without libusb setup in system and the agent could do a "eval try catch"  to avoid this error during startup.
