### ISSUE TITLE
Solaris - Problem in Mem.pm when set swap var.

### ISSUE THREAD

**Issue by jonathanabrantes** [OCSInventory-NG/UnixAgent#423]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Solaris 5.11
Perl version : 5.32.0

### OCS Inventory informations
Unix agent version : v2.10.0

### Problem's description
Currently we have a problem on module mem.pm(UnixAgent/tree/master/lib/Ocsinventory/Agent/Backend/OS/Solaris/Mem.pm), on the line 28 the regex that filter the command 'swap -l' isn't working well, we have 2 problems:

1-The regex filter the last data on the command, works well in other solaris versions but on 5.11 the command show a new data, "encrypted", and the regex set the data "yes" on the var $SwapFileSize. Follow example:

![Captura de tela de 2022-11-04 10-44-53](https://user-images.githubusercontent.com/54941941/199987671-6bc17e77-0e60-4f52-9ac8-c8e941339573.png)
![Captura de tela de 2022-11-04 10-45-02](https://user-images.githubusercontent.com/54941941/199988597-59fd7f26-a58b-4179-950a-18b912da2092.png)

To solve this problem, i made a new regex that filter the right data with both outputs from commands.

![Captura de tela de 2022-11-04 10-49-21](https://user-images.githubusercontent.com/54941941/199988605-0a4db3b0-48fa-46fd-8e9f-9db5db932188.png)

2- Even with the regex fixed, when the host have two different swaps the command set the last swap and send the data to the server.
To solve this problem, I initialized the variable with 0(line 17) and inside the foreach I added the filtered values to the variable that will be used in the sending(line 28)

I'll send the pull request.

**Comment by jonathanabrantes** [comment]
https://github.com/OCSInventory-NG/UnixAgent/pull/424

**Comment by fbomj** [comment]
PR merged. I'm closing the issue.
