### ISSUE TITLE
[error] Cannot establish communication : 500 Internal Server Error - ONLY FOR UNIX AGENT ON DEBIAN #410

### ISSUE THREAD

**Issue by c3ph3us** [OCSInventory-NG/UnixAgent#425]
linking from server issues as agent related (all needed data there)

https://github.com/OCSInventory-NG/OCSInventory-Server/issues/410

additional data:
[client_make.log](https://github.com/OCSInventory-NG/UnixAgent/files/9946112/client_make.log)
[client_make_install.log](https://github.com/OCSInventory-NG/UnixAgent/files/9946115/client_make_install.log)

logfile=/var/log/ocsinventory-agent.log
snmptimeout=3
snmpretry=2
tag=ocs-server
basevardir=/var/lib/ocsinventory-agent
snmp=1
server=http://10.10.0.254:8081/ocsinventory
ssl=0
debug=2
ca=/etc/ssl/certs/
nosoftware=0

[client_exec.log](https://github.com/OCSInventory-NG/UnixAgent/files/9946126/client_exec.log)

**Comment by fbomj** [comment]
which debian version?

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
