### ISSUE TITLE
Quelles version de l'agent prendre pour OSX?

### ISSUE THREAD

**Issue by thenamelessthing** [OCSInventory-NG/UnixAgent#430]
Bonjour, je remarque dans vos release que parfois c'est indiqué MAC OSX et parfois seulement unix agent. Cependant dans le descriptif c'est tout de même mentionné que c'est "compatible" avec la version XX de OS X.

Pouvez-vous m'expliquer la différence?

Est-ce qu'une version est prévu pour OSX 13.x?

Merci pour votre bon travail! ;-)

**Comment by charleneauger** [comment]
Bonjour @thenamelessthing,

Je vous avoue qu'en effet ce n'est pas très clair. 
Depuis la version 2.9.3, nous essayons de publier les versions de l'agent unix "classique" et MAC en même temps.

Comme vous pouvez le voir dans la release 2.10, vous avez l'archive pour les Linux et l'archive pour les MAC : 

```
- Ocsinventory-Unix-Agent-2.10.0.tar.gz
- Ocsinventory_Unix_Agent-2.10.0-MAC.tar.gz
``` 

Si vous avez la mention `Compatibilities for MacOS` dans la description de la release c'est que la version MAC est disponible dans les archives.

A savoir que les compatibilités que nous renseignons pour Macos sont sur la base de nos tests et des retours utilisateurs.
Rien ne vous empêche de tester la version 2.10 sur OSX 13 et de nous faire un retour potentiel sur les erreurs que vous pourriez rencontrer :-)

J'espère avoir répondu au mieux.
Cordialement,
Charlène

**Comment by thenamelessthing** [comment]
Merci pour la clarification.
