### ISSUE TITLE
can't find ocsinventory-agent in $PATH when install linux agent on RHEL8

### ISSUE THREAD

**Issue by Thananch** [OCSInventory-NG/UnixAgent#431]
I am new in OCS and first tried to install agent on RHEL8 and error with info below, please advise.

### General informations
Operating system :  RHEL8.7
Perl version : Perl 5.26.3

### OCS Inventory informations
Unix agent version : 2.10.0

### Problem's description
Setting OCS Inventory NG server address...
Looking for OCS Invetory NG Unix Unified agent installation...
sorry, can't find ocsinventory-agent in $PATH
make: *** [Makefile:1329: install] Error 1

**Comment by charleneauger** [comment]
Hi @Thananch ,

Can you tell me how you tried to install the agent (step by step) ?

Best regards,
Charlene

**Comment by charleneauger** [comment]
Hi,

Since there was no answer, I'll close this issue now.

Regards,
Charlene
