### ISSUE TITLE
MacOS Agent 2.10.0 No memory information

### ISSUE THREAD

**Issue by Seazonx** [OCSInventory-NG/UnixAgent#432]
### General informations
Operating system :  MacOS 12 and MacOS 13
Perl version :

### OCS Inventory informations
Unix agent version : 2.10.0

### Problem's description
No memory information on MacbookPro M1 2020.
It's empty in DIMM table.

And it's fine on Macbook Air 2015(Intel), everything is correct

**Comment by charleneauger** [comment]
Hi @Seazonx ,

Is the problem present on MacOS 12 AND MacOS 13 or only on MacOS 13 ?

Best regards,
Charlene

**Comment by Seazonx** [comment]
Hi @charleneauger ,

It's present on both MacOS 12 and MacOS 13, but only on M1 CPU models

**Comment by Seazonx** [comment]
I think it's something like this issue #339

**Comment by fbomj** [comment]
Try the latest release https://github.com/OCSInventory-NG/UnixAgent/releases/tag/v2.10.3-MAC
