### ISSUE TITLE
Setup TAG with Unix Agent

### ISSUE THREAD

**Issue by tovoro** [OCSInventory-NG/UnixAgent#433]
https://github.com/OCSInventory-NG/UnixAgent/issues/59

Sorry I dont know if closed issues trigger notifications. However, the issue mentioned here: https://github.com/OCSInventory-NG/UnixAgent/issues/59 still exists. Tags only get updated if the host is deleted before re-running the ocsinventory-agent. 

Does anybody have a fix for this?

**Comment by charleneauger** [comment]
Hi @tovoro ,

After check it seems that the `OCS_OPT_ACCEPT_TAG_UPDATE_FROM_CLIENT` option does not work as it should.
We have added this correction to our roadmap.

We will let you know when the fix is available :-)

Best regards,
Charlene

**Comment by tovoro** [comment]
Thank you Charlene, im happy to test if you have a fix available.

**Comment by charleneauger** [comment]
Hi @tovoro,

I made a correction on the recovery of the TAG if it is set on the command line or in the configuration file.
You can test it and give me feedback on it if you wish. :-)

Best regards,
Charlene
