### ISSUE TITLE
MacOS wrong Arch type on all machines 

### ISSUE THREAD

**Issue by PeLbmaN** [OCSInventory-NG/UnixAgent#444]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  MacOS 13.3.1
Perl version : v5.30.3

### OCS Inventory informations
Unix agent version : 2.10.1

### Problem's description
*Hey, when i run script from OCS agent i see that my Arch is x86_64. But i have macbook air m2. And this porblem only when i run script from OCS agent. This problem on all mac os machines wich i test.
*

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
Hi,

For each type of Mac you have, please run the command : sysctl -a and post the result.

Regards

**Comment by PeLbmaN** [comment]
@fbomj 
Hi,
this problem appears when you install from .pkg. Always. One time i install agent with source code, this problem was solved. How to fix this?

**Comment by fbomj** [comment]
Fix by https://github.com/OCSInventory-NG/UnixAgent/releases/tag/v2.10.3-MAC
