### ISSUE TITLE
Java software is not showing in which we mounted in /mnt

### ISSUE THREAD

**Issue by sunilkumarheterno** [OCSInventory-NG/UnixAgent#446]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  
Perl version : v5.16.3

### OCS Inventory informations
Unix agent version: 2.10.0

### Problem's description
*How to customize to search software which is mounted in mount point /mnt*

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
hi,

Could you explain your problem, plz ?

**Comment by fbomj** [comment]
Hi

Issue closed because no answer since opening.

Regards
