### ISSUE TITLE
GPG Public Key Expired

### ISSUE THREAD

**Issue by eguaj** [OCSInventory-NG/UnixAgent#447]
### General informations

Operating system :  Ubuntu 20.04

### OCS Inventory informations

Unix agent version : 2.10.0

### Problem's description

The GPG key documented in the [Wiki][1] and used for signing the DEB package repo has expired today (2023-08-04):

```
$ curl -fsSL http://deb.ocsinventory-ng.org/pubkey.gpg | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/ocs-archive-keyring.gpg
$ gpg --keyring /etc/apt/trusted.gpg.d/ocs-archive-keyring.gpg --no-default-keyring -k
/etc/apt/trusted.gpg.d/ocs-archive-keyring.gpg
----------------------------------------------
pub   rsa3072/0x8D1DA07AF0AF3862 2020-07-30 [SC] [expirée : 2023-08-04]
      Empreinte de la clef = 799E 0F4D 68A1 4A00 FD3A  CE2D 8D1D A07A F0AF 3862
uid                  [ expirée ] Gilles DUBOIS <gilles.dubois@factorfx.com>

```

### Inventory log file ( optional )

N/A

[1]: https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-UNIX-agent-using-repository-on-client-computers/

**Comment by timcanty** [comment]
Bit surprised this has been let to expire, any news when this will be replaced?

**Comment by dbrau** [comment]
+1

Please update the gpg public key. 

Thanks you in advance

**Comment by mtbadi39** [comment]
+1

Please update the gpg public key.

Thanks you in advance

**Comment by timcanty** [comment]
Any update when this might be updated?

**Comment by dbrau** [comment]
Key is already updated. Take a look here: http://deb.ocsinventory-ng.org/

After including this file on my system, the warning message disappeard.

**Comment by Lea9250** [comment]
Hi @eguaj,

Thank you for reporting it, the key was renewed. I'll close this issue now.

Best regards,
Léa
