### ISSUE TITLE
FreeBSD 13.2 with ocsinventory-agent-2.10.0,1 warning and missing hw. serialno

### ISSUE THREAD

**Issue by carlos-paniago** [OCSInventory-NG/UnixAgent#449]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  FreeBSD 
Perl version : perl5-5.34.1_3

### OCS Inventory informations
Unix agent version :  ocsinventory-agent-2.10.0,1

### Problem's description
when we execute in a cron job we receive a e-mail with: 

sysctl: unknown oid 'hw.serialno'

this sysctl doesnt exist in freebsd. a possible sugestion:
in file /usr/local/lib/perl5/site_perl/Ocsinventory/Agent/Backend/OS/BSD/CPU.pm
line 33, made this substituition

    # $serial = `sysctl -n hw.serialno`;
    $serial = `dmidecode -s system-serial-number`;

**Comment by fbomj** [comment]
Fixed with #454
