### ISSUE TITLE
ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xc400080, needed 0xf880080)

### ISSUE THREAD

**Issue by GillesRonsin** [OCSInventory-NG/UnixAgent#460]
Hi all,

*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Sonoma 14.4
Perl version : perl 5 version 34

### OCS Inventory informations
Unix agent version :  [Unix Agent 2.10.1 (Mac version)](https://github.com/OCSInventory-NG/UnixAgent/releases/tag/v2.10.1-MAC)

### Problem's description
After installation, well configured (like all other machine and another old mac) no data is transfered to ocs serveur.
admin interface is available, so connection is ok.
running in a console:

sudo /Applications/OCSNG.app/Contents/Resources/ocsinventory-agent

Password:
ListUtil.c: loadable library and perl binaries are mismatched (got handshake key 0xc400080, needed 0xf880080)

I don't know a lot about macos..
could you tell me what I have to do ? please

**Comment by cainatplugify** [comment]
I finally figured out the solution to this problem on Sonoma OSX 14.4+, and to be honest it's quite simple to fix.

you need to change the first line of the following file:
/Applications/OCSNG.app/Contents/Resources/ocsinventory-agent

the first line will have the content:
#!/usr/bin/perl

and you need to update it to:
#!/usr/bin/perl5.30

and that is it, fixed

**Comment by GillesRonsin** [comment]
Hi cainatplugify

nice. it is effectivally fixed

thank you

**Comment by GillesRonsin** [comment]
The fix forcing perl version works well
