### ISSUE TITLE
Installation link dead

### ISSUE THREAD

**Issue by nerdoc** [OCSInventory-NG/UnixAgent#468]
https://github.com/OCSInventory-NG/UnixAgent/blob/6523282691441ca7ba4dd8b03b9afc0a08dcdfff/README.md?plain=1#L9

This link is dead

**Comment by gillesdubois** [comment]
Hi,

New links are : 
https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-UNIX-agent-manually-on-client-computers/ (source install)
https://wiki.ocsinventory-ng.org/03.Basic-documentation/Setting-up-the-UNIX-agent-using-repository-on-client-computers/ (repo install)

We are going to update the readme.
Thanks for your feedback ! 

Regards,
Gilles DUBOIS.
