### ISSUE TITLE
Agent not reporting Debian OS minor release, but only on proxmox servers (pve/pbs)

### ISSUE THREAD

**Issue by itiser** [OCSInventory-NG/UnixAgent#478]
_Originally posted by @itiser in https://github.com/OCSInventory-NG/UnixAgent/issues/382#issuecomment-2255168862_

**Comment by itiser** [comment]
![image](https://github.com/user-attachments/assets/6d291be3-d427-4b01-8296-b74abed156d8)

**Comment by fbomj** [comment]
Hi,

The first three servers are at the same upgrade of debian ?

Regards

**Comment by itiser** [comment]
I re-checked it and have to mention:

The servers (first three) are ALL Proxmox VE Hosts (not VM's as I stated above).

This is the output of one of them (I think it'll be same for the others) which I have recently updated (5 min. ago) to the latest version of pve:

uname -a
Linux proxXX 6.8.12-1-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.12-1 (2024-08-05T16:17Z) x86_64 GNU/Linux

cat /etc/debian_version
12.7

OCSReports only shows Debian 12:

![grafik](https://github.com/user-attachments/assets/b6a20d6b-e48b-4a94-be97-26294a1a34fa)

**Comment by fbomj** [comment]
Hi
Fixed with #481. 

Regards
