### ISSUE TITLE
Cannot inventory when usb device plugged in linux machine.

### ISSUE THREAD

**Issue by Minovich** [OCSInventory-NG/UnixAgent#48]
PHP Warning:  mysqli_fetch_object() expects parameter 1 to be mysqli_result, boolean given in /usr/share/ocsinventory-reports/ocsreports/install.php on line 113, referer: https://ocs.andersenlab.com/ocsreports/install.php
[client 127.0.0.1:48899] PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_export/ms_csv.php on line 93, referer: https://ocs.andersenlab.com/ocsreports/?function=visu_repart_tag
 PHP Warning:  Invalid argument supplied for foreach() in /usr/share/ocsinventory-reports/ocsreports/plugins/main_sections/ms_export/ms_csv.php on line 93, referer: https://ocs.andersenlab.com/ocsreports/?function=visu_repart_tag
DBD::mysql::st execute failed: Table 'ocs_db.usbdevices' doesn't exist at /usr/local/share/perl/5.18.2/Apache/Ocsinventory/Server/Inventory/Update.pm line 171.
DBD::mysql::db DESTROY failed: MySQL server has gone away at /usr/share/perl5/Apache/DBI.pm line 212.
DBD::mysql::db DESTROY failed: MySQL server has gone away at /usr/share/perl5/Apache/DBI.pm line 212.

**Comment by StCyr** [comment]
same here: https://github.com/OCSInventory-NG/OCSInventory-Server/issues/40

**Comment by StCyr** [comment]
et effectivement je vois pas de table `usbdevices` dans ma db ocsweb

**Comment by gillesdubois** [comment]
Hi,

I'm closing this issue.
All the fix bug for this one will be done here : https://github.com/OCSInventory-NG/OCSInventory-Server/issues/40

Regards,
Gilles Dubois.
