### ISSUE TITLE
agent fails on macos 15 sequoia 

### ISSUE THREAD

**Issue by gnafou** [OCSInventory-NG/UnixAgent#484]
Hello

I tried to install ocsinventory agent on mac  osx15 ( sequoia )  ; a newly bought mac 
The installer works
but the client does not work if i double click on it as stated below, perl version 5.30 is not available on sequoia

 

### General informations
Operating system :  macOSX15 sequoia 
Perl version :  

### OCS Inventory informations
Unix agent version :   [Unix Agent 2.10.2 (Mac version)]

### Problem's description
The installer fails.  ( i ll be a bit more specific if i can ) 

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by MikaelUrankar** [comment]
The installer works for me but the application doesn't:
```/Applications/OCSNG.app/Contents/Resources/ocsinventory-agent 
/Applications/OCSNG.app/Contents/Resources/ocsinventory-agent: Command not found.
```
perl was updated to 5.34 and the shebang line of ocsinventory-agent is hardcoded to 5.30.

**Comment by gnafou** [comment]
yes sorry, i have just retried ; installer work, but double clicking fails ; and yes , only perl5.34 is availble

**Comment by GillesRonsin** [comment]
Same here.
its seems a not compliant List::Utils (or something like this) but I don't know how update

**Comment by MikaelUrankar** [comment]
You'll have to rebuild it or wait for the ocs dev to release a new version.
I've rebuilt it and it seems to work.

**Comment by gnafou** [comment]
Hello tanks for the beta package 

The mac had the [Unix Agent 2.10.2 (Mac version)](https://github.com/OCSInventory-NG/UnixAgent/releases/tag/v2.10.2-MAC) previously installed but not working 

I upgraded the mac to sequoia 15.0.1 ; 

I ran the 2.10.3 @Lea9250  proposed 

The installer ran not problem ( but did not ask  the usual questions )

The file /etc/ocsinventory-agent/ocsinventory-agent.cfg was unaltered 

clicking on the OCSNG app icon created a report that was successfully sent to the server 

Thanks ;-)

Fred

**Comment by wastez** [comment]
@Lea9250 
Your installer ist working as it should on macos 15.0.1.

I don't have problems with the  /etc/ocsinventory-agent/ocsinventory-agent.cfg as @gnafou suggested, it was configured as it should.

Everything is fine here.

**Comment by Lea9250** [comment]
Hi all,

Version 2.10.3 has been released for macOS 15 compatibility. I'll close this issue, but please feel free to open a new one if you encounter any issues with the new release.

Many thanks to @wastez and @gnafou for testing the new package :)

Best regards,
Léa
