### ISSUE TITLE
Problem with inventory send SNMP ( Unix Agent )

### ISSUE THREAD

**Issue by BEAR19931** [OCSInventory-NG/UnixAgent#487]
Operating system :  Ubuntu 24.04.1 LTS
Unix agent version : 2.10.2
OCS Server: 2.12.2

Good morning, when I ran the scan on the Linux system for the second time, sending the XML file containing the devices found with the snmp scan, the communication times out with error 500.

The strange thing is that if I restart Apache on the OCS server and run the scan again it works but then as described before, the second time it doesn't

I attach problem:

![Error500](https://github.com/user-attachments/assets/90d18fbf-9057-4d0c-9aa8-167d9ac32e3b)

Thank you

**Comment by Lea9250** [comment]
Hi @BEAR19931 

Could you provide the server configuration for SNMP? Is the OCS_FILES_OVERWRITE option enabled?

Regards,
Léa
