### ISSUE TITLE
dmidecode in Memory.pm

### ISSUE THREAD

**Issue by erzgebirgler** [OCSInventory-NG/UnixAgent#5]
Hi,

  I have a issue with a server with 32 GB RAM modules. dmidecode in
  Agent/Backend/OS/Generic/Dmidecode/Memory.pm does not differ by MB or
  GB.

  dmidecode Example:

  Handle 0x1103, DMI type 17, 28 bytes
  Memory Device
          Array Handle: 0x1000
          Error Information Handle: Not Provided
          Total Width: 72 bits
          Data Width: 64 bits
          Size: 16384 MB
          Form Factor: FB-DIMM
          Set: 4
          Locator: PROC 1 DIMM 4A
          Bank Locator: Not Specified
          Type: DDR3
          ...

  Handle 0x1102, DMI type 17, 34 bytes
  Memory Device
          Array Handle: 0x1000
          Error Information Handle: Not Provided
          Total Width: 72 bits
          Data Width: 64 bits
          Size: 32 GB
          Form Factor: DIMM
          Set: 1
          Locator: DIMM_A3
          Bank Locator: Not Specified
          Type: DDR3
          ...

**Comment by fbomj** [comment]
Hi,

Bug corrected.

Regards
