### ISSUE TITLE
command "strings" not available

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/UnixAgent#51]
package Ocsinventory::Agent::Backend::OS::MacOS::Video rely on the "strings" command (at line 34) though this command is only available when xcode is installed.

So, when you run the UnixAgent on Mac OSX where Xcode isn't installed, you get the following error:

```
The "strings" command requires the command line developer tools. Would you like to install the tools now?
Choose Install to continue. Choose Get Xcode to install xcode and the command line developer tools from the App Store.
```

**Comment by StCyr** [comment]
Peut-être qu'il serait plus opportun d'utiliser le module `Parse::EDID` (http://search.cpan.org/~grousse/Parse-EDID-1.0.6/lib/Parse/EDID.pm) pour décoder la sortie de `ioreg`

**Comment by fbomj** [comment]
C'est prévu d'utiliser ce module pour traiter les remontées d'écrans dans l'agent Unix en complément/remplacement de la commande monitor-edid et donc traiter la sortie de la commande ioreg pour Mac OSX.
