### ISSUE TITLE
lspci: Unable to load libkmod resources: error -12

### ISSUE THREAD

**Issue by scifire91** [OCSInventory-NG/UnixAgent#53]
Hey,

i installed the agent in the OCS Server which works. Also inventory work fine so far but everytime i do an inventory i get an error "lspci: Unable to load libkmod resources: error -12".
Inventory is transmittet and i didn´t found any missing data.

you now how to solve this error? 

Server is a Ubuntu 16.04 and OCS is 2.3 on erver and agent.

PHP    7.0.13-0ubuntu0.16.04.1 (apache2handler)
WebServer    Apache/2.4.18 (Ubuntu)
DatabaseServer   (Ubuntu) version 5.7.17-0ubuntu0.16.04.1
OCS Version     2.3

**Comment by fbomj** [comment]
Hi,

Have you the same error when you launch "lspci -vvv" command directly from command line?

Regards

**Comment by scifire91** [comment]
Yes 
`[10:07]root@rmvm052:/etc/ocsinventory-agent# lspci -vvv
00:00.0 Host bridge: Intel Corporation 440FX - 82441FX PMC [Natoma] (rev 02)
        Subsystem: Red Hat, Inc Qemu virtual machine
        Control: I/O+ Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx-
        Status: Cap- 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
lspci: Unable to load libkmod resources: error -12
`

**Comment by fbomj** [comment]
Hi,
The problem is with your command but not with the agent.
Regards
