### ISSUE TITLE
[Agent 2.3.0] SNMP Error from If_Mib.pm

### ISSUE THREAD

**Issue by tsmr** [OCSInventory-NG/UnixAgent#55]
### General informations
Operating system :  Debian Jessie (8.7)
Perl version : 5.20.2

### OCS Inventory informations
Unix agent version :  2.3.0

### Problem's description

Error into log file : 
Failed to load Ocsinventory::Agent::Modules::Snmp::If_Mib: Missing right curly or square bracket at /usr/local/share/perl/5.20.2/Ocsinventory/Agent/Modules/Snmp/If_Mib.pm line 178, at end of line
syntax error at /usr/local/share/perl/5.20.2/Ocsinventory/Agent/Modules/Snmp/If_Mib.pm line 178, at EOF
Compilation failed in require at (eval 244) line 2.

Indeed it misses a bracket at the end of this file

**Comment by fbomj** [comment]
Hi Tsmr,

Thanks for your contribution. File updated.
Regards
Frank
