### ISSUE TITLE
ssl=1 enforces agent to use client's certificate.

### ISSUE THREAD

**Issue by mateusz-gozdek-sociomantic** [OCSInventory-NG/UnixAgent#56]
### General informations
Operating system :  Ubuntu 16.04
Perl version : v5.22.1

### OCS Inventory informations
Unix agent version : 2.3

### Problem's description
`ssl=1` config options enforces agent to use SSL client certificate. If you want to use HTTP basic authentication over HTTPS connection, without SSL client certificate, you have to set `ssl` option to `0`.

If you don't have `cacert.pem` file, agent is printing following error:
```
[Wed Feb  8 12:47:11 2017][error] Cannot establish communication : 500 SSL_ca_file /var/lib/ocsinventory-agent/https:__inventory.local_ocsinventory/cacert.pem can't be used: No such file or directory
```

This creates a security problem, because `ssl=0` skips SSL server certificate checking.

### Proposed solution
Extend `ssl` and `ca` options to options wildly used in other software which is using SSL (X.509 in general) certificates.

Config options which should be exposed:
`ssl_verify_peer` - to set up the level of verification.
`ssl_ca_cert` - to be able to use self-signed certificate with local CA certificate.
`ssl_client_cert` - to specify client certificate used for authentication
`ssl_client_key` - optional, if client certificate uses key file (recommended)

Also, I think that setting `ssl=0` should't be used with `server` option using HTTPS protocol.

**Comment by mateusz-gozdek-sociomantic** [comment]
Update:
Looks like I missunderstood `ca` option. It looks like instead of some deeper changes, the fix would be to just use system's installed CA chain if `ca` parameter is not defined and cacert.pem` file per server is not defined instead of throwing the error.

However, options I described can be used to add SSL client certificate authentication, which can be nice alternative for HTTP Basic authentication.

**Comment by fbomj** [comment]
Hi,
Sorry for the delayed answer. We won't be able to use self signed certificates and no ssl inventory with your proposition but we want to continue with these two functionalities.

Regards
Frank
