### ISSUE TITLE
Version 2.3 for OSX

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [OCSInventory-NG/UnixAgent#57]
### General informations
Operating system :  OSX 10.11 and up
Perl version : 5.18

### OCS Inventory informations
Unix agent version : none

### Problem's description
No agent 2.3 for OSX. I have seen v 2.1.1 packaged for OSX. Can we get 2.3 packaged and available on github too?

**Comment by gillesdubois** [comment]
Hi @phillip-white-sociomantic,

Sorry for the delay. The next version of the Unix agent will package a Mac version.
See : https://github.com/OCSInventory-NG/UnixAgent/pull/49

Regards,
Gilles Dubois.
