### ISSUE TITLE
Setup TAG with Unix Agent

### ISSUE THREAD

**Issue by totorux** [OCSInventory-NG/UnixAgent#59]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Debian jessie
Perl version : v5.20.2

### OCS Inventory informations
Unix agent version : OCS-NG_unified_unix_agent_v2.3

### Problem's description
When I try to update my tag with: 
/usr/local/bin/ocsinventory-agent --tag=TOTO
The tag is not updated.
In /etc/apache2/conf-enabled/z-ocsinventory-server.conf OCS_OPT_ACCEPT_TAG_UPDATE_FROM_CLIENT is setup to 1 and apache have bin allready restarted.

### Inventory log file ( optional )
[Tue Mar  7 13:45:25 2017][debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.3
[Tue Mar  7 13:45:25 2017][debug] Log system initialised (File)
[Tue Mar  7 13:45:25 2017][debug] --scan-homedirs missing. Don't scan user directories
[Tue Mar  7 13:45:25 2017][debug] Accountinfo file: /var/lib/ocsinventory-agent/https:__ocsinv.somtest.tld_ocsinventory/ocsinv.adm
[Tue Mar  7 13:45:25 2017][debug] A TAG seems to already exist in the ocsinv.adm file. The -t parameter will be ignored. Don't forget that the TAG value will be ignored by the server unless it has OCS_OPT_ACCEPT_TAG_UPDATE_FROM_CLIENT=1.
[Tue Mar  7 13:45:25 2017][debug] OCS Agent initialised

**Comment by fbomj** [comment]
Hi,
Did you use --force option to force inventory with new tag?
Regards
Frank

**Comment by totorux** [comment]
Hi,
Yes I already try, but no change.
Regards

**Comment by piozylka** [comment]
same problem here, any chances to fix this ?

**Comment by fbomj** [comment]
If you want to change the tag you have two possibilties : 
- edit  the config file "/etc/ocsinventory-agent/ocsinventory-agent.cfg", change "tag=" value and set the option OCS_OPT_ACCEPT_TAG_UPDATE_FROM_CLIENT  to 1 in the z-ocsinventry-server.conf file 
- change the tag throught the web interface. 

If you want to set the tag you have two possibilities : 
- use the line command option "-t"  to set the tag if the tag is not written in the config file and  OCS_OPT_ACCEPT_TAG_UPDATE_FROM_CLIENT is set to 1 in the z-ocsinventory-server.conf file. 
- set the tag throught the web interface

For the others cases this is not possible.

Regards
Frank

**Comment by tovoro** [comment]
This issue still exists and I dont really know why its closed. 

The tags dont get written into the inventory, even if the value is empty before running the agent.
