### ISSUE TITLE
functions can_run, can_load, can_read

### ISSUE THREAD

**Issue by lhchin** [OCSInventory-NG/UnixAgent#60]
### OCS Inventory informations
Unix agent version :  2.3

### Problem's description
With relation to the following change, Unix agent 2.3 modules should also be updated as below
https://github.com/OCSInventory-NG/UnixAgent/commit/fe049ff4f9bcac55a999585c42784d1b6501c862
**$common->can_run()
$common->can_read()
$common->can_load()**

[debug] runWithTimeout(): unexpected error: Undefined subroutine &Ocsinventory::Agent::Backend::OS::Solaris::Drives::can_run called at /usr/local/inventory/lib/perl5/site_perl/5.12.2/Ocsinventory/Agent/Backend/OS/Solaris/Drives.pm line 12.
[debug] Ocsinventory::Agent::Backend::OS::Solaris::Drives ignored

### Example of modules  affected
Ocsinventory\Agent\Backend\OS\Solaris\CPU.pm
	Line 38:   if ( $OSLevel =~ /5.8/ || !can_run("zoneadm")){
Ocsinventory\Agent\Backend\OS\Linux\Domains.pm 
	Line 9:     return 1 if @domain || can_read ("/etc/resolv.conf");
Ocsinventory\Agent\Backend\OS\Solaris\Drives.pm
	Line 12: sub check { can_run ("df") }
Ocsinventory\Agent\Backend\OS\AIX\Videos.pm
	Line 7: can_run("lsdev")
Ocsinventory\Agent\Backend\OS\MacOS\Mem.pm
	Line 6:     return (undef) unless can_load("Mac::SysProfile");
	Line 551:     # if (can_run("smartctl")){

**Comment by fbomj** [comment]
Hi,
Thanks for your contribution. 
Files have been updated.
Regards
Frank

**Comment by lhchin** [comment]
@fbomj 

The following code missing the shift in $params to work.

Ocsinventory\Agent\Backend\OS\Solaris\Drives.pm

**my $params = shift;
my $common = $params->{common};
$common->can_run();**
