### ISSUE TITLE
Bash sript and exit code / ERR_EXIT_CODE

### ISSUE THREAD

**Issue by totorux** [OCSInventory-NG/UnixAgent#63]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Debian jessie
Perl version : v5.20.2

### OCS Inventory informations
Unix agent version : OCS-NG_unified_unix_agent_v2.3

### Problem's description
When I try to teledeploy a bash script like:
```
#! /bin/bash
exit 17
```
In OCS inventory I see : SUCCESS_4352 and no ERR_EXIT_CODE_17 like should have.
In agent log I see:
[download] Sending message for 1489074110, code=SUCCESS_4352.

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by fbomj** [comment]
Hi,
Which method do you use?
Regards
Frank

**Comment by totorux** [comment]
Hi,
I use "Launch" method to execute my script.
Regards

**Comment by dotspencer** [comment]
What's interesting is that `17 * 256 = 4352`

I came across this page looking for why bash was reporting incorrect exit codes then I realized that they were always just multiplied by 256 for some reason.

**Comment by fbomj** [comment]
Hi,
Thanks for your info and return. It's now corrected. 
Regards
Frank
