### ISSUE TITLE
OS version number missing

### ISSUE THREAD

**Issue by nerijus** [OCSInventory-NG/UnixAgent#64]
If the older OCS-NG_unified_unix_agent_v2.1.1 is used, then OS is displayed as "CentOS Linux release 7.3.1611 (Core)".
If the newest OCS-NG_unified_unix_agent_v2.3 is used, then OS is displayed as "CentOS".
Why is it so?

**Comment by nerijus** [comment]
If I add column "OS Version", then "7.3.1611" is shown in it, but it would be nice to display the version as the earlier agent did, because now it is even impossible to see if it is CentOS 6 or 7 without that additional column, while Windows versions are displayed.

**Comment by nerijus** [comment]
I found the issue which changed it - https://bugs.launchpad.net/ocsinventory-unix-agent/+bug/1405167
Trying to ping @derjoern, not sure if it is the same person.

**Comment by derjoern** [comment]
My motivation for the change is described in the link you mentioned and the representation of OS name and versioning is still correct (from my point of view) since it represents the output of 'lsb_release -a' which is supported on all major linux distributions.

In this context your example of "OS Version" and "7.3.1611" is not feasible since the OS Version would be 7.3 and 1611 would be a release number within this release.

Another minor point of my motivation was the clearing up of the OS statistics in OCS. Now I have a reasonable pie chart of OS names. Before it was scattered with dozens with a weird combination of os names and versions.

**Comment by kapouik** [comment]
From my point of view, the real bug is : Why the windows version are displayed ?

The OS is Centos or Windows or Debian and there is no logic to put version anywhere else than in OS version.

**Comment by derjoern** [comment]
Could you please explain what do you mean with 'Why the windows version are displayed ?' 

My change has taken place in LSB.pm with is only triggered if a Linux is detected by the OCS client. IIRC the unified unix agent has no modules for detection of Windows Systems so I don't see if we are talking about a real bug or the presentation of collected data.

**Comment by kapouik** [comment]
The bug is not in your Patch : the bug is in the windows agent that not read correctly OS and OS Version :)

**Comment by derjoern** [comment]
Yes, it would be nice if the conventions and therefore the presentation of os name and version for linux and windows would be the same.

**Comment by nerijus** [comment]
For me it is better if the version is displayed along with OS name, so I made this patch:
```
diff -ur LSB.pm.orig LSB.pm
--- LSB.pm.orig      2017-01-12 12:58:51.000000000 +0200
+++ LSB.pm   2017-04-05 01:39:03.175708331 +0300
@@ -11,21 +11,20 @@
     my $common = $params->{common};

     my $release;
-    foreach (`lsb_release -i`) {
-        $release = $1 if /Distributor\sID:\s+(.+)/;
-    }
+    chomp($release =`lsb_release -is`);

     my $OSversion;
-    foreach (`lsb_release -r`){
-        $osversion = $1 if /Release:\s+(.+)/;
-    }
+    chomp($OSversion =`lsb_release -rs`);

+    $release .= " ";
+    $release .= $OSversion;
+
     my $OSComment;
     chomp($OSComment =`uname -v`);

     $common->setHardware({
         OSNAME => $release,
-        OSVERSION => $osversion,
+        OSVERSION => $OSversion,
         OSCOMMENTS => "$OSComment"
     });
 }
```
Now it is displayed so:
Operating system: CentOS 7.3.1611
OS Version: 7.3.1611

**Comment by nerijus** [comment]
I would call Operating System (for example) Windows XP, Windows 7, CentOS 7.3, not Windows or CentOS. Windows or CentOS is OS family name.
With my patch it is almost correct, except CentOS is displayed as 7.3.1611 instead of 7.3, but IMHO it is a minor thing.

**Comment by nerijus** [comment]
> From my point of view, the real bug is : Why the windows version are displayed ?
Please see https://en.wikipedia.org/wiki/Microsoft_Windows - "Microsoft Windows (or simply Windows) is a metafamily of graphical operating systems". The actual OS names are Windows XP, Windows 7, etc.

**Comment by nerijus** [comment]
Why it has been closed? IMHO the bug is not resolved. I will create a PR.

**Comment by fbomj** [comment]
Closed because bug is resolved.
