### ISSUE TITLE
Unsuccessful stat on filename containing newline at... Common.pm Backend.pm

### ISSUE THREAD

**Issue by lhchin** [OCSInventory-NG/UnixAgent#68]
### OCS Inventory informations
Unix agent version :  2.3

### Problem's description
For both module, recommend to add perl regex to remove extra CR LF after chomp of the output. 

**$binpath =~ s/\R//g;**

Unsuccessful stat on filename containing newline at .../Ocsinventory/Agent/Common.pm line 1090
Unsuccessful stat on filename containing newline at .../Ocsinventory/Agent/Backend.pm line 33.

        can_run => sub {
            my $binary = shift;
    
            my $calling_namespace = caller(0);
            chomp(my $binpath=`which $binary 2>/dev/null`);
            $binpath =~ s/\R//g;
            return unless -x $binpath;
            $self->{logger}->debug(" - $binary found");
            1
        },

**Comment by fbomj** [comment]
Hi,

Can't reproduce it.
Regards
Frank
