### ISSUE TITLE
Unix agent for Mac - Apple mac address not reported

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [OCSInventory-NG/UnixAgent#73]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  OSX 10.12
Perl version : na

### OCS Inventory informations
Unix agent version : 2.1.1

### Problem's description
When an Apple Macbook is connected to an Apple screen it gets an additional Ethernet adapter added. This adapter is not showing up in the inventory. Only the macbook's Ethernet and WiFi Mac addresses are there. Not the one from the Apple screen.

Does anyone have the same issue?

### Inventory log file ( optional )
*Use github cloud or trusted upload website*

**Comment by MikaelUrankar** [comment]
Same here, any patches I can test?
