### ISSUE TITLE
UnixAgent 2.0.5 can't download packages from a 2.3.1 OcsInventory server

### ISSUE THREAD

**Issue by StCyr** [OCSInventory-NG/UnixAgent#74]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system :  Ubuntu 16.04.2
Perl version : 5.22.1-9

### OCS Inventory informations
Unix agent version : 2.0.5-1

### Problem's description
None of my ubuntu servers can download packages info files: Server answers with HTTP result 400 "Bad request"

### Workaround
Change line ```my $http_request = "GET $server_dir".$fileid."/info HTTP/1.0\n\n";``` to ```my $http_request = "GET $server_dir".$fileid."/info HTTP/1.1\r\nHost: acme.org\r\nUser-Agent: OCS-NG\r\nAccept: */*\r\n\r\n";```

**Comment by StCyr** [comment]
It seems it has something to do with my apache configuration: When activating debug log I find this:

```
[Wed Aug 23 10:54:29.942670 2017] [ssl:debug] [pid 8544] ssl_engine_kernel.c(2096): [client 10.8.0.41:43980] AH02043: SSL virtual host for servername acme.org found
[Wed Aug 23 10:54:29.942679 2017] [core:debug] [pid 8544] protocol.c(2208): [client 10.8.0.41:43980] select protocol from http/1.0,http/1.1, choices=http/1.1 for server acme.org
[Wed Aug 23 10:54:29.942684 2017] [core:debug] [pid 8544] protocol.c(2253): [client 10.8.0.41:43980] select protocol, proposals=http/1.1 preferences=http/1.0,http/1.1 configured=http/1.0,http/1.1
[Wed Aug 23 10:54:29.942696 2017] [core:debug] [pid 8544] protocol.c(2270): [client 10.8.0.41:43980] selected protocol=http/1.1
[Wed Aug 23 10:54:29.942700 2017] [ssl:debug] [pid 8544] ssl_engine_kernel.c(2096): [client 10.8.0.41:43980] AH02043: SSL virtual host for servername acme.org found
[Wed Aug 23 10:54:29.995937 2017] [ssl:debug] [pid 8544] ssl_engine_kernel.c(2023): [client 10.8.0.41:43980] AH02041: Protocol: TLSv1.2, Cipher: ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits)
[Wed Aug 23 10:54:29.996044 2017] [core:debug] [pid 8544] protocol.c(1382): [client 10.8.0.41:43980] AH00569: client sent HTTP/1.1 request without hostname (see RFC2616 section 14.23): /download/1503412889/info
```

So, tough the Download module sends a valid HTTP/1.0 request, my apache server insists to interpret it as a HTTP/1.1 request which is invalid because it is missing the "Host:" header.

Though I will probably be able to fix this issue with a better apache configuration it would be good to have the Download module use HTTP/1.1 requests.

**Comment by StCyr** [comment]
Well, despite all my efforts I can't get my apache server to support HTTP/1.0 requests.

Neither did I succeed yet to make it use its headers module to add a Host header to all incoming requests

**Comment by hschletz** [comment]
2.0.5 is severely outdated and has a lot of issues. Consider using the latest version (not available as an official Ubuntu package) where this particular code section has already been rewritten. I have not tested downloads with that version, but the code now uses a proper HTTP library instead of a hand-crafted request.

**Comment by StCyr** [comment]
Hi @hschletz, thanks for your reply.

Indeed, I've packaged ocsinventory-agent 2.3.1, and I'm busy installing it on all my linux servers.

I'm also trying to reach the debian maintainer to get it uploaded to their repo.

**Comment by fbomj** [comment]
Hi,
Version too old. This correction will be not made on this version.
Regards
Frank
