### ISSUE TITLE
Don't use "route" tool if "ip" is available

### ISSUE THREAD

**Issue by hschletz** [OCSInventory-NG/UnixAgent#76]
### General informations
Operating system :  Linux
Perl version : -

### OCS Inventory informations
Unix agent version : latest master

### Problem's description
The Linux backend uses the "route" tool from the outdated net-tools package to gather certain network information. It already checks for the "ip" tool and, if found, uses it in favor of the "ifconfig" tool from the same package, but it still relies on "route". If "ip" is available, "ip route" should be used instead to make it work on systems without the net-tools package.

**Comment by jocelynthode** [comment]
Yes just encountered this problem on a Debian 9 install that did not have net-tools but had access to ip. The ocs agent could not retrieve the ip address because of this.

**Comment by fbomj** [comment]
This is corrected and will be published soon

Regards
Frank

**Comment by nwildner** [comment]
I know that this sound silly, but anyone wants a workaround to this, just use `ifconfig` that comes with `busybox` package

    mv /sbin/ifconfig /sbin/ifconfig_net-tools_bkp
    ln -d /bin/busybox /sbin/ifconfig

It seems that this has to do with the way busybox's `ifconfig` displays the output(a old fashion way), that works with OCS:

    root@host:/tmp# ifconfig eth0
    eth0      Link encap:Ethernet  HWaddr 00:50:56:xx:xx:xx
              inet addr:10.3.x.x  Bcast:10.3.x.x  Mask:255.255.255.0
              inet6 addr: fe80::250:56ff:fe8d:3b56/64 Scope:Link
              UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
              RX packets:1636 errors:0 dropped:0 overruns:0 frame:0
              TX packets:342 errors:0 dropped:0 overruns:0 carrier:0
              collisions:0 txqueuelen:1000
              RX bytes:146806 (143.3 KiB)  TX bytes:67271 (65.6 KiB)

    root@host:/tmp# /sbin/ifconfig.net_tools eth0
    eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
            inet 10.3.x.x  netmask 255.255.255.0  broadcast 10.3.x.x
            inet6 fe80::250:56ff:fe8d:3b56  prefixlen 64  scopeid 0x20<link>
            ether 00:50:56:xx:xx:xx  txqueuelen 1000  (Ethernet)
            RX packets 1742  bytes 156526 (152.8 KiB)
            RX errors 0  dropped 0  overruns 0  frame 0
            TX packets 391  bytes 72601 (70.8 KiB)
            TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

I think the impact of this solution is low, since, OCSAgent seems to be the only software that insists on using `ifconfig` to retrieve network information. After years of warnings about it's deprecation, we can only hope OCS starts using `iproute2` instead...

**Comment by fbomj** [comment]
We continue to use ifconfig for compatibility with older linux but by default the ip command is used first.

Regards
Frank

**Comment by nwildner** [comment]
Hi Frank

It's interesting to document that behavior and my workaround, cause we have two situations where this could be a problem even with OCS 2.3 probing `ip` commands(and i faced both):

- New distributions that still create packages with old versions of `ocsinventory-agent`, like Debian 9( still uses 2.0.5)
- Minimal distributions that don't use(neither have as package) `iproute2` but uses the latest `ifconfig` 

For sure I could compile 2.3, but i don't have that much of space to use `cpan` and download the dependencies on my i386 thinclient project with 500MB of disk :)
