### ISSUE TITLE
Unable to find devices - AIX 7.1 / OCS Agent 2.3

### ISSUE THREAD

**Issue by n0F34tur3** [OCSInventory-NG/UnixAgent#77]
### **General informations**
Operating system : AIX 7.1
Perl version : 5.10.1.250

### **OCS Inventory informations**
Unix agent version : 2.3

### **Problem's description**
Hi,

We encounter an issue with OCS Unix agent concerning the networks and disks informations.

Below the related log :
-------------8<------------------------------------------
0516-306 : Unable to find 4 in the Device
        Configuration Database.
0516-306 : Unable to find 3 in the Device
        Configuration Database.
0516-306 : Unable to find 4 in the Device
        Configuration Database.
0516-306 : Unable to find 4 in the Device
        Configuration Database.
0516-306 lslv: Unable to find 4 in the Device
        Configuration Database.
0516-306 lslv: Unable to find 3 in the Device
        Configuration Database.
0516-306 lslv: Unable to find 4 in the Device
        Configuration Database.
0516-306 lslv: Unable to find 4 in the Device
        Configuration Database.
0516-306 : Unable to find volume group 1 in the Device
        Configuration Database.
0516-306 : Unable to find volume group 1 in the Device
        Configuration Database.
-------------8<------------------------------------------

Can you help me to resolve this stuff ?

P.S : I can provide more logs if you need...

Regards,

Loïc BRONDIN

**Comment by fbomj** [comment]
Hi,
Please post ocsinventory-agent.log file content.
Regards
Frank

**Comment by n0F34tur3** [comment]
Hi,

Bellow the agent log :
----------------8<------------------------------------------
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory unified agent for UNIX, Linux and MacOSX 2.3
[Fri Jun 16 12:21:59 2017][debug] Log system initialised (File)
[Fri Jun 16 12:21:59 2017][debug] --scan-homedirs missing. Don't scan user directories
[Fri Jun 16 12:21:59 2017][debug] accountconfig file: `/usr/local/linkbynet/script/inventaire/http:__yes_ocsinventory/ocsinv.conf doesn't exist. I create an empty one
[Fri Jun 16 12:21:59 2017][debug] ocsinv.conf updated successfully
[Fri Jun 16 12:21:59 2017][debug] ocsinv.conf updated successfully
[Fri Jun 16 12:21:59 2017][debug] Accountinfo file: /usr/local/linkbynet/script/inventaire/http:__yes_ocsinventory/ocsinv.adm
[Fri Jun 16 12:21:59 2017][info] Accountinfo file doesn't exist. I create an empty one.
[Fri Jun 16 12:21:59 2017][debug] Invalid parameter while writing accountinfo file
[Fri Jun 16 12:21:59 2017][debug] Account info updated successfully
[Fri Jun 16 12:21:59 2017][debug] OCS Agent initialised
[Fri Jun 16 12:21:59 2017][debug] Turns hooks on for /etc/ocsinventory/modules.conf
[Fri Jun 16 12:21:59 2017][debug] Calling handlers : `start_handler'
[Fri Jun 16 12:21:59 2017][debug] Compress::Zlib is available.
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::IpDiscover ignored
[Fri Jun 16 12:21:59 2017][debug]  - lsdev found
[Fri Jun 16 12:21:59 2017][debug] runWithTimeout(): unexpected error: Can't call method "can_run" on an undefined value at /usr/opt/perl5/lib/site_perl/5.10.1/Ocsinventory/Agent/Backend/OS/AIX/Drives.pm line 7.
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::AIX::Drives ignored
[Fri Jun 16 12:21:59 2017][debug]  - ifconfig found
[Fri Jun 16 12:21:59 2017][debug]  - lspv found
[Fri Jun 16 12:21:59 2017][debug]  - lsdev found
[Fri Jun 16 12:21:59 2017][debug]  - which found
[Fri Jun 16 12:21:59 2017][debug]  - lsattr found
[Fri Jun 16 12:21:59 2017][debug]  - lsdev found
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::AIX::Networks ignored
[Fri Jun 16 12:21:59 2017][debug]  - lsdev found
[Fri Jun 16 12:21:59 2017][debug]  - lslpp found
[Fri Jun 16 12:21:59 2017][debug]  - lsdev found
[Fri Jun 16 12:21:59 2017][debug] runWithTimeout(): unexpected error: Undefined subroutine &Ocsinventory::Agent::Backend::OS::AIX::Videos::can_run called at /usr/opt/perl5/lib/site_perl/5.10.1/Ocsinventory/Agent/Backend/OS/AIX/Videos.pm
 line 7.
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::AIX::Videos ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::BSD ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Dmidecode ignored
[Fri Jun 16 12:21:59 2017][debug]  - Sys::Hostname loaded
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Ipmi ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Lspci ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Lsusb ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Packaging::BSDpkg ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Packaging::Deb ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Packaging::Gentoo ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Packaging::Pacman ignored
[Fri Jun 16 12:21:59 2017][debug]  - rpm found
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Printers::Cups ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Generic::Screen ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::HPUX ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Linux ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::MacOS ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::OS::Solaris ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Docker ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Jails ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Libvirt ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Lxc ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Parallels ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Qemu ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::SolarisZones ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::VirtualBox ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::VmWareDesktop ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::VmWareESX ignored
[Fri Jun 16 12:21:59 2017][debug] Ocsinventory::Agent::Backend::Virtualization::VmWareWorkstation ignored
[Fri Jun 16 12:22:00 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Vmsystem ignored
[Fri Jun 16 12:22:00 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Xen::XL ignored
[Fri Jun 16 12:22:00 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Vmsystem ignored
[Fri Jun 16 12:22:00 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Xen::XL ignored
[Fri Jun 16 12:22:00 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Xen::XM ignored
[Fri Jun 16 12:22:00 2017][debug] Ocsinventory::Agent::Backend::Virtualization::XenCitrixServer ignored
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::AccessLog
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::DeviceID
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::CPU
[Fri Jun 16 12:22:00 2017][debug] PROCESSORN, PROCESSORS and PROCESSORT shouldn't be set directly anymore. Please use addCPU() method instead.
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Controller
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Domains
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Hardware
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::IPv4
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::LVM
[Fri Jun 16 12:22:00 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Mem
[Fri Jun 16 12:22:01 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Memory
[Fri Jun 16 12:22:01 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Modems
[Fri Jun 16 12:22:01 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Slots
[Fri Jun 16 12:22:01 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Software
[Fri Jun 16 12:22:01 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Sounds
[Fri Jun 16 12:22:01 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Storages
[Fri Jun 16 12:22:03 2017][debug] Running Ocsinventory::Agent::Backend::OS::AIX::Users
[Fri Jun 16 12:22:03 2017][debug] USERID shouldn't be set directly anymore. Please use addCPU() method instead.
[Fri Jun 16 12:22:03 2017][debug] Running Ocsinventory::Agent::Backend::OS::Generic
[Fri Jun 16 12:22:03 2017][debug] Running Ocsinventory::Agent::Backend::OS::Generic::Hostname
[Fri Jun 16 12:22:03 2017][debug]  - Sys::Hostname loaded
[Fri Jun 16 12:22:03 2017][debug] Running Ocsinventory::Agent::Backend::OS::Generic::Packaging
[Fri Jun 16 12:22:03 2017][debug] Running Ocsinventory::Agent::Backend::OS::Generic::Packaging::ByHand
[Fri Jun 16 12:22:03 2017][debug] Running Ocsinventory::Agent::Backend::OS::Generic::Packaging::RPM
[Fri Jun 16 12:22:03 2017][debug] Running Ocsinventory::Agent::Backend::OS::Generic::Users
[Fri Jun 16 12:22:03 2017][debug] Running Ocsinventory::Agent::Backend::Virtualization::Xen
[Fri Jun 16 12:22:03 2017][debug] Ocsinventory::Agent::Backend::Virtualization::Xen has no run() function -> ignored
[Fri Jun 16 12:22:03 2017][debug] Calling handlers : `inventory_handler'
[Fri Jun 16 12:22:03 2017][debug] last_state file: `/usr/local/linkbynet/script/inventaire/http:__yes_ocsinventory/last_state' doesn't exist (yet).
[Fri Jun 16 12:22:03 2017][debug] Section INPUT has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section BIOS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section PRINTERS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section VIDEOS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section HARDWARE has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section SOUNDS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section BATTERIES has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section SOFTWARES has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section MEMORIES has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section CONTROLLERS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section VIRTUALMACHINES has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section STORAGES has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section NETWORKS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section MODEMS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section MONITORS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section DRIVES has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section PORTS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section REGISTRY has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section SLOTS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Section CPUS has changed since last inventory
[Fri Jun 16 12:22:03 2017][debug] Missing value(s): MAC-address . I will send this inventory to the server BUT important value(s) to identify the computer are missing
[Fri Jun 16 12:22:03 2017][debug] sending XML
---------------------------8<------------------------------------------------------------------

Sorry for the delay, my last post seems don't, I'll verify the next times ;)

Don't hesitate to ask if you need others stuffs.

Thanks by advance,

Loïc BRONDIN - Linkbynet.

**Comment by n0F34tur3** [comment]
Hi,

Some suggestions about the log provided ?

Thanks by advance.

Regards,

Loïc BRONDIN - Linkbynet

**Comment by n0F34tur3** [comment]
Hi Guys,

Have you got some news about this issue ?

Thanks ;)

Regards,

Loïc BRONDIN - Linkbynet

**Comment by fbomj** [comment]
Hi,
df check ahs been corrected. Could you make a new test with this correction?
Regards
Frank
