### ISSUE TITLE
Problème avec l'agent OCS sous windows

### ISSUE THREAD

**Issue by raycaloo** [OCSInventory-NG/UnixAgent#78]
Bonjour, 
J'ai récemment installé l'agent OCS pour Windows. La version est la 2.3.0.0 et je ne parviens pas à me connecter au serveur ocs. Les journaux d'événements me donnent l'erreur suivante **_"Service encounter error <Failed to load/parse last inventory state>"_**. J'ai réinstallé plusieurs fois l'agent mais j'ai pas réussi à corriger le problème. Mon OS c'est Windows 10 et je ne sais où trouver le fichier ocsinventory.ini

**Comment by fbomj** [comment]
Bonjour,
Cela ne concerne pas l'agent unifié. Merci d'ouvrir une nouvelle issue sur le bon repository.
Cordialement
