### ISSUE TITLE
Questions / Fix on LWP behavior on HTTPS connection

### ISSUE THREAD

**Issue by gillesdubois** [OCSInventory-NG/UnixAgent#79]
### General informations

Operating system :  
- Mac OS El Captain
- Mac OS High Sierra
Perl version : 5.18.2
LWP version : 6.07 (2016)

### OCS Inventory informations

Unix agent version : 2.3.1 (unreleased) 

### Problem's description

In the first place this behavior can be seen on Mac but I think it's more related to the LWP library.

By default, the agent is using LWP library when Crypt::Ssleay is not available but when using LWP the SSL certificate validation is different and can lead to inventory error (SSL Certificate verify failed)

The problem can only be seen when using a self signed certificate.
I made 3 different servers with SSL self signed and try to use the https inventory and each time the inventory fail on the SSL certificate verify failed. 

After doing some research I saw that self signed certificate validation with LWP can be a bit tricky. Newer versions of LWP has change how to behave with SSL. (6.0 and newer only)

Here is some sources : 
- https://stackoverflow.com/questions/13385846/scripts-broke-after-upgrading-lwp-certificate-verify-failed
- https://stackoverflow.com/questions/37925246/certificate-verify-failed-for-self-signed-on-linux-7-2
- http://www.preshweb.co.uk/2013/03/using-ssl-client-certs-with-perls-lwpuseragent/

### Solution

The solution would be to set theses 2 variables when using LWP : 
- verify_hostname => 1
- SSL_ca_file => "cert_path"

### Inventory log file ( optional )

[ocsinventory.log](https://github.com/OCSInventory-NG/UnixAgent/files/1367745/ocsinventory.log)

**Comment by fbomj** [comment]
Hi,
verify_hotname => 1 this is by default. 
Add SSL_CA_file => "file path" <= already present in the code.
The 2 propositions are already present in the code (see lines 66 to 69 in Agent/Network.pm file).

Does LWP::UserAgent run on MacOS?
Frank

**Comment by gillesdubois** [comment]
This behavior on Mac has been fixed by updating the perl dependencies.
I updated the Darwin perl snapshot and will update the create perl dependencies script for Mac soon.

Regards,
Gilles Dubois.

**Comment by fbomj** [comment]
OK. Nice to see that the problem is solved.
Regards
Frank
