### ISSUE TITLE
SSL dependency absent in Unix Agent rpm

### ISSUE THREAD

**Issue by dvdred** [OCSInventory-NG/UnixAgent#83]
### General informations
Operating system :  CentOS 7.4 (64bit)
Perl version : perl5.16.3

### OCS Inventory informations
Unix agent version : 2.3

### Problem's description
The RPM present at https://www.ocsinventory-ng.org/en/rpm-repository-is-available-for-rhelcentosfedora/ lacks of SSL perl dependecy

*Describe your problem here*
Using ocs-server over https is not possible without installing some other packages:
**yum install perl-LWP-Protocol-https perl-Crypt-SSLeay**

**Comment by kapouik** [comment]
New release 2.4.0 add ssl dependancies
