### ISSUE TITLE
Scan Ip Discover no remonte Seveur OCS

### ISSUE THREAD

**Issue by franck51000** [OCSInventory-NG/UnixAgent#85]
Bonjour,
selon les logs coté Agent  le scan de ipdiscover se passe bien mais ne remonte pas au serveur OCS

Serveur: 

    Nom du système :     Linux x86_64
    Version :     3.10.0-693.2.2.el7.x86_64
    Distribution :     CentOS Linux 7 (Core)
Logiciel
    Version de PHP :     5.4.45
    Serveur Web :     Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.4.45 mod_perl/2.0.10 Perl/v5.16.3
    Serveur SQL :    MariaDB Server version 5.5.56-MariaDB
    Version OCSReports:    2.3.1

### General informations Agent Unix
Operating system :  Debian 
Perl version : This is perl 5, version 20, subversion 2 (v5.20.2)

### OCS Inventory informations
Unix agent version :  2.3.1

### Problem's description
Bonjour,
selon les logs coté Agent  le scan de ipdiscover se passe bien mais ne remonte pas au serveur OCS

### Inventory log file
```

  <IPDISCOVER>
      <H>
        <I>10.x.x.1</I>
        <M>00:00:5e:00:01:01</M>
        <N>-</N>
      </H>
      <H>
        <I>10.x.x.2</I>
        <M>ec:e5:55:53:ca:23</M>
        <N>-</N>
      </H>
      <H>
        <I>10.x.x.3</I>
        <M>ec:e5:55:53:d0:23</M>
        <N>-</N>
      </H>
      <H>
        <I>10.x.x.16</I>
        <M>ec:e5:55:f3:4d:05</M>
        <N>-</N>
      </H>
      <H>
        <I>10.x.x.18</I>
        <M>ec:e5:55:f3:4c:f0</M>
        <N>-</N>
      </H>


</CONTENT>
  <DEVICEID>AgentOcs-2017-10-17-06-59-22</DEVICEID>
  <QUERY>INVENTORY</QUERY>
</REQUEST>
[Wed Oct 18 10:22:41 2017][debug] =BEGIN=SERVER RET======
[Wed Oct 18 10:22:41 2017][debug] $VAR1 = '<?xml version=\'1.0\' encoding=\'UTF-8\'?>
<REPLY>
  <RESPONSE>NO_ACCOUNT_UPDATE</RESPONSE>
</REPLY>
';
[Wed Oct 18 10:22:41 2017][debug] =END=SERVER RET======
[Wed Oct 18 10:22:41 2017][debug] Calling handlers : `end_handler'
[Wed Oct 18 10:22:41 2017][debug] [download] Calling download_end_handler
[Wed Oct 18 10:22:41 2017][debug] [snmp] Calling snmp_end_handler
[Wed Oct 18 10:22:41 2017][info] [download] Beginning work. I am 2174.
[Wed Oct 18 10:22:41 2017][info] [download] Option turned off. Exiting.
[Wed Oct 18 10:22:41 2017][debug] [download] End of work...
```

**Comment by fbomj** [comment]
Bonjour,

Des erreurs dans le fichier de log de l'agent?

Cordialement
