### ISSUE TITLE
Deprecated nmap option

### ISSUE THREAD

**Issue by hschletz** [OCSInventory-NG/UnixAgent#86]
### General informations
Operating system :  Linux (Debian 9.2)
Perl version : irrelevant

### OCS Inventory informations
Unix agent version : latest master

### Problem's description
nmap generates warnings because it is invoked with the deprecated -sP option. -sn should be used instead. The -sn option has been around for several years, so it should be safe to use.

**Comment by gillesdubois** [comment]
Hi,

Can you provide a source of the deprecated and the warnings generated ?

Regards,
Gilles Dubois.

**Comment by hschletz** [comment]
```
# ./ocsinventory-agent --devlib
[info] --devlib are found, Developer mode enabled
Warning: The -sP option is deprecated. Please use -sn

# grep -rne '-sP'
lib/Ocsinventory/Agent/Modules/Snmp.pm:416:            $nmaparser->parsescan("nmap","-sP",$net_to_scan);
lib/Ocsinventory/Agent/Backend/IpDiscover/Nmap.pm:54:    $nmaparser->parsescan("nmap","-sP","-PR","$network/24");
```
Replacing -sP with -sn removes the warning.

**Comment by fbomj** [comment]
Hi,

This is corrected and released in the next version.
Regards
Frank
