### ISSUE TITLE
EDID.pm is missing on macOS

### ISSUE THREAD

**Issue by MikaelUrankar** [OCSInventory-NG/UnixAgent#91]
### General informations
Operating system :  macOS 10.13.1
Perl version : v5.18.2

### OCS Inventory informations
Unix agent version : 2.3.1

### Problem's description
Video Card detection doesn't work

EDID.pm is missing in the agent:
Failed to load Ocsinventory::Agent::Backend::OS::MacOS::Video: Can't locate Parse/EDID.pm in @INC (you may need to install the Parse::EDID module) (@INC contains: /Applications/OCSNG.app/Contents/Resources//lib/ /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Backend/OS/MacOS/Video.pm line 4

**Comment by fbomj** [comment]
Hi,

This module is not installed with the agent. You have to install it manually.

Regards

**Comment by MikaelUrankar** [comment]
I disagree, edid.pm should be part of the agent.
You already bundle a bunch of perl library (macosx-perl-lib-dep-snapshot.tar.gz), accessible in  /Applications/OCSNG.app/Contents/Resources/lib, why not doing the same for parse/edid.pm ?

**Comment by gillesdubois** [comment]
Hi,

Indeed edid is not shipped in mac os agent. It will be fixed in the next release.
Thx for your contribution.

Regards,
Gilles Dubois.

**Comment by fbomj** [comment]
If you use the unified agent you have to install it manually. I'm agree with you  that this module must be shipped with the mac osx agent. 
Regards
Frank
