### ISSUE TITLE
Undefine Memory info. macOS Sierra.

### ISSUE THREAD

**Issue by carrolcox** [OCSInventory-NG/UnixAgent#93]
### General informations
Operating system :  Apple macOS Sierra (10.12.6)
Perl version : 5.18

### OCS Inventory informations
Unix agent version : Ocsinventory unified agent for UNIX, Linux and MacOSX 2.3.1

### Problem's description
Regression error after update from 2.1.1 to 2.3.1
```
[Thu Nov  9 10:40:50 2017][debug] runWithTimeout(): unexpected error: Undefined subroutine &Ocsinventory::Agent::Backend::OS::MacOS::Mem::can_load called at /Applications/OCSNG.app/Contents/Resources//lib/Ocsinventory/Agent/Backend/OS/MacOS/Mem.pm line 6.
[Thu Nov  9 10:40:50 2017][debug] Ocsinventory::Agent::Backend::OS::MacOS::Mem ignored
```

**Comment by carrolcox** [comment]
@gillesdubois please help

**Comment by MikaelUrankar** [comment]
It's fixed on the master branch: https://github.com/OCSInventory-NG/UnixAgent/blob/master/lib/Ocsinventory/Agent/Backend/OS/MacOS/Mem.pm
