### ISSUE TITLE
agent libvirtd missing/needed ???

### ISSUE THREAD

**Issue by piozylka** [OCSInventory-NG/UnixAgent#97]
Operating system :  CentOS 6.9
Perl version : perl5 (revision 5 version 10 subversion 1)
Unix agent version : 2.3

i try to install to one of my servers:
perl Makefile.pl -> ok
make -> ok
make install -> ok
after that agent tries to send information to ocs server and i get:
```
Launching OCS Inventory NG Unix Unified agent...
error: Failed to reconnect to the hypervisor
error: no valid connection
error: internal error Unable to locate libvirtd daemon in /usr/sbin (to override, set $LIBVIRTD_PATH to the name of the libvirtd binary)
```

Never had a problem with installation on different servers but this ...
Do i have to install libvirtd ???

**Comment by fbomj** [comment]
Hi,
On your server is virsh command installed? Could you please post the content of ocsinventory-agent.log file?
Regards
Frank

**Comment by piozylka** [comment]
Yep you are right, this was not virsh but another set of packages for virtualization.
Uninstalled and evrth is working,
THX
SOLVED
