### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by catharinasilva** [OCSInventory-NG/UnixAgent#99]
*It's hard to solve a problem when important details are missing, that why we added this template, to help you and us.*

### General informations
Operating system : Fedora 27
Perl version : 5.24

### OCS Inventory informations
Unix agent version : 2.3 

### Problem's description
I and my team got a problem with the installation agent. It can't find any archive in @INC even if we have them.

**Comment by fbomj** [comment]
Hi,
How do you install the agent?
Regards

**Comment by catharinasilva** [comment]
Hi,

We install all necessary modules. Download the agent via wget and then we
start configuration.

Em 28 de dez de 2017 1:26 PM, "fbomj" <notifications@github.com> escreveu:
